table Orders
	lineageTag: e29d6e35-a5a1-4651-abd9-d491fcf37ec5

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dba77977-2cc5-452e-b3e5-6f7239ba1131
		annotation Copilot_Description = Migrated from Tableau: SUM([Sales]) | DAX: SUM('Orders'[Sales])

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f3abb5cd-ea97-4671-9c40-3665c5ad9f14
		annotation Copilot_Description = Migrated from Tableau: SUM([Profit]) | DAX: SUM('Orders'[Profit])

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 95c2ecdb-7fc8-49ce-a7e6-99c215b0a371
		annotation Copilot_Description = Migrated from Tableau: SUM([Profit]) / SUM([Sales]) | DAX: SUM('Orders'[Profit]) / SUM('Orders'[Sales])

	measure 'Number of Orders' = DISTINCTCOUNT('Orders'[Order ID])
		displayFolder: Measures
		lineageTag: 52e48c98-2f84-4347-bceb-68941f074d15
		annotation Copilot_Description = Migrated from Tableau: COUNTD([Order ID]) | DAX: DISTINCTCOUNT('Orders'[Order ID])

	measure 'Total Sales Formatted' = VAR _val = [Total Sales] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: db6885ee-8b0e-469f-b6c6-6b799177b9ad
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Sales (K/M/B)

	measure 'Total Profit Formatted' = VAR _val = [Total Profit] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: f26bc869-328a-423c-b814-e4e825971345
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Profit (K/M/B)

	measure 'Profit Ratio Formatted' = VAR _val = [Profit Ratio] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 492d7c8a-8eb8-4588-bce9-6043e928d0d3
		annotation Copilot_Description = Dynamic numeric abbreviation for Profit Ratio (K/M/B)

	column 'Row ID'
		dataType: int64
		lineageTag: e76db0b5-369c-4481-adb0-87619c588d6b
		summarizeBy: sum
		sourceColumn: 'Row ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: bebfb0ec-bc47-407d-b106-f1017bfc003c
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9ea32c71-0eb2-4df2-b7f6-98602b4bbb6a
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b94f135-32fd-498d-94f8-f9bdaa35e4e4
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: e6215663-2c19-4a32-83ec-326cc63fad4c
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 75b4022c-77b4-42b7-9f38-c9265bcfb1eb
		summarizeBy: none
		sourceColumn: 'Customer ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 61cddba1-69f4-4142-8f82-6c36d36fbef1
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 654d8af0-c163-4882-8707-81839a09dddc
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 5121a8a5-e197-4ba7-88e1-d078a632c244
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e299b889-f428-42b6-b7c5-5ef66c99f08e
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 87870ea2-3595-481c-ad85-ef19adaab49b
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 0d306e5c-9699-4745-b35c-2bbb4d4f5c00
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 08aa76e8-31ec-405b-bb3b-a84ad2f6e979
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 54b9a508-1c13-4c87-8af0-898bb08fcfce
		summarizeBy: none
		sourceColumn: 'Product ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: f729b29b-de2e-42f7-8031-fce56ad6a85d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 257a49fc-9b95-4569-b9a2-364638a1da8c
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 125f078e-9ffe-4c0c-a34c-3e5337d77a34
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: ec39b96b-e2e4-4496-a4e6-8e5268f02ebe
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 55eaadfc-b3ba-417b-a936-9c199edda908
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: cbb99413-2643-43b1-ae6a-ac890dc267c7
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: e389046e-b07d-47f0-9fde-11f10884c345
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	partition 'Orders-2326ee37-d6b6-4757-b7db-fd1d9baebf93' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Orders",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 21 columns and 7 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (21 columns total).

