table People
	lineageTag: e417f998-909d-490e-89b9-49d1a80ca1e9

	column 'Regional Manager'
		dataType: string
		lineageTag: a06a98cf-6b10-4b05-a195-1f5993d558ee
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b4acb37c-7832-4c46-adfd-ac71d6451726
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-b03a264e-8da2-4596-bce8-de21c488b0f6' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Regional Manager, Region.

