table 'Top Customers'
	lineageTag: f7df4328-8e15-4674-8309-992a0dba0dea

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: 9d0e5e98-4f80-4210-a91c-17693fe4ac27
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top Customers'[Value], 5)

	column Value
		dataType: int64
		lineageTag: a75d1cdf-8cba-439e-8bd0-8a9e5a67e51b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-36a9bf4f-9f67-49e6-a3cc-954242398809' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

