table Orders
	lineageTag: fe53b3a9-5752-475c-a71e-38a16217afa2

	measure Margin = SUM('Orders'[Profit])/SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 398c97ff-b8a2-49c4-9beb-48027bab5639
		annotation Copilot_Description = Migrated from Tableau: SUM([Profit])/SUM([Sales]) | DAX: SUM('Orders'[Profit])/SUM('Orders'[Sales])

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: 6ddd3207-5d13-42b9-984b-0c80161a4b9e
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	measure 'Margin Formatted' = VAR _val = [Margin] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 6fc92a1a-a988-40d0-a1e6-bf5b7fb3d5a0
		annotation Copilot_Description = Dynamic numeric abbreviation for Margin (K/M/B)

	column 'Row ID'
		dataType: int64
		lineageTag: 2427d3b1-fe42-4273-8264-cdc1da8d7b11
		summarizeBy: sum
		sourceColumn: 'Row ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 0ae08be0-3454-4e3e-90d2-cd882828bd95
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 042c2e0a-f397-4e2d-a84f-3781f8a40da4
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0c800369-9fee-4bd9-9a3f-e3c29652bb73
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 3e982b97-f63c-4051-bad9-5a3b031d9033
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 88872606-b464-44c8-9753-6ba71c19840b
		summarizeBy: none
		sourceColumn: 'Customer ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: c9c101ef-0379-49fe-9055-0e25646f1929
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: fa3103d5-3266-4f35-8cc9-7d1e37eb6965
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 485f9dbc-dfe5-4b87-9e65-479008e37b69
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: de9f4013-b9d4-4764-95e1-81b70c8ab733
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: aa39aeea-9828-4227-8bbb-841d6c59f5db
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 6217c2c1-520a-4de4-9bc2-7b3020b48673
		summarizeBy: none
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 2c322d53-a7f5-4c99-b498-be616ef062dc
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4c71dbf5-e6eb-4eea-827b-fdec8899bb08
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: ae70d14e-a579-4e39-a25f-9b26eb3cebca
		summarizeBy: none
		sourceColumn: 'Product ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 601be681-1386-40e4-9a2f-fb1b001b036c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 2f3b6aec-9f6d-42cd-ab0a-f9c3ad4bf78d
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: e503f6ad-b368-445c-a3e2-6116ed09dabd
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: f656d8a6-4ebb-4a47-a3d7-4f5c65c921f5
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 9dc7cd3f-ae25-4bec-bdc3-9728948c212a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: cf1db4cf-e8eb-41d2-91a1-7861417f67d1
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: be4cdf24-8d61-4e62-85db-56bd0addc9d2
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 63490375-5e3f-4f82-a11e-b69e8b7b973e
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: 89c7be3b-da1f-4509-8076-5b10ae15bd08
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column 'Discount (bin)'
		dataType: int64
		lineageTag: da8156d1-ea6c-4ed3-889d-7f7b499c189b
		summarizeBy: none
		sourceColumn: 'Discount (bin)'

		annotation SummarizationSetBy = Automatic

	column 'Action (Discount (bin))'
		dataType: string
		lineageTag: a16403a2-6bdc-4014-be57-9252168b6b56
		summarizeBy: none
		sourceColumn: 'Action (Discount (bin))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Segment)'
		dataType: string
		lineageTag: b87be354-c22c-44b4-aef2-bb5e026eab2e
		summarizeBy: none
		sourceColumn: 'Action (Segment)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (State)'
		dataType: string
		lineageTag: 25b29fe8-59e4-4a1e-a753-64241b5b502b
		summarizeBy: none
		sourceColumn: 'Action (State)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Order Date))'
		dataType: string
		lineageTag: 7c34be04-335e-4977-bb1b-4dfe4ff9f3d1
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Order Date))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category (group)'
		dataType: string
		lineageTag: 708c4930-7f84-4eed-ae36-0e34bdfdbd15
		summarizeBy: none
		sourceColumn: 'Sub-Category (group)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Orders-3fbc4ee7-30b7-4c3f-81fa-d24c3a8c56a1' = m
		mode: import
		source =
				let
				    // Source Excel: Global Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Global Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Orders",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "City", "State", "Country", "Postal Code", "Market", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit", "Shipping Cost", "Order Priority"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Country", type text},
				        {"Postal Code", type text},
				        {"Market", type text},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number},
				        {"Shipping Cost", type number},
				        {"Order Priority", type text}
				    }),
				    #"Added Discount (bin)" = Table.AddColumn(#"Changed Types", "Discount (bin)", each [Discount], Int64.Type),
				    #"Added Action (Discount (bin))" = Table.AddColumn(#"Added Discount (bin)", "Action (Discount (bin))", each Text.From([#"Discount (bin)"]), type text),
				    #"Added Action (Segment)" = Table.AddColumn(#"Added Action (Discount (bin))", "Action (Segment)", each Text.From([#"Segment"]), type text),
				    #"Added Action (State)" = Table.AddColumn(#"Added Action (Segment)", "Action (State)", each Text.From([#"State"]), type text),
				    #"Added Action (YEAR(Order Date))" = Table.AddColumn(#"Added Action (State)", "Action (YEAR(Order Date))", each Text.From(Date.Year([#"Order Date"])), type text),
				    #"Added Sub-Category (group)" = Table.AddColumn(#"Added Action (YEAR(Order Date))", "Sub-Category (group)", each if [#"Sub-Category"] = "Art" then "Miscellaneous_Office_Supplies" else if [#"Sub-Category"] = "Binders" then "Miscellaneous_Office_Supplies" else if [#"Sub-Category"] = "Envelopes" then "Miscellaneous_Office_Supplies" else if [#"Sub-Category"] = "Fasteners" then "Miscellaneous_Office_Supplies" else if [#"Sub-Category"] = "Labels" then "Miscellaneous_Office_Supplies" else if [#"Sub-Category"] = "Paper" then "Miscellaneous_Office_Supplies" else if [#"Sub-Category"] = "Supplies" then "Miscellaneous_Office_Supplies" else "Other", type text),
				    Result = #"Added Sub-Category (group)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 30 columns and 3 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (30 columns total).

