table dim_customer
	lineageTag: 5b4a7571-c3c2-4155-ab01-41d6757c45f5

	column customer_key
		dataType: int64
		lineageTag: c95829dd-7455-4031-b102-83a9b0d42570
		summarizeBy: sum
		sourceColumn: customer_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: f43c6e25-5d85-4864-8360-a5179aa97171
		summarizeBy: none
		sourceColumn: customer_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: ef887194-776d-4cfb-9212-3bfa16b85583
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: fadc48d3-502c-4686-9d29-91c938c0e500
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: dd23877d-283b-443f-a36c-429652b9dc74
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 6c0a1680-bf8a-4bed-ab7a-d3b73adb8b81
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: 04be9750-9472-4d4f-9748-4174a52f377c
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column company_size
		dataType: string
		lineageTag: 68855fd2-d110-44d0-831c-2358df2875cf
		summarizeBy: none
		sourceColumn: company_size

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 65b08c93-4af2-4c60-8d3d-4764b06bd581
		summarizeBy: none
		sourceColumn: first_order_date

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		formatString: #,0.00
		lineageTag: 0635af1b-eb26-49ff-a087-c458c1f1efd6
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: a119a9d2-fc72-4205-bc90-86a98dffda43
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		lineageTag: c704d0de-a10c-4127-a40c-6df56869e858
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	partition 'dim_customer-0ad55cf3-2ecd-4ff2-877a-21f0d765c093' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_key", "customer_id", "customer_name", "email", "phone", "segment", "industry", "company_size", "first_order_date", "credit_limit", "account_manager", "is_active"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_customer Table" = #"SALES"{[Name="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_customer Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"email", "Email"}, {"phone", "Phone"}, {"segment", "Segment"}, {"industry", "Industry"}, {"company_size", "Company Size"}, {"first_order_date", "First Order"}, {"credit_limit", "Credit Limit"}, {"account_manager", "Account Manager"}, {"is_active", "Active?"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

