table Returns
	lineageTag: cd8397c6-ea22-464a-bb5f-e5fde4376660

	column Returned
		dataType: string
		lineageTag: 977a0912-878c-447f-a194-302fc32cff12
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 949236ed-2e3f-4d23-97ef-c7238005e95a
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-2b3ac657-22b2-40cf-9b90-f2641523ba61' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xls
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xls"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

