table 'Top Customers'
	lineageTag: b91abd95-4029-4146-9bd8-f93d3354104f

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: beae6ad6-83c5-47f0-a6ee-6f5c3e04ac5f
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top Customers'[Value], 5)

	column Value
		dataType: int64
		lineageTag: 6a683aa9-a9b0-4451-8510-d1d8a44fb546
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-9b3badc1-5895-4e56-aa99-c30db13e6be6' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

