table Rebounds
	lineageTag: 2ab584fb-cf3e-4e79-aa2f-6586c6acf283

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 33c75a62-0e34-4ef3-a5cc-00daf5a9edc8
		annotation Copilot_Description = DAX: SELECTEDVALUE('Rebounds'[Value], 1.0)

	column Value
		dataType: double
		lineageTag: 08d136f7-a0ac-42d2-8090-00a6d0a1dfc6
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: d7a6845e-e9ec-4b8a-97bb-f7c42e2e2abe
		summarizeBy: none
		sourceColumn: Name
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-be22d614-04e2-46ab-9ad5-075f96bceaf8' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, "Name", STRING, {{1.0, "Average Deffensive Rebounds per Game"}, {2.0, "Average Offensive Rebounds per Game"}, {3.0, "Average Rebound per Game"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns and 1 measures: Value, Name.

