table 'Profit Bin Size'
	lineageTag: c747f740-e40e-4d60-9829-f70be5e2f27e

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 215f89c8-1b3b-4bc2-9038-a12666fa3b89
		annotation Copilot_Description = DAX: SELECTEDVALUE('Profit Bin Size'[Value], 200)

	column Value
		dataType: int64
		lineageTag: da7ae8d0-309b-4ed2-848b-01cd2b48f242
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-0688f23b-4dae-43da-b945-248b4f82572d' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

