table xy
	lineageTag: d96e0f16-c5a1-402b-b4cc-f859271ea11c

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: 98b91562-75b1-4b61-afe7-72790da05f85
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: 68428f95-f60a-486e-a12f-812aac77e749
		annotation Copilot_Description = Migrated from Tableau: SUM([x]) + SUM([y]) | DAX: SUM('xy'[x]) + SUM('xy'[y])

	column a
		dataType: string
		lineageTag: e91a20e9-353c-4929-9578-c20d7eca4fac
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: cc5f201f-5d8a-4d25-92fd-e3b3a588c142
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 12ed56e9-92ea-4684-8c14-24153d0b290c
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-8b7e7d44-cad9-4963-8be2-2737f0bed883' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 2 measures: a, x, y.

