// DAX measures for table: Orders
// Auto-generated by Tableau → Power BI migration

Total Sales =
SUM('Orders'[Sales])

Total Profit =
SUM('Orders'[Profit])

Profit Ratio =
SUM('Orders'[Profit]) / SUM('Orders'[Sales])

Number of Orders =
DISTINCTCOUNT('Orders'[Order ID])

