table Calendar
	lineageTag: a1f0d8be-c6e7-4195-9f62-852056718f02

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5d5726c7-4005-4a48-bcde-8cf4b806279a
		annotation Copilot_Description = DAX: TOTALYTD([Profit Ratio], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 877a56c5-a310-4e71-b2a1-ce23d2d9b214
		annotation Copilot_Description = DAX: CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 8a5a5e4f-2fcb-46c4-934d-d41145470464
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dc2bc770-20f3-4f52-8cdc-7f2ca4134626
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4e30cc7c-6dfb-4ece-81cb-a939dfbb6964
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a173566e-f31c-45f1-b385-726efb17ae49
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 226e4955-672c-402f-a5cb-0da3454a8989
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0a44dfd2-af51-496b-a8e1-b8db8f0bce99
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e3082216-f222-4761-a47a-62822d13d70b
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a666b36d-c02f-4fcc-8fef-9850f125f4c2
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d30cc8e9-7ef9-4784-9d72-1c888bd4aa16
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 78a5758c-13e9-401f-9011-dc5e525a457f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5bfda9b9-4792-4fcf-b086-2367df712a35

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: bb000e4d-98ba-4bc2-92fc-cf5202e16f8e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c6ffafd6-6bb3-4c16-b4e0-1432f570179f

		level Day
			ordinal: 3
			column: Day
			lineageTag: 287a2d8c-2d82-4e5f-ba5c-72984253b3b4


	partition 'Calendar-2f2b2059-1dc6-4e4b-a8b7-93a9a40569b6' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

