table 'Profit Bin Size'
	lineageTag: dc99d840-2cc2-42fb-b93c-cfe0a107e9ee

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 660f695f-9b04-4831-9609-efcb257bc254
		annotation Copilot_Description = DAX: SELECTEDVALUE('Profit Bin Size'[Value], 200)

	column Value
		dataType: int64
		lineageTag: be109de7-d913-4fc2-8faf-b41cbf59eb04
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-cea016c0-c14b-43ab-ad7a-3c16a32658f9' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

