table Returns
	lineageTag: e296390e-9c52-49f8-ba4a-8fdc930fd79c

	column Returned
		dataType: string
		lineageTag: 81e10dbe-376e-4125-bda9-1450a6480d21
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 674b1676-4702-4534-8255-5c69314cfd0b
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-a5e080b5-41ae-4c2b-b31a-4f052bd4d7e3' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xls
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xls"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

