table 'Top Customers'
	lineageTag: a0ee492b-c479-4c6f-8f19-41541d992cca

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: c13348cb-cb29-4538-926d-07614fb5d3f5
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top Customers'[Value], 5)

	column Value
		dataType: int64
		lineageTag: 589837c8-3320-4d3f-af9a-1693bb8a4d2b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-23400468-cd48-40d4-9cca-efa43d3c86f0' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

