table Campaigns
	lineageTag: 47e7a84f-4de0-4f17-a63b-585598892192

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: a6b75504-7466-49de-ada0-4e895a59d8aa
		annotation Copilot_Description = Migrated from Tableau: COUNTA([lead_name]) | DAX: COUNTA('Leads'[lead_name])

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Campaigns'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8a0dedf4-8e05-4049-8e95-28b9b20bcccc
		annotation Copilot_Description = Migrated from Tableau: CORR([budget], [deal_value]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[de]))...

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 84377844-a581-4733-8795-8111f5f999f6
		annotation Copilot_Description = Migrated from Tableau: COVAR([spend], [engagement_score]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'),))...

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0dd73bcb-8431-4db9-ada8-55aac6a6c638
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [channel] : AVG([deal_value])} | DAX: CALCULATE(AVERAGE('Leads'[deal_value]))

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0a68cdfb-19cf-49a2-9a26-4f64eea656b4
		annotation Copilot_Description = Migrated from Tableau: (SUM([deal_value]) - SUM([spend])) / SUM([spend]) | DAX: (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b9a8f151-dabd-455e-b964-2a2a21c27d48
		annotation Copilot_Description = Migrated from Tableau: SUM([spend]) / COUNTD([lead_id]) | DAX: SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1517cf02-db0f-4163-b7ad-855f36b07706
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MAX((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1ac6b583-cabf-4aed-8400-42e4c0056938
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MIN((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))

	measure 'Cumulative Leads' = /* TODO: DAX conversion validation failed for Calc_CumLeads: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: 9af15e70-dd56-4183-a152-130ebd869d3d
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(COUNTD([lead_id])) | DAX: /* TODO: DAX conversion validation failed for Calc_CumLeads: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 16eccd8e-4b99-49e9-9fa5-ed41f66c66c7
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [lead_status] = "Won" THEN 1 ELSE 0 END) / COUNT([lead_id]) | DAX: SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])

	measure 'Target Channel' = "Email"
		lineageTag: 602f136c-302b-43f4-b3d1-72f780c2379e
		annotation Copilot_Description = DAX: "Email"

	column campaign_id
		dataType: int64
		lineageTag: a0bc51b4-151c-424b-8cf5-811925a4c36c
		summarizeBy: sum
		sourceColumn: campaign_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 911506a6-0fa7-4d7c-81ae-b20a1d69f84f
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: fcf125b0-6644-479f-acc3-a21f65a9993e
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 522fdcb4-e492-4446-8852-edbbacc4e670
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c270e4b-a627-407d-a1e3-1b6b7892451d
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: a4818c08-6572-4808-8a26-39738850cd30
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: 2d080207-0d07-4fbc-9d86-1030af6377c0
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: 30588b9a-7676-48e3-9958-c26d3454da91
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: 7aadc54e-0769-4d36-8bd5-226d3ff34c85
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 9284b050-6c4a-4995-bb9f-03c938407507
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: 8a00955d-06c6-48d7-b448-9b57c728119c
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: bcc1b612-dc8c-4f0c-b172-141bf555467c
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: dfa5a911-6655-40f1-9fe6-6d4ab908ee59
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 740be21c-ca4d-467b-bbf7-d359ce253814
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(CALCULATE(SELECTEDVALUE(Leads[email])), FIND("@", CALCULATE(SELECTEDVALUE(Leads[email]))) + 1, LEN(CALCULATE(SELECTEDVALUE(Leads[email]))))
		dataType: string
		lineageTag: 7fe080a3-9386-4030-a44d-d8ada2bba148
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(CALCULATE(SELECTEDVALUE(Leads[lead_name])), FIND(" ", CALCULATE(SELECTEDVALUE(Leads[lead_name]))) - 1)
		dataType: string
		lineageTag: 6859c123-4d95-40b0-a81e-3a2927bd796e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(CALCULATE(SELECTEDVALUE(Leads[lead_name])), FIND(" ", CALCULATE(SELECTEDVALUE(Leads[lead_name]))) + 1, LEN(CALCULATE(SELECTEDVALUE(Leads[lead_name]))))
		dataType: string
		lineageTag: 2b3fdcce-a889-4694-acd3-3434fc402809
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(CALCULATE(SELECTEDVALUE(Leads[lead_name])))
		dataType: int64
		lineageTag: 729ac49d-fada-4673-abe9-148f793c4e7f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(CALCULATE(SELECTEDVALUE(Leads[phone])), "-", ""), " ", ""))
		dataType: string
		lineageTag: 339f9717-04f4-4e70-bd2d-9b9d6b553167
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(CALCULATE(SELECTEDVALUE(Leads[phone])), 4)
		dataType: string
		lineageTag: fe2017f8-b085-4d23-a705-5de9b30fc67e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: da6b73b0-a764-4148-85f3-c034d66c66cd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise'
		dataType: boolean
		lineageTag: 787cb183-d2a3-4a71-8b4b-7bd4f9d78d60
		summarizeBy: none
		sourceColumn: 'Is Enterprise'

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = /* REGEXP_MATCH: complex regex "^[a-z0-9_-]+$" — verify manually */ CONTAINSSTRING('Campaigns'[utm_campaign], "^[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: 083a0b19-b473-4e58-b66c-44d40a4b02a7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = /* REGEXP_REPLACE("https?://"): complex regex — verify manually */ SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: 31d563ff-f882-4bec-8551-2ef64563fa85
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year'
		dataType: dateTime
		formatString: General Date
		lineageTag: aec80a4c-45f8-4e2b-a307-9556ca8f81c7
		summarizeBy: none
		sourceColumn: 'Campaign Year'

		annotation SummarizationSetBy = Automatic

	column 'Start Month'
		dataType: int64
		lineageTag: 41b98501-fa81-46ef-9703-351c689c0a8a
		summarizeBy: none
		sourceColumn: 'Start Month'

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: 80233b88-b41b-4f3e-a4c0-a8359b8f07ea
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days'
		dataType: int64
		lineageTag: 6d63d2f2-c36c-47fe-8e10-f97a60e04a1f
		summarizeBy: none
		sourceColumn: 'Campaign Days'

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: 24064753-7fd1-4b20-b588-97d6ed56f505
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-58b0cf96-a86b-4eb9-bf34-d01e812bd471' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Campaigns"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"campaign_id", "campaign_name", "channel", "start_date", "end_date", "budget", "spend", "target_audience", "creative_url", "utm_source", "utm_medium", "utm_campaign", "region", "status"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    #"Added Is Enterprise" = Table.AddColumn(#"Renamed Columns", "Is Enterprise", each Text.Contains([target_audience], "Enterprise"), type logical),
				    #"Added Campaign Year" = Table.AddColumn(#"Added Is Enterprise", "Campaign Year", each #date(Date.Year([start_date]), 1, 1), type datetime),
				    #"Added Start Month" = Table.AddColumn(#"Added Campaign Year", "Start Month", each Date.Month([start_date]), Int64.Type),
				    #"Added Campaign Days" = Table.AddColumn(#"Added Start Month", "Campaign Days", each Duration.Days([end_date] - [start_date]), Int64.Type),
				    Result = #"Added Campaign Days"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 29 columns and 11 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (29 columns total).

