table 'Min Budget'
	lineageTag: a73d9af9-22c4-4d88-b928-fee91a85c304

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 94a28a4b-ffbe-4e36-ba0b-6a493704011d
		annotation Copilot_Description = DAX: SELECTEDVALUE('Min Budget'[Value], 5000)

	column Value
		dataType: double
		lineageTag: ac142c11-f967-4cb1-8810-9c63cb7da897
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-ddc841cf-f6fd-4019-9429-70823b77d1f7' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

