table Calendar
	lineageTag: bbe81bed-9760-48d2-b46d-441be0f71ca9

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b79c4ce2-fee0-433e-b2d4-c86ca4f1ee31
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 00950207-2474-4810-a407-606c3f6b2b0a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a81f1d3a-d5cc-434a-afd5-6760e6a1109a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 4b8e7118-0c03-4496-90de-aa671f7bab8c
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a961cdf7-c338-4841-9d76-4e580ffda90e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 161b36f4-8808-4977-9452-cbf32f1438da
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 78d69728-5379-4c08-b27f-053674ff3b6c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 89a62b3f-1a42-470e-bd5d-35768cf7dce8
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 11fcec2e-7492-4a3e-b5fc-6cdbf4e4d712

		level Year
			ordinal: 0
			column: Year
			lineageTag: dc4b8301-a0e9-40e6-8ef0-5725c7ecb62e

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 1783b74c-305f-4a1a-8141-b7eaa2d67ebe

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3b6a0e6b-1b54-4484-a820-cba298bd3d8d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9055928b-6b8c-4ad8-83d7-e22c4dfbed0b


	partition 'Calendar-795d6316-d76b-4a29-afd0-af6514751b98' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

