table 'Objectif Marge'
	lineageTag: 53b53593-4918-4a36-b329-214b89c62f4a

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: 0cbaa781-6e36-4de4-9f44-ce462dabbc18
		annotation Copilot_Description = DAX: SELECTEDVALUE('Objectif Marge'[Value], 0.15)

	column Value
		dataType: double
		lineageTag: 29d02c69-cdc5-430d-aec2-68f2649acdce
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-d64950e7-b3f5-4854-8a30-38ab02c2e916' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

