table Produits
	lineageTag: 810b3c64-237b-45dc-ab81-46749da90f1c

	column produit_id
		dataType: int64
		lineageTag: c8b92f51-11b3-4533-8a30-ac0e859bf2b8
		summarizeBy: sum
		sourceColumn: produit_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_produit
		dataType: string
		lineageTag: df9d1fa2-d01c-4bf3-bb1b-63d11cc273a0
		summarizeBy: none
		sourceColumn: nom_produit

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: 1969be6f-95a0-4b27-b4d2-e4146d2bea10
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: d911d23b-2268-4198-a974-ba3e3a052e84
		summarizeBy: none
		sourceColumn: sous_categorie

		annotation SummarizationSetBy = Automatic

	column marque
		dataType: string
		lineageTag: 293b1c74-eaff-4099-afda-a6bea7f48f75
		summarizeBy: none
		sourceColumn: marque

		annotation SummarizationSetBy = Automatic

	column cout_achat
		dataType: double
		formatString: #,0.00
		lineageTag: 4cb63812-cd2d-4764-b85c-056be935cd5b
		summarizeBy: sum
		sourceColumn: cout_achat

		annotation SummarizationSetBy = Automatic

	partition 'Produits-4f24a7e0-91ed-426a-b69b-1b80ed6c3c58' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Produits"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"produit_id", "nom_produit", "categorie", "sous_categorie", "marque", "cout_achat"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"produit_id", "ID Produit"}, {"nom_produit", "Nom du Produit"}, {"categorie", "Catégorie"}, {"sous_categorie", "Sous-Catégorie"}, {"marque", "Marque"}, {"cout_achat", "Coût d'Achat"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

