table 'Top N Produits'
	lineageTag: c45b8c1a-0fdd-40e9-a27b-80fef9624fb3

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: 4f225eef-a04b-42c0-a97d-7281a7095eb9
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Produits'[Value], 10)

	column Value
		dataType: int64
		lineageTag: 1117bcad-3511-46cd-a307-a5f522fe5188
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-b326c872-ed16-4e29-89f1-cc194adb2416' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

