table Calendar
	lineageTag: b51494c6-5ff3-4422-9833-9bdeb6e16803

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: acd9fccb-3b9f-4202-8e62-3186890746f6
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ea51c6d7-1b68-4558-85f7-b0b1940c6a3a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 53c496fc-87dd-4442-91f5-d46ec391092f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 50d3eae1-e0ed-4ab4-859f-a967be93108f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0d9a4168-bb3a-4f70-8252-1bb0d02e8cd2
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 52859a73-fc7d-4460-8ac2-03416334dac8
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1812e49e-beb3-4689-955d-858a670de2c0
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 63ff7e32-301f-46dc-a683-d4caf317736f
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 4553371e-8a95-4e43-a939-6f9100c0d8fa

		level Year
			ordinal: 0
			column: Year
			lineageTag: ba4d5e26-c6b1-4b49-ba67-2dfd8f6593d8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ea56f461-7716-42f0-a4b9-0cdb2b3e2af1

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 22a7ac05-d6d3-4853-9a52-2b4059453e83

		level Day
			ordinal: 3
			column: Day
			lineageTag: 78b7cabb-dd0b-4f10-94ec-6c1ed0cd24b2


	partition 'Calendar-aa2f2427-a369-42be-98c5-94a99dbcc4bb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

