table Orders
	lineageTag: 45acc393-1342-4697-aec9-0f5cbebff748

	column 'Row ID'
		dataType: int64
		lineageTag: 669b0378-c791-494a-86b5-f20fe2a65899
		summarizeBy: sum
		sourceColumn: 'Row ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		lineageTag: 46468870-ff6f-4fcb-80ff-7f682e288da4
		summarizeBy: sum
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2d1df837-bffa-4c61-8d63-df7708964886
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: b05d2c72-2057-482c-863a-f92c2f997894
		summarizeBy: none
		sourceColumn: 'Order Priority'

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		lineageTag: ea959879-fa64-4df7-b705-198adec29ea7
		summarizeBy: sum
		sourceColumn: 'Order Quantity'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: bac4dbd1-f421-4f48-a12c-fcd2c57b4ce0
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: 26d79d53-4a9d-4564-b5d9-82bd43d6e238
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: ad1bd537-ec9e-4a2d-b736-59d62bb550a6
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: 8f811d13-e3af-45ce-aa6b-b5009e667cae
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,0.00
		lineageTag: 35564c7f-6a56-46f5-90bf-33c3cdce1c01
		summarizeBy: sum
		sourceColumn: 'Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Shipping Cost'
		dataType: double
		formatString: #,0.00
		lineageTag: 333499fb-ef24-4e0a-a70a-0fd23ef415cd
		summarizeBy: sum
		sourceColumn: 'Shipping Cost'

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: cab4a25d-4a53-4e8c-a1cd-574ad8ad867e
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 154d419b-c638-4817-a501-a5f9f3699fd3
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: 474ff2d1-6e95-4efa-a0a4-3e8fafdea0a4
		summarizeBy: none
		sourceColumn: 'Zip Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a40086cc-4298-4b12-9ab5-5025c0228cdc
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 13cea8f4-4506-4bb8-89aa-fb530229243e
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: d9f051ab-e668-417e-8e72-d25c3b5ffa80
		summarizeBy: none
		sourceColumn: 'Customer Segment'

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: bca60637-aed2-4cdc-ae00-71981d015138
		summarizeBy: none
		sourceColumn: 'Product Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 6dad2cd7-3a06-436e-83d1-c0807bb06590
		summarizeBy: none
		sourceColumn: 'Product Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 444e6512-6798-4624-bdb4-691ffa6a0f40
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: 8f679c9c-58d5-4ab6-9adf-a1c1d8f3996b
		summarizeBy: none
		sourceColumn: 'Product Container'

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		formatString: #,0.00
		lineageTag: a3c985c8-a484-40cc-8643-c56899252c1b
		summarizeBy: sum
		sourceColumn: 'Product Base Margin'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 95819938-34c2-461c-8bc7-85c0868bdba2
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Grouping Based on Unit Price'
		dataType: string
		lineageTag: ea23b599-5b26-433d-a8ed-0b4645f73a6e
		summarizeBy: none
		sourceColumn: 'Grouping Based on Unit Price'

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: b8cad16a-28a2-4fec-a3d8-8902d6693632
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Orders-87eac49b-4286-4f7d-bb0c-1f04a927d3a3' = m
		mode: import
		source =
				let
				    // Source Excel: Orders.xlsx
				    Source = Csv.Document(File.Contents(DataFolder & "\Extract.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", Int64.Type},
				        {"Order Date", type date},
				        {"Order Priority", type text},
				        {"Order Quantity", Int64.Type},
				        {"Sales", type number},
				        {"Discount", type number},
				        {"Ship Mode", type text},
				        {"Profit", type number},
				        {"Unit Price", type number},
				        {"Shipping Cost", type number},
				        {"Customer Name", type text},
				        {"City", type text},
				        {"Zip Code", type text},
				        {"State", type text},
				        {"Region", type text},
				        {"Customer Segment", type text},
				        {"Product Category", type text},
				        {"Product Sub-Category", type text},
				        {"Product Name", type text},
				        {"Product Container", type text},
				        {"Product Base Margin", type number},
				        {"Ship Date", type date}
				    }),
				    #"Added Grouping Based on Unit Price" = Table.AddColumn(#"Changed Types", "Grouping Based on Unit Price", each if [Unit Price] <= 2500 then "A" else if [Unit Price] <= 5000 then "B" else "C", type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Grouping Based on Unit Price", "Action (Region)", each Text.From([#"Region"]), type text),
				    Result = #"Added Action (Region)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 25 columns: Row ID, Order ID, Order Date, Order Priority, Order Quantity, Sales, Discount, Ship Mode, ... (25 columns total).

