table Calendar
	lineageTag: 27874c23-8400-4b11-b15b-29d2ed3dbfe8

	measure 'Year To Date' = TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 96d71415-1915-4b06-832e-e9f81eebd18c
		annotation Copilot_Description = DAX: TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c64a0783-0dbc-4a0d-807b-6531f1fd4f06
		annotation Copilot_Description = DAX: CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 7a88b736-7644-4262-8de6-32657b9ad1fe
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 72078864-36b1-48b7-899a-336ae4628571
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 2dc30394-cb35-4710-a52c-528707ec2ade
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0c452dd4-cf36-43f7-860b-76113908d09a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 401251ee-402a-4c0f-8309-35b4da1b49b2
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: be4fe7aa-6318-4cd4-9ee3-e482c0e63245
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 0eedc718-7e27-4103-9727-89451022a595
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: a0bb96d3-5de5-4a7a-b45a-8a4f8bfcde57
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d85a5e9d-a206-4b8b-8292-7fa8f441a9ee
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b05aa016-4599-4bfb-bdca-3575583bc9bb

		level Year
			ordinal: 0
			column: Year
			lineageTag: 687540cb-2770-428d-9743-e1bc3565129d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b2369ec2-8038-424d-9811-e6ea0f13da44

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 234a1245-9b52-48c3-8ea8-5018b66428a1

		level Day
			ordinal: 3
			column: Day
			lineageTag: dece8087-8307-4780-ba8c-4ddc08f39d07


	partition 'Calendar-89aa661b-b2a0-4c93-a349-2a715c6b95a4' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

