expression DataFolder = "C:\\Users\\pidoudet\\OneDrive - Microsoft\\Boulot\\PBI SME\\OracleToPostgre\\TableauToPowerBI\\artifacts\\real_world_output\\datasource_test\\Data" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression ServerName = "postgres91.test.tsi.lan:5432" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression DatabaseName = "TestV1" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]