// DAX measures for table: Calendar
// Auto-generated by Tableau → Power BI migration

Year To Date =
TOTALYTD([Budget Variance], 'Calendar'[Date])

Previous Year =
CALCULATE([Budget Variance], SAMEPERIODLASTYEAR('Calendar'[Date]))

Year Over Year % =
DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

