// DAX measures for table: Sheet1
// Auto-generated by Tableau → Power BI migration

p. Rebounds =
SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))

min(1) =
MINX('Sheet1', 1)

