table Calendar
	lineageTag: 616eff61-148b-4d62-8f42-cda907e73bbf

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e461efd1-eb6a-41d0-871f-7841f151b89e
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 5ef09849-54e8-4163-a3f3-a76222213fbb
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 7322b948-358f-4870-82c6-c8cb89d25113
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 12e62a54-ed27-4dca-bcf0-f022ab144637
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: a932e2a1-aa72-40b2-81d7-504b73021c4e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e9f10aca-f9b2-4ca6-a7f0-22821656df13
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2cbf9a97-2529-4139-9799-c1f3f33753cf
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 4f0b98e0-1e98-4fff-8fcd-a190e8b9874d
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9403631e-b335-4b52-8bb3-9dfe9c29f1d0

		level Year
			ordinal: 0
			column: Year
			lineageTag: 9a9acea7-14d5-4ab8-ab45-350c5e1aeb42

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 04cae4b2-f6f4-48b0-a19a-041433894b9c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 67f675b1-e0c9-4447-a0da-417cef3ad35d

		level Day
			ordinal: 3
			column: Day
			lineageTag: 0ee60b2b-9f36-4306-bcbc-0fc81b3c2189


	partition 'Calendar-ba7751c1-df5b-4f96-af9a-f7562303a00d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

