// DAX measures for table: Calendar
// Auto-generated by Tableau → Power BI migration

Year To Date =
TOTALYTD([GDP per capita (weighted)], 'Calendar'[Date])

Previous Year =
CALCULATE([GDP per capita (weighted)], SAMEPERIODLASTYEAR('Calendar'[Date]))

Year Over Year % =
DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

