table 'Select Indicator'
	lineageTag: d591506d-0324-4ff0-8299-60e99689ec2f

	measure 'Select Indicator' = SELECTEDVALUE('Select Indicator'[Value], "Avg Deal Size (won)")
		lineageTag: 9d1d3a81-00f9-47f0-828a-29e8cee3f50d
		annotation Copilot_Description = DAX: SELECTEDVALUE('Select Indicator'[Value], "Avg Deal Size (won)")

	column Value
		dataType: string
		lineageTag: 76b3fb49-520d-4837-9231-0733e5d3f82f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Select Indicator-870b2060-f5f0-4b01-a116-3df56574a360' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"Avg Deal Size (won)"}, {"Avg Opportunity Size"}, {"Avg Probability"}, {"Conversion Rate"}, {"Nb of Closed Opportunities"}, {"Nb of Lost Opportunities"}, {"Nb of Open Opportunities"}, {"Nb of Opportunities"}, {"Nb of Owners"}, {"Nb of Won Opportunities"}, {"Pipeline Generated"}, {"Pipeline Value"}, {"Sales Cycle"}, {"Sales Cycle (lost)"}, {"Sales Cycle (won)"}, {"Sales Velocity"}, {"Total Closed Opportunities Amount"}, {"Total Sales"}, {"Weighted Pipeline Value"}, {"Won/Lost Rate"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

