table xy
	lineageTag: ce467c8d-3fb8-40bc-8b6b-25f1f5583e7c

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: 69e6f3ec-aec6-44ee-bcd2-c7037098bb84
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	column a
		dataType: string
		lineageTag: d6ce98e3-8a22-4ac0-9bf9-b99e63ea92fc
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 6faa70ca-7884-4a6e-a554-693c71a1b1db
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: 1c62ad0d-3629-490b-892f-c23359d71471
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-9b845f83-94da-44cf-9447-e9adc4bc5476' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 1 measures: a, x, y.

