table Extract
	lineageTag: acbc7e41-ddc6-40d8-8095-f7d3cb774b17

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: fc2ab8e3-7326-4b1f-a819-14c935957810
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	column 'Number of Records'
		dataType: int64
		lineageTag: 418ed55a-092c-434d-bf89-9113d1f4558c
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column a
		dataType: string
		lineageTag: fdd9e320-b07d-45c0-8372-e0e6961748e7
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 597942a7-78ae-4fef-af68-44cd70a64003
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: e15e02df-fd80-424c-ad5c-3544e02616d0
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'Extract-afb4a341-2ffe-4f7c-afe5-d358b8301d2b' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("mssql2012.test.tsi.lan", "TestV1"),
				
				            _nav = _src{[Schema="dbo", Item="Extract"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Number of Records", "a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 4 columns and 1 measures: Number of Records, a, x, y.

