table Employees
	lineageTag: 6b34faae-ffcf-40ca-9639-91c0c47d8519

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f12ea66d-816c-4cdd-936d-224a27979f79
		annotation Copilot_Description = Migrated from Tableau: AVG([Salary]) | DAX: AVERAGE('Employees'[Salary])

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 88cbef66-06d2-41c3-a1a6-527f412736ab
		annotation Copilot_Description = Migrated from Tableau: COUNT([EmployeeID]) | DAX: COUNT('Employees'[EmployeeID])

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ed927b87-567a-45e2-bc5c-ab4793cd52a2
		annotation Copilot_Description = Migrated from Tableau: SUM([Salary]) * 1.25 | DAX: SUM('Employees'[Salary]) * 1.25

	column EmployeeID
		dataType: int64
		lineageTag: b1dbfd6d-f68f-44f9-ae0d-4f91df594eff
		summarizeBy: sum
		sourceColumn: EmployeeID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 7afd4377-3f3c-4e48-b7c1-2f4404829779
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: be423de2-05b2-4e5e-8825-bf8a351d6221
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 19c3a4f4-c94d-4f18-8886-1a17a885ebc2
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: f8511f09-a819-42e5-91b1-061fdc12c16c
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 2f087f60-ee58-4d1e-95da-5d1db6b4ca03
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: f377d1c7-95fc-448b-a0e4-86e5158b58e3
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: f0eb2891-497c-49e1-8238-427677715b75
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: 2ebf936e-0d83-4043-a9df-858697184c8a
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: 8fc81c30-b7a5-4c65-b9db-31c177fa7ba2
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: b54af086-3b81-476b-a4ff-09380a94aecd
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: ae824193-36a8-44e2-840b-c2396f4be425
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-01c5d143-73a8-4029-a152-6d14349f7959' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "HRDatabase"),
				
				            _nav = _src{[Schema="dbo", Item="Employees"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Added Tenure Category" = Table.AddColumn(_nav, "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns and 3 measures: EmployeeID, FirstName, LastName, HireDate, Department, JobTitle, Salary, Location, ... (12 columns total).

