table Calendar
	lineageTag: dd7829d9-100b-4f7e-9a33-5e15171f8aa7

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 481d1f97-4475-40a0-86a7-25c9d9608cbf
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: d9ef9e43-a549-4f86-9cf8-bcd69d09ffa1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e5ce197a-77a1-40c5-96b4-df9ff922130d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: b1de45f3-8104-4d2a-9279-0908d0c891de
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 37027a89-3629-4ddc-a0ce-bca7da98e951
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e164d2b8-806b-425b-acbe-6abe4a97141d
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 93096698-4189-4cde-8fa1-b6dfd4ae4f6c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c51a1edd-999d-42bf-a5b9-21e5348d805c
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6e7c1955-dc49-406a-92c8-cdf135d1ee1b

		level Year
			ordinal: 0
			column: Year
			lineageTag: ab7274c1-2711-436a-a64c-361dcba352bf

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ee33687e-ad72-4d9d-8d03-0c97be8e084e

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: d7087280-d93b-48a4-a2f2-31b74a76cfe4

		level Day
			ordinal: 3
			column: Day
			lineageTag: 86f8b899-ecc2-469c-964c-7152a3d7f701


	partition 'Calendar-bbb6d0e0-3ae4-4dd6-be22-58c5610649f3' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

