table 'Business Unit'
	lineageTag: 7d53431c-a398-496c-bd82-7fe8d3d7c047

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 419e4a61-10c7-4fdd-af63-e30d20fdab20
		annotation Copilot_Description = DAX: SELECTEDVALUE('Business Unit'[Value], "All")

	column Value
		dataType: string
		lineageTag: 1a6897ba-000b-45c8-85c2-ed546e3ad01b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-25bca943-43f3-4bc5-92f8-f5dfbe32204b' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

