table 'Fiscal Year'
	lineageTag: 4d0d0a62-5518-45a2-a017-4ea017b22a84

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: d838a136-20e3-48b8-8350-5db49df77731
		annotation Copilot_Description = DAX: SELECTEDVALUE('Fiscal Year'[Value], 2024)

	column Value
		dataType: int64
		lineageTag: 2cc1bfed-2b57-4d5b-829c-5b9801432548
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-1e262741-d794-4674-a684-90b00a684e5c' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

