table transactions
	lineageTag: 2090c934-ce45-403d-81d8-85a8eb7ba622

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7e09a644-d7f7-4c76-8076-f6ee60b2bcf3
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Revenue" THEN [amount] ELSE 0 END) | DAX: SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9f7e50c0-b707-4557-926e-5343719c1b67
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Expense" THEN [amount] ELSE 0 END) | DAX: SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 39b17e32-9559-4c9b-b1c8-c6238ddcd21b
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Revenue" THEN [amount] ELSE -[amount] END) | DAX: SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 67dff6ad-b162-4d0d-a0dc-9315174e2cd9
		annotation Copilot_Description = Migrated from Tableau: ([Revenue] - [Expenses]) / [Revenue] | DAX: ([Revenue] - [Expenses]) / [Revenue]

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 5e6ed69e-2aa9-4a9f-8fee-81377de91e6d
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF YEAR([transaction_date]) = YEAR(TODAY()) THEN [amount] ELSE 0 END)} | DAX: CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: af115a5e-e56e-45de-a6cf-69d05d375fad
		annotation Copilot_Description = Migrated from Tableau: SUM([amount]) - WINDOW_AVG(SUM([amount])) | DAX: SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))

	measure 'Revenue Formatted' = VAR _val = [Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 63a9145a-ed60-4168-8c5b-8445a4bcc2e2
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue (K/M/B)

	measure 'Expenses Formatted' = VAR _val = [Expenses] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: c98326a7-f48e-4ee3-823d-0a635b97cf97
		annotation Copilot_Description = Dynamic numeric abbreviation for Expenses (K/M/B)

	measure 'Net Income Formatted' = VAR _val = [Net Income] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: e94fc6f5-7e0d-4118-bbde-fb43f2c75507
		annotation Copilot_Description = Dynamic numeric abbreviation for Net Income (K/M/B)

	measure 'YTD Revenue Formatted' = VAR _val = [YTD Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 26d91979-e965-453d-9b63-b838374765c9
		annotation Copilot_Description = Dynamic numeric abbreviation for YTD Revenue (K/M/B)

	measure 'Budget Variance Formatted' = VAR _val = [Budget Variance] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 472b3b6b-8634-4164-a49e-0011b6adfef8
		annotation Copilot_Description = Dynamic numeric abbreviation for Budget Variance (K/M/B)

	column transaction_id
		dataType: int64
		lineageTag: 86dd484c-e87f-4cd3-a609-673b128e14b4
		summarizeBy: sum
		sourceColumn: transaction_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1a72c575-4b9c-4aee-bc61-70d6c9de238f
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: 254ef741-82a5-4f34-8fe0-e2175d848559
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: f4aaf56b-3d64-4962-9d2a-6a49fe31b20f
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: c05ecf5d-6f09-441b-aac8-07fe5d0bc57b
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 9be1ada6-cdcd-449b-8cc7-b61377529d51
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 89e59bad-4b33-4ff1-8dd8-507e8b7e3fd0
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: 7819a278-1fd8-4069-a44b-215b4b1de935
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-de3e16c3-67a4-416f-86d4-afc2d3233c25' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.company.com:5432", "finance"),
				
				            _nav = _src{[Schema="public", Item="transactions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"transaction_id", "transaction_date", "account", "category", "amount", "type", "business_unit", "cost_center"}, {}),
				    Result = Source
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns and 11 measures: transaction_id, transaction_date, account, category, amount, type, business_unit, cost_center.

