table Calendar
	lineageTag: a7e205b1-8a17-4ebf-9c6c-9cbfa8326bcf

	measure 'Year To Date' = TOTALYTD([Total Sales], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: b3fd4da6-4cb9-4099-bf08-c61500db88f0
		annotation Copilot_Description = DAX: TOTALYTD([Total Sales], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 0cc02bc7-138b-44c6-b153-fdd16ce011c6
		annotation Copilot_Description = DAX: CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: cf0bb223-ff8a-448b-839c-7982b1d50bad
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 089a84ab-85f7-4187-a3aa-c65828dcb5c5
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c88f3959-d6f3-4d39-a068-1634e5c02ec1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: d3cd6f85-ae5b-42fe-a0f3-dc6aaccc95e0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 0e375d68-9690-4052-9168-292dc95f718f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d0b5317a-492d-419d-a14e-5ba44e2d2faa
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: b115ceae-7db1-461b-b19f-3d417616f3c2
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 709d717f-8440-4792-95ac-298d74f1663c
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f8f9f3c3-ed6f-41ee-856a-5ac2ba0a69f5
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 78b90f62-df15-410f-99ed-aa33ea744157

		level Year
			ordinal: 0
			column: Year
			lineageTag: f3baefc1-9664-4634-b4c9-1386bd33f107

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 4a94068e-4017-499e-ab01-f230cc673f15

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 008cd40b-c295-43a7-9790-95052e187a56

		level Day
			ordinal: 3
			column: Day
			lineageTag: 61c25960-9861-4459-adb7-4ccd39b6b69d


	partition 'Calendar-02b05bfa-6bee-43b0-8c26-8880c8594f0f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

