table Returns
	lineageTag: 97d8abb7-381c-406e-988c-8ede9c3df81b

	column Returned
		dataType: string
		lineageTag: 531ff9ef-0922-4dfa-9485-d1912063cc04
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 622f72fb-ffa8-47e1-998f-2cf9ca6b9115
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	partition 'Returns-75c9ec4a-76c3-40c3-86c9-9e9286a7e272' = m
		mode: import
		source =
				let
				    // Source Excel: Sample - Superstore.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Returns",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Returned", "Order ID"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Returned", type text},
				        {"Order ID", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Returned, Order ID.

