// DAX measures for table: sessions
// Auto-generated by Tableau → Power BI migration

Total Sessions =
COUNT('sessions'[session_id])

Unique Visitors =
DISTINCTCOUNT('sessions'[user_id])

Conversion Rate =
SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])

Avg Session Duration =
AVERAGE('sessions'[session_duration])

Total Revenue =
SUM('sessions'[revenue])

Revenue per Session =
SUM('sessions'[revenue]) / COUNT('sessions'[session_id])

Revenue by Channel =
CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))

