table Extract
	lineageTag: e74d944c-185f-42d1-bdb1-be13c3212bca

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2dd9b13a-b823-4a23-b69a-db7e136696d0
		annotation Copilot_Description = Migrated from Tableau: AVG([F: GDP per capita (curr $)]) / TOTAL(AVG([F: GDP per capita (curr $)])) | DAX: AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7a5cf6b0-e022-49fd-8a1c-98bba83c54de
		annotation Copilot_Description = Migrated from Tableau: SUM([F: GDP (curr $)]) / SUM([P: Population (count)]) | DAX: SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9f20a5dd-a0f0-442e-ab9a-d5523776ecce
		annotation Copilot_Description = Migrated from Tableau: AVG([F: Lending interest rate (%)])-AVG([F: Deposit interest rate (%)]) | DAX: AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])

	measure 'GDP per capita (weighted) Formatted' = VAR _val = [GDP per capita (weighted)] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 07663105-92dd-4140-8efa-62da4884466c
		annotation Copilot_Description = Dynamic numeric abbreviation for GDP per capita (weighted) (K/M/B)

	column 'Country / Region'
		dataType: string
		lineageTag: aecd3119-adb7-4d8c-9be1-0670d61d6a9f
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: f687a967-3925-4e91-8218-26ec36d4ac6e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 523aeaa2-94c0-4e93-91d0-d895e03d9010
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 8278dad6-90b1-4bb1-8487-e3589da94772
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: e82c7d6d-c290-46e4-8b92-129ddc8c013a
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: b97465c2-fcb6-4ca9-a039-de58fe252502
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: b6b760ab-5091-4b6e-95b7-0488162efffa
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: 28430be4-8c54-428a-9ded-ea2d85623a1f
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: 990ebfe1-428f-4d94-9863-53270a07d9b8
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 17cf1a08-3140-44cc-892f-787832a400c7
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: 96ead797-be81-4d18-b40f-76405ed4c0eb
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a210074e-a5b8-42c5-bc9a-52268d7ccc27
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: 0921f0ce-d124-44df-a2f2-0ceace18640e
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)'
		dataType: string
		lineageTag: bc4cc3cc-87c9-4e2b-ab81-e185461bcea5
		summarizeBy: none
		sourceColumn: 'Action (Country Name)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))'
		dataType: string
		lineageTag: 857a6c67-d0f7-42c9-8864-70188c720d11
		summarizeBy: none
		sourceColumn: 'Action (Date (year))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: de027d7e-3880-4955-808f-1e15754dee02
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))'
		dataType: string
		lineageTag: dc53af94-be75-4d0c-a034-fa28ceae12ca
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))'
		dataType: string
		lineageTag: c2485054-5498-4488-b4b3-e99accf5af51
		summarizeBy: none
		sourceColumn: 'Exclusions (Country Name,YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-7797f85f-0ec1-4d9f-8f71-e8a7bff94251' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"},
				            {
				                {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"},
				                {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Sample 13", "Sample 14"}
				            }
				        )
				    otherwise
				        #table({"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    #"Added Action (Country Name)" = Table.AddColumn(#"Renamed Columns", "Action (Country Name)", each Text.From([#"Country / Region"]), type text),
				    #"Added Action (Date (year))" = Table.AddColumn(#"Added Action (Country Name)", "Action (Date (year))", each Text.From([#"Date"]), type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Action (Date (year))", "Action (Region)", each Text.From([#"Region"]), type text),
				    #"Added Action (YEAR(Date (year)))" = Table.AddColumn(#"Added Action (Region)", "Action (YEAR(Date (year)))", each Text.From(Date.Year([#"Date"])), type text),
				    #"Added Exclusions (Country Name,YEAR(Date (year)))" = Table.AddColumn(#"Added Action (YEAR(Date (year)))", "Exclusions (Country Name,YEAR(Date (year)))", each Text.From([#"Country / Region"]) & " | " & Text.From(Date.Year([#"Date"])), type text),
				    Result = #"Added Exclusions (Country Name,YEAR(Date (year)))"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 18 columns and 4 measures: Country / Region, Date, F: Deposit interest rate (%), F: GDP (curr $), F: GDP per capita (curr $), F: Lending interest rate (%), H: Health exp (% GDP), H: Health exp/cap (curr $), ... (18 columns total).

