table 'Base Salary'
	lineageTag: 58b29df0-f961-4919-8697-d8e0c5363755

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: da8b568e-9ec1-4636-abbc-8eaabfb93735
		annotation Copilot_Description = DAX: SELECTEDVALUE('Base Salary'[Value], 50000)

	column Value
		dataType: int64
		lineageTag: a0798ea4-e0ac-49be-903d-ec273202fcec
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-00e81b2e-e73e-46ae-b30a-bdadaaca01bb' = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

