table Calendar
	lineageTag: a7a4e8fa-f3e9-49f7-9d94-2483e7295470

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3995f38e-a6fe-462f-8929-c01c040b0496
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 24080747-3051-42d5-973a-4530e7f75113
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 5975dcee-d20f-4470-b161-9b7f70ae5ca0
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 06fc3c64-dbff-4477-9af7-f26acf855077
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 86f80336-b2f6-405f-9799-6175b2ba80ec
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 51151739-ea6a-4073-87d8-06993b68dae9
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 728a4f4c-c5c6-4edc-a5da-36bc0846b6ad
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7fd3482f-95c6-4ef3-affd-0b8bcf92e325
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 57b45734-e78a-4fd6-ada0-426dee38b95d

		level Year
			ordinal: 0
			column: Year
			lineageTag: 162f398a-5aff-44a7-80b8-696c41ffa621

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 0156e29b-507b-4725-8493-1406384402a4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6ef33f90-6585-4999-8418-22dce0148a18

		level Day
			ordinal: 3
			column: Day
			lineageTag: a4683c15-9e6b-4075-8c11-f7fa62b98aee


	partition 'Calendar-21eb9d19-9fb1-44ec-a0d2-66555c9e704f' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

