table 'Churn Rate'
	lineageTag: 74420937-9d7f-4ec6-b7e4-b4ffc283a665

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: fd94d6a4-f480-4449-8f01-a17f95f54fdb
		annotation Copilot_Description = DAX: SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)

	column Value
		dataType: double
		lineageTag: 254adef3-361f-4e3e-8da1-ca0db9452b81
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-69f0144e-8335-468a-9973-fff88833de53' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

