table 'Commission Rate'
	lineageTag: 323b0eb8-fce0-40f4-8a57-473329be7208

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: a648ef22-6e7d-4eef-8db3-63062e508894
		annotation Copilot_Description = DAX: SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)

	column Value
		dataType: double
		lineageTag: 6a4d5315-b02b-454e-b764-0dcc7a4385fa
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-fb123472-a9a5-4ee6-912f-2a157682d184' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

