table Extract
	lineageTag: ad2154be-e153-45ec-9020-b84ae6889824

	measure 'Number of Records' = COUNTROWS('Extract')
		displayFolder: Measures
		lineageTag: be02626a-7a11-40b7-afd7-0cd03b05d05e
		annotation Copilot_Description = DAX: COUNTROWS('Extract')

	column Category
		dataType: string
		lineageTag: 98e149bf-57c8-4d1a-ab72-5785c17d58db
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 8f5f074b-9e1c-4d05-a494-41b08e6bd3da
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: e3cd017c-a781-4b5c-a81d-0c847d3e7166
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Sales Target'
		dataType: int64
		formatString: c"$"#,#0;("$"#,#0)
		lineageTag: 2b84bd07-e1da-4fce-b41b-cdb6129a60af
		summarizeBy: sum
		sourceColumn: 'Sales Target'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: a75afbb8-80b6-4879-99cb-b3f4c98863a1
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition 'Extract-cf935411-b5fd-42a3-89f1-124c983eaf1c' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Category", "Number of Records", "Order Date", "Sales Target", "Segment"},
				            {
				                {"Sample 1", 2, 3, 4, "Sample 5"},
				                {"Sample 2", 3, 4, 5, "Sample 6"}
				            }
				        )
				    otherwise
				        #table({"Category", "Number of Records", "Order Date", "Sales Target", "Segment"}, {})  // Empty table on error
				in
				    Source

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 5 columns and 1 measures: Category, Number of Records, Order Date, Sales Target, Segment.

