table 'New Quota'
	lineageTag: de6561a6-5a80-468c-bf20-529b39203212

	measure 'New Quota' = SELECTEDVALUE('New Quota'[Value], 500000)
		lineageTag: cd7240f3-6216-49fd-9e70-71f653679387
		annotation Copilot_Description = DAX: SELECTEDVALUE('New Quota'[Value], 500000)

	column Value
		dataType: int64
		lineageTag: 60e43305-729f-4683-b614-6991a9cc6b21
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'New Quota-90a060f4-11d7-44fd-aeca-41ff10903467' = calculated
		mode: import
		source = GENERATESERIES(100000, 100, 25000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

