table 'New Business Growth'
	lineageTag: 546dff48-f03e-4019-939e-2cc98fa750d9

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: b39f777d-d632-4fe9-83ce-7ead5383609d
		annotation Copilot_Description = DAX: SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)

	column Value
		dataType: double
		lineageTag: c87b36d5-4975-472d-86c5-f6036b4aa95f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-b29edf45-bf41-4e82-811b-148e066c354f' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

