table xy
	lineageTag: 9b52daa9-17ea-4658-b94e-0d8a3a8accae

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: 2d1bdbed-2835-4557-9070-c8ff007853c2
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	column a
		dataType: string
		lineageTag: 749cfa4c-2397-42e9-b41e-5faf40035113
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column 'Today''s Date'
		dataType: string
		lineageTag: 9e8126b3-28a7-461e-bb7a-e611ab3fd09f
		summarizeBy: none
		sourceColumn: 'Today''s Date'

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 65d63c52-0875-4ef5-b6da-31b88e64d8ac
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: eb1112bd-7135-4275-86ad-7bfacd8de7cf
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-039dd7b3-1b9c-4f3a-be60-c9f3a37610a2' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "Today's Date", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 4 columns and 1 measures: a, Today's Date, x, y.

