# ══════════════════════════════════════════════════════════════
# RLS Role Assignment Script — Security_Test
# Generated by Tableau-to-Power-BI Migration Tool
# ══════════════════════════════════════════════════════════════
#
# Prerequisites:
#   Install-Module -Name MicrosoftPowerBIMgmt -Scope CurrentUser
#   Connect-PowerBIServiceAccount
#
# Usage:
#   1. Update $WorkspaceId and $DatasetId below
#   2. Update the email addresses for each role
#   3. Run: .\assign_rls_roles.ps1
# ══════════════════════════════════════════════════════════════

# --- Configuration ---
$WorkspaceId = "YOUR_WORKSPACE_ID"   # Replace with your workspace GUID
$DatasetId   = "YOUR_DATASET_ID"     # Replace with your dataset GUID

# Connect to Power BI Service (interactive login)
Connect-PowerBIServiceAccount

# ── Role: Region Access ──
$Role_Region_Access_Members = @(
    "user@yourdomain.com"     # TODO: Add Azure AD members
)

foreach ($member in $Role_Region_Access_Members) {
    try {
        $body = @{ emailAddress = $member } | ConvertTo-Json
        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"
        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
        Write-Host "  Added $member to role Region Access" -ForegroundColor Green
    } catch {
        Write-Host "  Failed to add $member to role Region Access: $_" -ForegroundColor Red
    }
}

# ── Role: Is Current User ──
$Role_Is_Current_User_Members = @(
    "user@yourdomain.com"     # TODO: Add Azure AD members
)

foreach ($member in $Role_Is_Current_User_Members) {
    try {
        $body = @{ emailAddress = $member } | ConvertTo-Json
        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"
        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
        Write-Host "  Added $member to role Is Current User" -ForegroundColor Green
    } catch {
        Write-Host "  Failed to add $member to role Is Current User: $_" -ForegroundColor Red
    }
}

# ── Role: Manager Access ──
$Role_Manager_Access_Members = @(
    "user@yourdomain.com"     # TODO: Add Azure AD members
)

foreach ($member in $Role_Manager_Access_Members) {
    try {
        $body = @{ emailAddress = $member } | ConvertTo-Json
        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"
        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
        Write-Host "  Added $member to role Manager Access" -ForegroundColor Green
    } catch {
        Write-Host "  Failed to add $member to role Manager Access: $_" -ForegroundColor Red
    }
}

# ── Role: Region Match ──
$Role_Region_Match_Members = @(
    "user@yourdomain.com"     # TODO: Add Azure AD members
)

foreach ($member in $Role_Region_Match_Members) {
    try {
        $body = @{ emailAddress = $member } | ConvertTo-Json
        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"
        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
        Write-Host "  Added $member to role Region Match" -ForegroundColor Green
    } catch {
        Write-Host "  Failed to add $member to role Region Match: $_" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "RLS role assignment complete." -ForegroundColor Cyan
