table Calendar
	lineageTag: 9f4d0900-8de7-40a8-89fe-0d982c8d3c6e

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3542f666-b672-4130-a1d2-b5378e649379
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: bba06df1-ecb9-4b1b-9bdd-c179d6218974
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 495b952f-ec82-469a-be90-8149de310770
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 412c35e0-7aea-49ba-af16-592c0b1c2dbf
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f00c300e-1ae7-4863-9e86-06fb27ff213c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 93dd8f63-c8ae-427e-8f09-45f41bde3600
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2ad51202-0d87-4dda-b601-cf04ab7b1c6e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b6437479-3dec-4cf3-b992-6f1a8156d406
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fed9cabc-f4b1-44a6-bebc-43d92088cf70

		level Year
			ordinal: 0
			column: Year
			lineageTag: e54aedac-3ac2-4460-b3bc-c5c8f37125e4

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: a4c987f5-204d-4626-8569-f9438984b94d

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4ceab22c-c870-4904-9a0e-bfdd6c0ce948

		level Day
			ordinal: 3
			column: Day
			lineageTag: b311c18a-6ee4-4f84-b453-02c50c7bf48f


	partition 'Calendar-ad8726a0-fd59-46a5-b384-0c6f4dcef454' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

