table 'customer_feedback_data.json'
	lineageTag: fbcc123b-3612-4311-ac21-67fb44d934ad

	column 'Document Index (generated)'
		dataType: int64
		lineageTag: 47ffcb6a-f320-45d4-835a-b6cf3ac2b726
		summarizeBy: sum
		sourceColumn: 'Document Index (generated)'

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 2b565067-5a68-4e66-a3ca-4824363127d3
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 74e3a30f-e1da-49e0-bdeb-98ed17aa5cad
		summarizeBy: none
		sourceColumn: customer_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: c10e9a75-163c-417d-8275-a259f64664db
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 485a65b7-72ac-42d2-8667-fa7185a3b299
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column feedback_score
		dataType: double
		formatString: #,0.00
		lineageTag: eba6dfa3-12b6-4c2c-aa00-b5075592e41c
		summarizeBy: sum
		sourceColumn: feedback_score

		annotation SummarizationSetBy = Automatic

	column feedback_text
		dataType: string
		lineageTag: 1297b30e-7db3-4d12-abef-ebca11d4bc91
		summarizeBy: none
		sourceColumn: feedback_text

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b6736234-514d-494e-aa6f-96787c114c4f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: 1b298a08-2217-40d6-8b91-90a380c6df7b
		summarizeBy: none
		sourceColumn: sentiment

		annotation SummarizationSetBy = Automatic

	column Promoter
		dataType: int64
		lineageTag: 941fc52f-c4c4-4f1d-a58f-caa5a97df7fd
		summarizeBy: none
		sourceColumn: Promoter

		annotation SummarizationSetBy = Automatic

	column 'Action (Category)'
		dataType: string
		lineageTag: 349b73ba-685f-4100-af6b-372d2b133256
		summarizeBy: none
		sourceColumn: 'Action (Category)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Sentiment)'
		dataType: string
		lineageTag: c2e784f7-1f52-458a-af37-d3c57a985d9d
		summarizeBy: none
		sourceColumn: 'Action (Sentiment)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'customer_feedback_data.json-18c79a9d-3d3d-46b1-81b9-66f23a5df086' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: SEMISTRUCTPASSIVESTORE-DIRECT
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"},
				            {
				                {1, "Sample 2", "Sample 3", 4, "Sample 5", 6, "Sample 7", "Sample 8", "Sample 9"},
				                {2, "Sample 3", "Sample 4", 5, "Sample 6", 7, "Sample 8", "Sample 9", "Sample 10"}
				            }
				        )
				    otherwise
				        #table({"Document Index (generated)", "category", "customer_id", "date", "email", "feedback_score", "feedback_text", "name", "sentiment"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"category", "Category"}, {"customer_id", "Customer Id"}, {"date", "Date"}, {"email", "Email"}, {"feedback_score", "Feedback Score"}, {"feedback_text", "Feedback Text"}, {"name", "Name"}, {"sentiment", "Sentiment"}}),
				    #"Added Promoter" = Table.AddColumn(#"Renamed Columns", "Promoter", each if [feedback_score] >= 9 then 1 else 0, Int64.Type),
				    #"Added Action (Category)" = Table.AddColumn(#"Added Promoter", "Action (Category)", each Text.From([#"category"]), type text),
				    #"Added Action (Sentiment)" = Table.AddColumn(#"Added Action (Category)", "Action (Sentiment)", each Text.From([#"sentiment"]), type text),
				    Result = #"Added Action (Sentiment)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: Document Index (generated), category, customer_id, date, email, feedback_score, feedback_text, name, ... (12 columns total).

