table Calendar
	lineageTag: d61f7e05-4468-46cd-aea7-bb96c9a33476

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0b97cd55-88fd-4fbf-8f13-9a02b32a5036
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 98bcd783-0f7a-4ef2-83d0-6f0724a4241c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0dabdbab-74f6-44ec-90bf-508a47559ba9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 885f3e2a-8dc4-4465-8de5-857c42543cb9
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f5fc6c3c-ca60-4cd3-9eb1-2bb59e814ca4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: d8f57fd6-1e2e-4118-96de-ec20ecbf93a0
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4b6d02f4-71d7-4170-9251-d95d23f1b397
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f92305ee-1f6c-4343-b525-482866c30914
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 9be389bc-3890-4268-96dd-a7c33bde8518

		level Year
			ordinal: 0
			column: Year
			lineageTag: 51a32227-b8d9-4565-9de2-208f8a45da98

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 7c55771e-535f-4dac-ae8e-2513959bd8d4

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0bc6d9f7-89be-493e-be75-bd8d348ba8a1

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5b44d6ea-4004-4499-bd3d-7c81afa1c53b


	partition 'Calendar-98e614ea-f853-4da2-b5f3-746a493bf1eb' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

