table pPlaceholder
	lineageTag: 10c54c6b-58c3-4551-b665-66aa4e4e3099

	measure pPlaceholder = SELECTEDVALUE('pPlaceholder'[Value], 0)
		lineageTag: 9a76c1dd-f43e-453d-a0ea-43ee10ceffd5
		annotation Copilot_Description = DAX: SELECTEDVALUE('pPlaceholder'[Value], 0)

	column Value
		dataType: int64
		lineageTag: 29b332ae-8d0e-4e50-b934-cf59831d26ef
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'pPlaceholder-37dd5f3e-0e79-4a86-b151-aafa11706bf7' = calculated
		mode: import
		source = DATATABLE("Value", INTEGER, {{0}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

