table 'Business Unit'
	lineageTag: 461c38a5-6a49-4340-bed7-7bdc0dc3431c

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: 41766103-4985-4f78-8005-22e471a7c70f
		annotation Copilot_Description = DAX: SELECTEDVALUE('Business Unit'[Value], "All")

	column Value
		dataType: string
		lineageTag: 8de48faf-3e1d-4960-a455-f145622202b9
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-560e7bfe-ee09-4d22-949c-a9cbb4dc6272' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

