table 'Fiscal Year'
	lineageTag: c5e26fbc-30a5-4a9f-a984-b5843cadf210

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: 9bc06e17-e386-4e72-9bd8-55e37fce0f32
		annotation Copilot_Description = DAX: SELECTEDVALUE('Fiscal Year'[Value], 2024)

	column Value
		dataType: int64
		lineageTag: a8dcdb35-6af6-4cfe-b85b-21a976a9cab2
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-d964483d-1c02-456c-b81d-ae1c886ba8e3' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

