table transactions
	lineageTag: 9a355a1b-46a4-49be-b0de-2dd9c52ffb84

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d60c5c57-b080-49ae-83e8-6114d096eced
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Revenue" THEN [amount] ELSE 0 END) | DAX: SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7215bed8-2359-436f-b923-ad192902c43a
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Expense" THEN [amount] ELSE 0 END) | DAX: SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 45f36c65-7861-402d-8742-d9236818cdda
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Revenue" THEN [amount] ELSE -[amount] END) | DAX: SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 96b4f009-07ed-4a0a-aaa2-c16dead8cf57
		annotation Copilot_Description = Migrated from Tableau: ([Revenue] - [Expenses]) / [Revenue] | DAX: ([Revenue] - [Expenses]) / [Revenue]

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 469196d1-293b-4e6d-a629-98d3be7e8d2b
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF YEAR([transaction_date]) = YEAR(TODAY()) THEN [amount] ELSE 0 END)} | DAX: CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1379cdd0-ea33-4cdd-b09c-b30f0ef74ddd
		annotation Copilot_Description = Migrated from Tableau: SUM([amount]) - WINDOW_AVG(SUM([amount])) | DAX: SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))

	column transaction_id
		dataType: int64
		lineageTag: 94abc741-d8c7-43c7-84fe-142eb27e04ec
		summarizeBy: sum
		sourceColumn: transaction_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f26eb842-45dc-441f-8823-ea3c9d85a7a4
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: d0cf55e5-b947-4416-b9bb-5f584b3aed9f
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 4a6c1d22-423f-483c-b4ae-0638218a4037
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 1c9b17f4-7e40-49af-a02b-d0ec6a5aa9c4
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: aa269ca8-e524-4442-b3cc-14bf1e77e9d0
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 3e0c97fe-0b7d-4a3f-bbe6-5af1fff532ba
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: b1988179-88ab-458d-aeb3-a86448c8fa0b
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-b150e5e0-d171-45ca-97c0-e2bcd48f8eb4' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.company.com:5432", "finance"),
				
				            _nav = _src{[Schema="public", Item="transactions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"transaction_id", "transaction_date", "account", "category", "amount", "type", "business_unit", "cost_center"}, {}),
				    Result = Source
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns and 6 measures: transaction_id, transaction_date, account, category, amount, type, business_unit, cost_center.

