table 'Alert Threshold'
	lineageTag: 30c75f16-567d-44c5-82e4-9d27632a9d8a

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: cea272cd-a93d-419c-bda5-afc89ee1d430
		annotation Copilot_Description = DAX: SELECTEDVALUE('Alert Threshold'[Value], 100)

	column Value
		dataType: double
		lineageTag: 1853cef4-431b-4150-8703-fa08ec3501f9
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-888df31a-adcf-44e6-b634-3ea3a5a923bd' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

