table Calendar
	lineageTag: 1b279a9a-4059-47a6-a1de-bf1b9eacce27

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2747e07a-e1d4-47b9-a80f-7ee662004709
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 9bd50f8e-0297-4148-92ce-f2452bfb109c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ba833209-fe03-4f14-a8fd-06a72fdda3ef
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: cb727ed6-8f51-4365-afed-c4271a0d4267
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2db0c3fb-0fcf-4033-b573-4e353fee5156
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 2779a228-c37b-4afd-b931-e1a13b1a8f11
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 4aa65880-dfc4-4e7e-b56d-215b11cb4d1d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7dcbf25b-f89a-4795-a83b-0b4e04818275
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 541786b9-adae-4cb4-bb4f-081d40dbe0f7

		level Year
			ordinal: 0
			column: Year
			lineageTag: 67d75dfd-ffc3-4fc6-9097-0116c2883087

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b645f804-1881-4b3d-aeaa-a0e44cf35923

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 0891a376-1093-409c-84e6-c4e8fa2e5c3f

		level Day
			ordinal: 3
			column: Day
			lineageTag: b084a954-8392-41bd-99e9-0eebbb0a8d5d


	partition 'Calendar-6feefa6e-f490-4e05-bc3b-6c93fcd92893' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

