table Machines
	lineageTag: cc0ba634-c5c5-428f-97da-666e4a4c9be8

	column machine_id
		dataType: int64
		lineageTag: 76bc4466-9592-4787-88e2-d75b39b05ddb
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: d77bb5e5-fe42-4275-aa13-82368bc81389
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: 76c1e2e3-d64b-4abb-b315-97638de98079
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 351fda30-7f26-4ba6-85a4-e7ea8c0b3b7f
		summarizeBy: none
		sourceColumn: install_date

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: ade864b3-0d8e-423e-bc84-70cec10f4641
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: d8b0df2e-e836-4de8-9613-1ca9afe7618d
		summarizeBy: none
		sourceColumn: line_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: 2d9e8076-c792-4f53-82c0-02cc5e685e71
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-b0916756-e8ad-4146-b21d-2d115fc7fb69' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Machines"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"machine_id", "machine_name", "machine_type", "install_date", "location", "line_id", "rated_capacity"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: machine_id, machine_name, machine_type, install_date, location, line_id, rated_capacity.

