table Maintenance
	lineageTag: 026d8e6d-28f3-49ba-8b4c-ea2e6aba250f

	column maint_id
		dataType: int64
		lineageTag: 3b1ca644-cec9-4045-b425-d9d495dc31c8
		summarizeBy: sum
		sourceColumn: maint_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 16196a19-78d6-4266-9609-b2d1475f31c6
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ae610e01-693a-48c9-96f3-75385e948b0f
		summarizeBy: none
		sourceColumn: maint_date

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: d54baf89-97c7-475c-83da-1ee2bfaeb593
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 194c2206-a80d-4415-b62a-84e7731ffd08
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 01a6bcd5-6ed0-44ae-937e-0d8a0f64b1b1
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: cd8662ee-4a9f-4808-aabb-d076cf49f29f
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 6231ca91-4273-4b94-a8df-13e38d36a440
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-96aaa1a6-7c11-46ac-a652-4925cff58903' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

