table Sensors
	lineageTag: 42476f03-fadb-4d9b-acbf-ab7f0c2cbd3a

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 38ddec50-4100-4538-8423-381a03b4f7c9
		annotation Copilot_Description = Migrated from Tableau: MEDIAN([value]) | DAX: MEDIAN('Sensors'[value])

	measure 'P95 Value' = PERCENTILE.INC(MAX('Sensors'[value]), 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8420893a-9bdf-4580-8668-598e3ff8b287
		annotation Copilot_Description = Migrated from Tableau: PERCENTILE([value], 0.95) | DAX: PERCENTILE.INC(MAX('Sensors'[value]), 0.95)

	measure 'Value Variance' = VAR.S(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d9054c68-b4e7-4d07-af77-3e2ab22eb05d
		annotation Copilot_Description = Migrated from Tableau: VAR([value]) | DAX: VAR.S(MAX('Sensors'[value]))

	measure 'Value Variance Pop' = VAR.P(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 688ca713-6503-4494-bc2e-30263d48f56e
		annotation Copilot_Description = Migrated from Tableau: VARP([value]) | DAX: VAR.P(MAX('Sensors'[value]))

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b3fccc76-4c65-4cc2-a6b7-92750b5a9451
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [sensor_type], [machine_id] : AVG([value])} | DAX: CALCULATE(AVERAGE('Sensors'[value]))

	measure 'Running Avg Value' = /* TODO: DAX conversion validation failed for Calc_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 08aba30b-11fe-40e6-a8e0-5c7b99d19bb5
		annotation Copilot_Description = Migrated from Tableau: RUNNING_AVG(AVG([value])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Count' = /* TODO: DAX conversion validation failed for Calc_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: f5f52c0a-0b66-496d-b723-6c24b01b1b1f
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(COUNT([reading_id])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Max Value' = /* TODO: DAX conversion validation failed for Calc_RunMax: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7aae4b27-07b3-43e9-a826-93e957511f80
		annotation Copilot_Description = Migrated from Tableau: RUNNING_MAX(MAX([value])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunMax: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Min Value' = /* TODO: DAX conversion validation failed for Calc_RunMin: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: cb8dcc20-ee4f-49c1-867e-164e002c92f1
		annotation Copilot_Description = Migrated from Tableau: RUNNING_MIN(MIN([value])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunMin: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: 79dc164c-6964-4c41-9049-9adea853e9b1
		annotation Copilot_Description = Migrated from Tableau: RANK_DENSE(SUM([value])) | DAX: RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: 7966d3b3-b769-4a70-9187-940edfbcbf92
		annotation Copilot_Description = Migrated from Tableau: RANK_UNIQUE(AVG([value])) | DAX: RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ca250093-f7e7-4689-92ac-36ad9bdb03ab
		annotation Copilot_Description = Migrated from Tableau: WINDOW_SUM(SUM([value])) | DAX: CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))

	measure 'Time Granularity' = "Hour"
		lineageTag: 1b8c5f3f-d48c-47c3-b4ee-2c61fda24fe1
		annotation Copilot_Description = DAX: "Hour"

	column reading_id
		dataType: int64
		lineageTag: da70c916-8480-4cc3-b39a-282627561478
		summarizeBy: sum
		sourceColumn: reading_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 78944844-617a-401e-93d9-59982491a564
		summarizeBy: none
		sourceColumn: reading_time

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 0a09d390-1394-4dbe-8446-e74d97676472
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: 376ac800-5cd5-4d7f-aeab-aae364d25c6a
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 040da15c-d0f3-4e5d-b5aa-234b4f1a47f0
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 6ed46b9b-5070-483f-8761-57ce35934ca0
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: 01c6b4f3-8838-4106-9d7c-8b1d516dc04f
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: aa8ee4f9-a5a0-4335-a5a3-c8874a25c234
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 5f921e67-9c6f-4d1c-a0f2-5cd05146699f
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: d810ce61-3ea1-44ec-bf37-fc100eeef278
		summarizeBy: none
		sourceColumn: plant_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: b4b6d2b4-1b9b-4be6-9586-cd69ddf41d21
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 403d5647-e724-4bb8-9bcf-11819e6ca3ed
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: a2235a8d-6dc9-46da-9daf-0f7c047e52bb
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 75651f70-d784-4370-9155-facc95ca5485
		summarizeBy: none
		sourceColumn: 'Abs Deviation'

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: d1f0cd92-73e8-4724-b4f4-b55b155f3461
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 957a4426-2591-4e7b-8374-2964afcd7473
		summarizeBy: none
		sourceColumn: 'Floor Value'

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 63ebb556-a0db-4184-9795-0d83ae57dc7a
		summarizeBy: none
		sourceColumn: 'Rounded Value'

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: 1e81beb2-ba9e-480b-9847-48513de8761e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 6a2c14c9-7ce4-4f16-b64c-5875684edf77
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 7256228c-5db2-49fa-a0d1-f682544900ac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 8f1dcb59-9890-41cf-a7ca-b364d9b3f57d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 02be5ba4-bd1d-422c-ac03-957863bd2169
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7938cc2c-e09f-41df-9544-417f7d2f3abe
		summarizeBy: none
		sourceColumn: 'Reading Month'

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		formatString: General Date
		lineageTag: 7522c36b-6242-4a1f-8369-54387a843453
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 9e243444-c5dd-41e8-a15d-62627530c507
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: 78324d6b-84d1-4f1d-97f0-1ff4b2c334e1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-6e6ab447-ce8f-4c4e-88a4-0f0b3a0a9bfc' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Sensors"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"reading_id", "reading_time", "machine_id", "sensor_type", "value", "threshold_min", "threshold_max", "unit", "quality_score", "plant_id", "delta_value", "angle_degrees", "power_watts"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    #"Added Reading Month" = Table.AddColumn(#"Added Rounded Value", "Reading Month", each #date(Date.Year([reading_time]), Date.Month([reading_time]), 1), type datetime),
				    Result = #"Added Reading Month"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 26 columns and 13 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

