// DAX measures for table: Extract
// Auto-generated by Tableau → Power BI migration

GDP % of Total =
AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))

GDP per capita (weighted) =
SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])

Rate spread (difference) =
AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])

Number of Records =
1

