table 'Target Margin'
	lineageTag: e0a016e9-6ead-4921-bf63-90c6299372d7

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: f32769bf-8b43-4483-9d6c-fc52d15170e1
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin'[Value], 0.2)

	column Value
		dataType: double
		lineageTag: f2d010ef-d825-44cc-9d01-a9bbeb399d15
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-33c2d487-af18-45ce-92dc-0ee06f4f77a1' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

