table 'Top N'
	lineageTag: f3c1a59f-5a9d-4f75-b0f5-ab5e2b56885d

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: ae32b7f1-0eeb-43c9-852b-4afa7f613f85
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N'[Value], 10)

	column Value
		dataType: int64
		lineageTag: 718e0384-e540-4ab7-add5-be125c3fecbe
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N-b6fe5301-33eb-44bd-9a08-8e7c27605170' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

