// DAX measures for table: transactions
// Auto-generated by Tableau → Power BI migration

Revenue =
SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))

Expenses =
SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))

Net Income =
SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))

Profit Margin % =
([Revenue] - [Expenses]) / [Revenue]

YTD Revenue =
CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))

Budget Variance =
SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))

