table Campaigns
	lineageTag: 13bd48f5-25f8-4925-81ec-f1b59ca553a6

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: 73b3e1eb-a159-4b12-bf01-a642c3421913
		annotation Copilot_Description = Migrated from Tableau: COUNTA([lead_name]) | DAX: COUNTA('Leads'[lead_name])

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Campaigns'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d16f1e60-45ab-40ce-b2cd-5778a7664e07
		annotation Copilot_Description = Migrated from Tableau: CORR([budget], [deal_value]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[de]))...

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 53f90283-3309-4a7f-a140-1b5721a3af90
		annotation Copilot_Description = Migrated from Tableau: COVAR([spend], [engagement_score]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'),))...

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e95d5605-05b7-419c-b097-4fca6e17f9eb
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [channel] : AVG([deal_value])} | DAX: CALCULATE(AVERAGE('Leads'[deal_value]))

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1b7fa434-5a2f-4e23-a716-7ac191fc525d
		annotation Copilot_Description = Migrated from Tableau: (SUM([deal_value]) - SUM([spend])) / SUM([spend]) | DAX: (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ff1eeb2b-94e9-4b87-a70c-8d3a8c934b9e
		annotation Copilot_Description = Migrated from Tableau: SUM([spend]) / COUNTD([lead_id]) | DAX: SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 830b86b8-721a-447d-b730-2168da5c7d79
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MAX((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 382ad5c1-ec24-4cb8-a2eb-72ccaa8bf368
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MIN((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))

	measure 'Cumulative Leads' = /* TODO: DAX conversion validation failed for Calc_CumLeads: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: 5b494141-d745-400c-8d97-6e056b48f11e
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(COUNTD([lead_id])) | DAX: /* TODO: DAX conversion validation failed for Calc_CumLeads: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 53af49a7-d91d-4b5f-b1c7-80e5568c0d88
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [lead_status] = "Won" THEN 1 ELSE 0 END) / COUNT([lead_id]) | DAX: SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])

	measure 'Target Channel' = "Email"
		lineageTag: 1784f640-05b4-4f68-9c15-dfffcf2bf6e2
		annotation Copilot_Description = DAX: "Email"

	measure 'Budget Deal Correlation Formatted' = VAR _val = [Budget Deal Correlation] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: d07026dc-67b0-42ba-bdaa-44e3f0161cd5
		annotation Copilot_Description = Dynamic numeric abbreviation for Budget Deal Correlation (K/M/B)

	measure 'Spend Engagement Covar Formatted' = VAR _val = [Spend Engagement Covar] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 9fe7b8fb-95d2-4b61-b6a0-dd197b2d8b08
		annotation Copilot_Description = Dynamic numeric abbreviation for Spend Engagement Covar (K/M/B)

	measure 'Campaign ROI Formatted' = VAR _val = [Campaign ROI] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 4247ee8b-1067-4f0e-9fd9-910281cb0ef3
		annotation Copilot_Description = Dynamic numeric abbreviation for Campaign ROI (K/M/B)

	measure 'Cost Per Lead Formatted' = VAR _val = [Cost Per Lead] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 70b3c053-72ec-4be9-8150-073100e66668
		annotation Copilot_Description = Dynamic numeric abbreviation for Cost Per Lead (K/M/B)

	measure 'Window Best ROI Formatted' = VAR _val = [Window Best ROI] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 4878e92c-14ee-42b2-bbf7-f5baccebd554
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Best ROI (K/M/B)

	measure 'Window Worst ROI Formatted' = VAR _val = [Window Worst ROI] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: d90d322b-aa71-4f61-b7d8-42672002d7c7
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Worst ROI (K/M/B)

	measure 'Conversion Rate Formatted' = VAR _val = [Conversion Rate] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 43a2ede3-8d87-4720-8dae-9e5cb1c22d44
		annotation Copilot_Description = Dynamic numeric abbreviation for Conversion Rate (K/M/B)

	column campaign_id
		dataType: int64
		lineageTag: 06827fd3-cb63-475d-8ebd-1584a371a030
		summarizeBy: sum
		sourceColumn: campaign_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 3bfe1f35-43de-4c5b-8537-8253937ad5bf
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 86d901d1-079a-4245-9913-0773a457336d
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b425388-9edb-411d-8d10-99c219c6f573
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b4f1004-4fb6-4a35-bc74-3b5e1aa7a428
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: e616f9e0-e551-4303-9c98-779999cb2c0b
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: bd28c809-af59-4495-8d06-080b9f6d5cad
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: fe5eb6df-fb03-40dd-84da-1e51881f5f73
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: 3ab6c8fc-9606-4e35-9df6-52fd8f87cfbf
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 739c7bc6-39ec-4e76-8013-8fd347e29576
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: ae4c542d-2f4b-4c00-b4b5-95f657cd5856
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 7d9a7f4c-f08c-431e-853f-1a8838d21913
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 88a752d8-d909-4db0-914d-c0d71e10d2cd
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 61b941f3-6b5b-489b-af80-9a7a429c0ca2
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(CALCULATE(SELECTEDVALUE(Leads[email])), FIND("@", CALCULATE(SELECTEDVALUE(Leads[email]))) + 1, LEN(CALCULATE(SELECTEDVALUE(Leads[email]))))
		dataType: string
		lineageTag: 97cf258d-cb5d-41bf-8246-7fb68c60ca92
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(CALCULATE(SELECTEDVALUE(Leads[lead_name])), FIND(" ", CALCULATE(SELECTEDVALUE(Leads[lead_name]))) - 1)
		dataType: string
		lineageTag: 03f3b2b9-1259-496b-a09b-6cfa7260d0cd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(CALCULATE(SELECTEDVALUE(Leads[lead_name])), FIND(" ", CALCULATE(SELECTEDVALUE(Leads[lead_name]))) + 1, LEN(CALCULATE(SELECTEDVALUE(Leads[lead_name]))))
		dataType: string
		lineageTag: 7db41ec3-3ed4-419d-832e-e835ae89178c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(CALCULATE(SELECTEDVALUE(Leads[lead_name])))
		dataType: int64
		lineageTag: cd99758a-8bb8-40be-9c09-4704d31ea2b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(CALCULATE(SELECTEDVALUE(Leads[phone])), "-", ""), " ", ""))
		dataType: string
		lineageTag: 300eefc8-5035-4010-bddb-211560cc0dbf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(CALCULATE(SELECTEDVALUE(Leads[phone])), 4)
		dataType: string
		lineageTag: bb3fa7a9-8e5f-49cd-a83d-3efb4c6df8da
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: 01239763-4f9c-4f28-88b9-8fd57ce4cce6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise'
		dataType: boolean
		lineageTag: e8106c1b-5cd2-42e3-a35c-2c86bfbf3c67
		summarizeBy: none
		sourceColumn: 'Is Enterprise'

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = /* REGEXP_MATCH: complex regex "^[a-z0-9_-]+$" — verify manually */ CONTAINSSTRING('Campaigns'[utm_campaign], "^[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: 101a1bfb-dca8-40a7-9dc0-b899e5c21992
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = /* REGEXP_REPLACE("https?://"): complex regex — verify manually */ SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: b2f03f3b-34ea-4245-8050-31071740bd5f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year'
		dataType: dateTime
		formatString: General Date
		lineageTag: 92dc5adc-7300-45ff-bba7-f6f6427b40dd
		summarizeBy: none
		sourceColumn: 'Campaign Year'

		annotation SummarizationSetBy = Automatic

	column 'Start Month'
		dataType: int64
		lineageTag: d1ae09be-7cc3-4526-be74-143267a9f8e8
		summarizeBy: none
		sourceColumn: 'Start Month'

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: 1fdc9804-18fa-4b80-b1e2-379e0080c1ee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days'
		dataType: int64
		lineageTag: 8702b4d4-5d6e-47bd-a539-280c6ec16de9
		summarizeBy: none
		sourceColumn: 'Campaign Days'

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: c17f47fb-46a0-4c54-88d0-c28f9befb720
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-883490ec-7d00-4064-95a7-02c1a1e7ca8f' = m
		mode: import
		source =
				let
				    // Source MySQL: analytics-mysql.corp.local:3306
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Campaigns"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"campaign_id", "campaign_name", "channel", "start_date", "end_date", "budget", "spend", "target_audience", "creative_url", "utm_source", "utm_medium", "utm_campaign", "region", "status"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    #"Added Is Enterprise" = Table.AddColumn(#"Renamed Columns", "Is Enterprise", each Text.Contains([target_audience], "Enterprise"), type logical),
				    #"Added Campaign Year" = Table.AddColumn(#"Added Is Enterprise", "Campaign Year", each #date(Date.Year([start_date]), 1, 1), type datetime),
				    #"Added Start Month" = Table.AddColumn(#"Added Campaign Year", "Start Month", each Date.Month([start_date]), Int64.Type),
				    #"Added Campaign Days" = Table.AddColumn(#"Added Start Month", "Campaign Days", each Duration.Days(Date.From([end_date]) - Date.From([start_date])), Int64.Type),
				    Result = #"Added Campaign Days"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 29 columns and 18 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (29 columns total).

