table 'Min Budget'
	lineageTag: 35f12fa7-a217-430c-bdc6-5e21a77793f2

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 23c950a9-ead7-4905-9d40-213b25df64c2
		annotation Copilot_Description = DAX: SELECTEDVALUE('Min Budget'[Value], 5000)

	column Value
		dataType: double
		lineageTag: c20c9091-f484-40e4-96fa-fbce6223733e
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-19146df0-dab2-403c-b281-e96ce9a47658' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

