table Calendar
	lineageTag: 5c76d501-90f7-43ce-a143-50c7c5388a14

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fc362fee-52ce-466d-a14d-51cd1252fe8a
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: add3b8a7-470c-4a97-a596-804580527754
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: c4412e02-6147-4dce-8780-d56f91925be7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: de3f7a37-ba08-4563-9dd0-25ffbf03e671
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 35cc9e48-29c3-4cef-9c0d-72f38e7266ff
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 27a087b1-5733-406c-8628-37631c90428b
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: ed9e7478-c550-40f4-95ba-232cadfb7924
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 321875d8-7ff7-4ca5-afc8-b6e36b9e5dd6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: fcc13f7f-c44a-48ca-8fe8-74d1261f64b3

		level Year
			ordinal: 0
			column: Year
			lineageTag: 68ad0fb1-9a0f-45d2-b0ae-6eacee71e853

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 81e52a44-8a61-41e2-8cc7-b02a4ed4d29b

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 61d3ae5b-8daf-4d3a-9a16-53b742d0c5e2

		level Day
			ordinal: 3
			column: Day
			lineageTag: 2300eccb-dfcf-444d-be1c-fcfb0315e39e


	partition 'Calendar-589d0240-889a-4694-bec4-ad84fac67481' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

