table Calendar
	lineageTag: 053c7d8e-d0b7-4f7c-bada-49e859fcc536

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6e5142f7-9535-4061-a81f-b3e0222ddc78
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: a6a89f4f-f3e5-4680-bcb3-76bcc1c1153f
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 946c5017-6dba-469a-a17b-9363765a75bc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 5be31a95-18f5-4abe-804e-e6d5a9e224db
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ccf249b2-f682-495b-93b0-69b44a845e76
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 60f3acde-b9d9-4ce2-b916-fbddd87a2e46
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 1a41a9f2-5269-46ec-b602-31d1b5934356
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7063b43a-3941-4d0f-b9df-f76580cd66ba
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: ec559a0e-f1b0-4344-b935-b32975fc1a88

		level Year
			ordinal: 0
			column: Year
			lineageTag: 90c98a66-5a51-489a-af27-6a3bfbde5ade

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ceb4873a-3c94-44b0-9d91-dcbffd683f67

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 5d483e99-bac5-4332-83b7-3ebfea76cc17

		level Day
			ordinal: 3
			column: Day
			lineageTag: 4300774f-eb02-4154-bb8c-44b2e6ad4af5


	partition 'Calendar-877ed54c-7176-4705-ba1e-06053aa94c82' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

