table 'Objectif Marge'
	lineageTag: e50c77ef-f670-4846-90d8-df414bf5b21f

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: 99e19aa9-f545-43aa-9524-aff2babf7254
		annotation Copilot_Description = DAX: SELECTEDVALUE('Objectif Marge'[Value], 0.15)

	column Value
		dataType: double
		lineageTag: fb57762f-9fa6-4e89-91d3-ae3b5f7f8386
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-b094f5b0-0787-4cb3-a702-5c38f9af7efa' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

