table 'Top N Produits'
	lineageTag: 25760e05-4849-4ca7-a292-5732c3a7f6f8

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: 0c12d7d2-6439-4475-9b6e-ff9a60468512
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Produits'[Value], 10)

	column Value
		dataType: int64
		lineageTag: 7f47e3e8-a697-4a73-b37e-047915da515e
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-282c790a-6306-48ff-9683-232cf3ba4e47' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

