table Calendar
	lineageTag: d32d44f9-32bf-4c69-b00b-93c62a0ed815

	measure 'Year To Date' = TOTALYTD([Region Match], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d3f7094c-32fa-4598-b92a-8432c6074f5e
		annotation Copilot_Description = DAX: TOTALYTD([Region Match], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Region Match], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 1f19adb8-4e7f-4615-aa06-e0666733b235
		annotation Copilot_Description = DAX: CALCULATE([Region Match], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 6479474c-9a90-489a-a532-ff589eef1157
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 19e16abd-2850-401b-af8f-ac15513a3f95
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 65c5b0a7-e008-411a-b884-e63836323c48
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 674c325b-8734-4a02-b9e2-0b5e51efd9de
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 2b119460-5d24-457e-9174-3561512c1be2
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: eff512ea-653b-4b70-9913-10dc32b66c0e
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5a8e74da-5a06-4bee-a45b-3538cbbdfad4
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: fdafc160-a6f9-4f69-8635-6e4c5b5f5782
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8e4f453e-13bd-4cc9-8080-76395fa484f0
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: f6379c32-82dd-4f61-801e-3ad082b9b307

		level Year
			ordinal: 0
			column: Year
			lineageTag: af5ed374-d8a3-4e67-a77b-22e2fcb8c0db

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: b382a2aa-61b1-4c90-ade0-ae17919938cd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 6bba8f2c-a9ce-42f1-a6a0-00fcd5c8deb3

		level Day
			ordinal: 3
			column: Day
			lineageTag: fbf3f580-c51e-4916-b86e-8c71051b637a


	partition 'Calendar-d19123c0-d521-46f8-b0b5-1e773bfe726a' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

