table Regions
	lineageTag: 751252ce-42e6-4228-ae09-dbc9e6ee93ee

	column RegionName
		dataType: string
		lineageTag: 2e8e0201-baa1-483a-9257-91f732a11bdb
		summarizeBy: none
		sourceColumn: RegionName
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column RegionManager
		dataType: string
		lineageTag: 75be9bbb-c343-4679-a138-a670a4639c85
		summarizeBy: none
		sourceColumn: RegionManager
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'Regions-bfcbea40-93a5-4404-814c-a734032cd0b7' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "SalesDB"),
				
				            _nav = _src{[Schema="dbo", Item="Regions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"RegionName", "RegionManager"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"RegionName", "Region Name"}, {"RegionManager", "Region Manager"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: RegionName, RegionManager.

