table TestData
	lineageTag: b8c395f5-58a0-49b1-b3a3-e129f9fe8469

	measure 'Number of Records' = COUNTROWS('TestData')
		displayFolder: Measures
		lineageTag: 151a73d9-5e95-4b1b-8126-aa138ec30359
		annotation Copilot_Description = DAX: COUNTROWS('TestData')

	column 'Account Account Name'
		dataType: string
		lineageTag: 82af3a56-5c89-4bd3-9982-1cfc57603c44
		summarizeBy: none
		sourceColumn: 'Account Account Name'

		annotation SummarizationSetBy = Automatic

	column 'Account Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 21774424-b94c-47f5-bf67-a865dfc490be
		summarizeBy: sum
		sourceColumn: 'Account Number'

		annotation SummarizationSetBy = Automatic

	column 'Account Number Burst Out Account'
		dataType: string
		lineageTag: 011fb08b-42ef-4da6-80df-4f3bdd98c979
		summarizeBy: none
		sourceColumn: 'Account Number Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Acct Name'
		dataType: string
		lineageTag: 3fcdedf2-1bdd-47e6-83ad-35640381ca05
		summarizeBy: none
		sourceColumn: 'Acct Name'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out'
		dataType: string
		lineageTag: fa3f2d82-30f8-48ad-b8bd-3c25137be7b1
		summarizeBy: none
		sourceColumn: 'Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Join'
		dataType: string
		lineageTag: bb40e1a3-39e9-48e4-860b-21d4828c2e76
		summarizeBy: none
		sourceColumn: 'Burst Out Join'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out Set list'
		dataType: string
		lineageTag: 85ff8b99-75d4-4342-8347-661c5fe8d9db
		summarizeBy: none
		sourceColumn: 'Burst Out Set list'

		annotation SummarizationSetBy = Automatic

	column 'Burst Out View'
		dataType: double
		formatString: #,0.00
		lineageTag: f5cc6cb6-8745-4ea2-b1f5-5411ca3ffcbd
		summarizeBy: sum
		sourceColumn: 'Burst Out View'

		annotation SummarizationSetBy = Automatic

	column 'Count JE Number'
		dataType: double
		formatString: #,0.00
		lineageTag: 941bb196-79e5-4b47-a222-37c44c8d9260
		summarizeBy: sum
		sourceColumn: 'Count JE Number'

		annotation SummarizationSetBy = Automatic

	column 'Entity ID'
		dataType: string
		lineageTag: 744760b6-ac62-4ba0-ad8e-d80156784cdb
		summarizeBy: none
		sourceColumn: 'Entity ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Filter
		dataType: double
		formatString: #,0.00
		lineageTag: ca399ec7-9041-445a-86d2-4da33f3761c3
		summarizeBy: sum
		sourceColumn: Filter

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 5e4d37d5-71e6-47dd-8593-4ea459ae9872
		summarizeBy: none
		sourceColumn: 'Fiscal Year'

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: boolean
		lineageTag: 48c38505-f4e3-4539-ada0-af897ebee685
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	column Flag__copy_
		dataType: boolean
		lineageTag: 33be80c4-c618-46f4-963d-e0ca39f47dc7
		summarizeBy: none
		sourceColumn: Flag__copy_

		annotation SummarizationSetBy = Automatic

	column 'FS Line'
		dataType: double
		formatString: #,0.00
		lineageTag: 68e24487-6bf8-4bd1-aa78-629cf1e2811e
		summarizeBy: sum
		sourceColumn: 'FS Line'

		annotation SummarizationSetBy = Automatic

	column 'FS Line Burst Out Account'
		dataType: string
		lineageTag: 02807827-395a-4300-87ea-cea9d4612724
		summarizeBy: none
		sourceColumn: 'FS Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column 'Group By'
		dataType: double
		formatString: #,0.00
		lineageTag: 5fda3f34-0f9b-486e-a40a-05868c1d6c30
		summarizeBy: sum
		sourceColumn: 'Group By'

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: e220ebff-15b5-44dd-a1b5-7fab617c160b
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column 'Note Line'
		dataType: double
		formatString: #,0.00
		lineageTag: fb3958b8-a706-42d8-b453-c567f087eaae
		summarizeBy: sum
		sourceColumn: 'Note Line'

		annotation SummarizationSetBy = Automatic

	column 'Note Line Burst Out Account'
		dataType: string
		lineageTag: 40f3c232-e90f-40d1-b333-7cc05439f93b
		summarizeBy: none
		sourceColumn: 'Note Line Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Selection
		dataType: double
		formatString: #,0.00
		lineageTag: e1bae56a-bcdb-4eca-8393-fae096dd5f24
		summarizeBy: sum
		sourceColumn: Selection

		annotation SummarizationSetBy = Automatic

	column SHOW = IF('TestData'[BurstoutSet], "Selected", "Not Selected")
		dataType: string
		lineageTag: 0b0f01ec-eceb-4c7a-999e-782991e8d1f9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Show Cycle Based'
		dataType: string
		lineageTag: 58f653db-2833-4883-b04f-a41a5a9508ac
		summarizeBy: none
		sourceColumn: 'Show Cycle Based'

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: double
		formatString: #,0.00
		lineageTag: cfaa8316-1853-471a-acd5-2ccbdae05ea4
		summarizeBy: sum
		sourceColumn: 'Sub Class'

		annotation SummarizationSetBy = Automatic

	column 'SubClass Burst Out Account'
		dataType: string
		lineageTag: faf01386-bd36-4e3c-ad60-3dca6a2ebcc4
		summarizeBy: none
		sourceColumn: 'SubClass Burst Out Account'

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 85fb8f20-8586-498f-bfae-96e49734df00
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: string
		lineageTag: 5762da3e-3167-4612-b512-9ffd9c9fed66
		summarizeBy: none
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Amount1
		dataType: string
		lineageTag: 95fba76a-3e33-45f3-9eab-8917ba0cb551
		summarizeBy: none
		sourceColumn: Amount1

		annotation SummarizationSetBy = Automatic

	column 'Count of Amount Calculation'
		dataType: double
		formatString: #,0.00
		lineageTag: 1c952cce-6bc4-45ff-a626-b92fd2e52a68
		summarizeBy: sum
		sourceColumn: 'Count of Amount Calculation'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: double
		formatString: #,0.00
		lineageTag: 2d311237-b731-4f83-a61b-42546ab1419b
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records1'
		dataType: double
		formatString: #,0.00
		lineageTag: 6ec0340d-255a-4062-8cc1-fc4112914b71
		summarizeBy: sum
		sourceColumn: 'Number of Records1'

		annotation SummarizationSetBy = Automatic

	column 'Select Burst Out'
		dataType: double
		formatString: #,0.00
		lineageTag: e7105b78-020d-4e7d-b5c4-72aa13e43121
		summarizeBy: sum
		sourceColumn: 'Select Burst Out'

		annotation SummarizationSetBy = Automatic

	column 'Select Transaction Analysis view'
		dataType: double
		formatString: #,0.00
		lineageTag: 690e32ff-9893-482a-b625-66524fa0665d
		summarizeBy: sum
		sourceColumn: 'Select Transaction Analysis view'

		annotation SummarizationSetBy = Automatic

	column 'Sum Cy'
		dataType: double
		formatString: #,0.00
		lineageTag: c4111461-39ab-4ab6-9927-c6d298011905
		summarizeBy: sum
		sourceColumn: 'Sum Cy'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py1'
		dataType: double
		formatString: #,0.00
		lineageTag: 5542e32d-26a2-42e5-8951-ae5c1a421fd0
		summarizeBy: sum
		sourceColumn: 'Sum Py1'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py2'
		dataType: double
		formatString: #,0.00
		lineageTag: 270e4a87-0fe9-47c3-966c-6ee653d055c1
		summarizeBy: sum
		sourceColumn: 'Sum Py2'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py3'
		dataType: double
		formatString: #,0.00
		lineageTag: 58a7bbde-1d3a-4641-adfa-d95d52d9a107
		summarizeBy: sum
		sourceColumn: 'Sum Py3'

		annotation SummarizationSetBy = Automatic

	column 'Sum Py4'
		dataType: double
		formatString: #,0.00
		lineageTag: a79b5233-1b00-4bbe-a6c8-32b85a8b032b
		summarizeBy: sum
		sourceColumn: 'Sum Py4'

		annotation SummarizationSetBy = Automatic

	column 'Total Credits'
		dataType: double
		formatString: #,0.00
		lineageTag: 708d741b-58c1-42ac-a38f-5a7747f7fd5b
		summarizeBy: sum
		sourceColumn: 'Total Credits'

		annotation SummarizationSetBy = Automatic

	column 'Total Debits'
		dataType: double
		formatString: #,0.00
		lineageTag: 17001817-da1c-4cd3-9b45-74c6b6861d32
		summarizeBy: sum
		sourceColumn: 'Total Debits'

		annotation SummarizationSetBy = Automatic

	column BurstoutSet
		dataType: string
		lineageTag: 187950bd-1558-420d-9cf8-3675ec3d322a
		summarizeBy: none
		sourceColumn: BurstoutSet
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'TestData-a1bcda98-703d-4783-83c4-888d44ab8ec4' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("b5dpm3ihhu.database.windows.net", "EmptyDB"),
				
				            _nav = _src{[Schema="dbo", Item="TestData"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Account Account Name", "Account Number", "Account Number Burst Out Account", "Acct Name", "Burst Out", "Burst Out Join", "Burst Out Set list", "Burst Out View", "Count JE Number", "Entity ID", "Filter", "Fiscal Year", "Flag", "Flag__copy_", "FS Line", "FS Line Burst Out Account", "Group By", "Image", "Note Line", "Note Line Burst Out Account", "Selection", "show", "Show Cycle Based", "Sub Class", "SubClass Burst Out Account", "Type", "Amount", "Amount1", "Count of Amount Calculation", "Number of Records", "Number of Records1", "Select Burst Out", "Select Transaction Analysis view", "Sum Cy", "Sum Py1", "Sum Py2", "Sum Py3", "Sum Py4", "Total Credits", "Total Debits"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"show", "Show"}}),
				    #"Added BurstoutSet" = Table.AddColumn(#"Renamed Columns", "BurstoutSet", each "", type text),
				    Result = #"Added BurstoutSet"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 41 columns and 1 measures: Account Account Name, Account Number, Account Number Burst Out Account, Acct Name, Burst Out, Burst Out Join, Burst Out Set list, Burst Out View, ... (41 columns total).

