table xy
	lineageTag: 7a733b97-ba6c-43fe-97ae-4bf24ef6d718

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: a13c0181-60e6-4000-99f6-6e57ed1a57df
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	column a
		dataType: string
		lineageTag: 6d70e3b8-9eec-41e2-8535-bf354143504a
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 157d2364-4435-4af0-af68-5c0b47ed4c3e
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: d1b93364-4237-4e0e-8a86-fcb60ab371ae
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-9d1a50fb-57fd-41e3-a966-b35f29b8f557' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 1 measures: a, x, y.

