table xy
	lineageTag: dd6aeb54-94aa-4763-8713-bae180e91996

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: b46951de-3800-41ec-9eb0-06b3a3628390
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	measure 'SUM(X) + SUM(Y)' = SUM('xy'[x]) + SUM('xy'[y])
		displayFolder: Measures
		lineageTag: addd40c7-c668-4a90-8007-f05e3dd0442a
		annotation Copilot_Description = Migrated from Tableau: SUM([x]) + SUM([y]) | DAX: SUM('xy'[x]) + SUM('xy'[y])

	measure 'SUM(X) + SUM(Y) Formatted' = VAR _val = [SUM(X) + SUM(Y)] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: 2d00899b-d208-4410-852b-3e4514e41e35
		annotation Copilot_Description = Dynamic numeric abbreviation for SUM(X) + SUM(Y) (K/M/B)

	column a
		dataType: string
		lineageTag: c7b26a52-cd21-4bf6-b17b-837a9ecebfdb
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: 30e24262-40b4-4fdd-b013-89f33162a372
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: f9029972-cc31-4dc7-ba84-504c4bfa299c
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-2cd4c121-cc6e-4d73-aa26-032151a855c5' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 3 columns and 3 measures: a, x, y.

