table sessions
	lineageTag: a7a47a67-a2e1-4e68-99fb-d4d54e37d253

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: 88f8de3c-68e9-4c85-b58e-a81bcddc456d
		annotation Copilot_Description = Migrated from Tableau: COUNT([session_id]) | DAX: COUNT('sessions'[session_id])

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: 01c47933-fe73-470c-922a-f6b6ab72e7df
		annotation Copilot_Description = Migrated from Tableau: COUNTD([user_id]) | DAX: DISTINCTCOUNT('sessions'[user_id])

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 7843836c-1ba9-43cc-9666-b190d4d56e3c
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [converted] THEN 1 ELSE 0 END) / COUNT([session_id]) | DAX: SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 355fab85-2371-4fb6-acba-c2efcf4a2a12
		annotation Copilot_Description = Migrated from Tableau: AVG([session_duration]) | DAX: AVERAGE('sessions'[session_duration])

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 13ea1251-e7cd-40ff-9eaf-1a0103938aff
		annotation Copilot_Description = Migrated from Tableau: SUM([revenue]) | DAX: SUM('sessions'[revenue])

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: eee158cc-f8bf-4f5d-8f47-de5cbfab5f06
		annotation Copilot_Description = Migrated from Tableau: SUM([revenue]) / COUNT([session_id]) | DAX: SUM('sessions'[revenue]) / COUNT('sessions'[session_id])

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e7ccb66f-1b58-45cc-a3f4-923df53b8f55
		annotation Copilot_Description = Migrated from Tableau: {FIXED [channel] : SUM([revenue])} | DAX: CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))

	column session_id
		dataType: string
		lineageTag: d156e8d6-8e44-4e1a-92a7-c0e0a379c275
		summarizeBy: none
		sourceColumn: session_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ebd716b-f024-4df8-b908-ecc0d25b155a
		summarizeBy: none
		sourceColumn: session_date

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: 9873a938-25cb-4d40-9f30-b1f4089db92a
		summarizeBy: none
		sourceColumn: user_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 883f7f76-0e28-46d7-b869-eb0df476ecd1
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 6fece4ab-fa78-4ca6-a8ba-3644718f7cf1
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: fbb21abc-203c-461c-bb52-156d34ea7818
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: aa662c21-9d64-4e09-8b52-f4db57e69e33
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: 2222518b-0bd4-4427-95ab-000cf9c6ce8b
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: 15004ead-98a7-4c6a-bff3-6afb7d007d49
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 2731fefd-749b-4f87-9406-408bedffc442
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category'
		dataType: string
		lineageTag: 45a8b30d-88b0-462b-8be7-5b0d613e9b35
		summarizeBy: none
		sourceColumn: 'Channel Category'

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level'
		dataType: string
		lineageTag: b0d4d2b1-3b93-4242-bef7-0c9c468e43cc
		summarizeBy: none
		sourceColumn: 'Engagement Level'

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(CALCULATE(SELECTEDVALUE(users[signup_date])), TODAY(), DAY)
		dataType: int64
		lineageTag: 19cf7602-c880-4abb-9410-b12e2ee2e346
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'sessions-a0d86cbc-f57a-4ccd-a78e-16da0a078413' = m
		mode: import
		source =
				let
				    // Source Google BigQuery: my-analytics-project.web_data
				    Source = try
				
				        let
				
				            _src = GoogleBigQuery.Database([BillingProject="my-analytics-project"]),
				
				            _nav = _src{[Name="web_data"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"session_id", "session_date", "user_id", "channel", "device_type", "country", "page_views", "session_duration", "converted", "revenue"}, {}),
				    #"sessions Table" = Source{[Name="sessions"]}[Data],
				    #"Added Channel Category" = Table.AddColumn(#"sessions Table", "Channel Category", each if [channel] = "Organic Search"  or  [channel] = "Paid Search" then "Search" else if [channel] = "Social"  or  [channel] = "Referral" then "Social/Referral" else if [channel] = "Direct" then "Direct" else "Other", type text),
				    #"Added Engagement Level" = Table.AddColumn(#"Added Channel Category", "Engagement Level", each if [page_views] >= 10 then "High" else if [page_views] >= 5 then "Medium" else "Low", type text),
				    Result = #"Added Engagement Level"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 13 columns and 7 measures: session_id, session_date, user_id, channel, device_type, country, page_views, session_duration, ... (13 columns total).

