table xy
	lineageTag: dd120dd6-e5f4-47dd-bee2-2e0156684e98

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: f5058f70-92b2-48da-81d1-0995c942f874
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	column a
		dataType: string
		lineageTag: 29636b80-120a-4ad8-8034-5b4952a43734
		summarizeBy: none
		sourceColumn: a

		annotation SummarizationSetBy = Automatic

	column 'Today''s Date'
		dataType: string
		lineageTag: e0b40416-7aac-45ca-99fd-fa08848f433e
		summarizeBy: none
		sourceColumn: 'Today''s Date'

		annotation SummarizationSetBy = Automatic

	column x
		dataType: int64
		lineageTag: e6b81c10-7a8d-4242-a1a9-f1a7b30ffe25
		summarizeBy: sum
		sourceColumn: x

		annotation SummarizationSetBy = Automatic

	column y
		dataType: int64
		lineageTag: a95edac5-8d55-46b5-903c-850f262f9c14
		summarizeBy: sum
		sourceColumn: y

		annotation SummarizationSetBy = Automatic

	partition 'xy-00a05a92-b4c2-4e16-a683-ed6266564b05' = m
		mode: import
		source =
				let
				    // Source PostgreSQL
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("postgres91.test.tsi.lan:5432", "TestV1"),
				
				            _nav = _src{[Schema="public", Item="xy"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"a", "Today's Date", "x", "y"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"a", "A"}, {"x", "X"}, {"y", "Y"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 4 columns and 1 measures: a, Today's Date, x, y.

