table 'Alert Threshold'
	lineageTag: d9179980-dd3c-49e1-8a06-03dda3bdb295

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: c6286c5e-4f75-41a7-975c-2482fd0760b2
		annotation Copilot_Description = DAX: SELECTEDVALUE('Alert Threshold'[Value], 100)

	column Value
		dataType: double
		lineageTag: 145e3221-45db-4b83-9798-bafb0c550d7d
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-3789ca7f-8c79-4c20-bd2a-6e6b8a7f6c20' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

