table Calendar
	lineageTag: 6a5def31-7a38-40bd-b0c0-b35e866ce913

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5cf7f198-3c78-4942-b4e0-4651e80047df
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 1c6845b5-fa3b-43e7-b1c9-2494f04ce47e
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 49fe599d-fd5a-4acd-9300-511b250c15e5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 072be6c5-09d5-47d6-a2dc-08f87ffaff28
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 463da6c7-82d3-4390-aefc-53e36b2c09af
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 23eeae0d-4f88-40ce-bfb4-f4a73a8a92ea
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0c563cf4-f98c-4157-bef3-d8d428ab9d36
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 7d857c41-16c9-4023-98fe-9a6a7dc1fd55
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bc71f255-25ee-4278-84bb-2c11c37ca56a

		level Year
			ordinal: 0
			column: Year
			lineageTag: 044cfa69-d930-4d37-a24c-f93f4c3ce6f3

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 6acd16ca-1e56-4eb4-ba97-d2cc26b580fc

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 16af937b-d197-4dea-b712-f1a2515c00af

		level Day
			ordinal: 3
			column: Day
			lineageTag: 94d43329-928f-45fe-b551-a422b2b00daf


	partition 'Calendar-2a6a8705-4f0d-40d7-88f3-9a056835eabc' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

