table Maintenance
	lineageTag: c1efcaa7-a782-42fd-afa2-08a478678481

	column maint_id
		dataType: int64
		lineageTag: a3e96689-a0d5-4b09-9c60-50b668288a5a
		summarizeBy: sum
		sourceColumn: maint_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 6e60cf87-93c5-4350-b421-9e46c0c37004
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0cddc102-dcd3-4b6b-9221-ffc84020e5f2
		summarizeBy: none
		sourceColumn: maint_date

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 7f230ac1-5454-40e6-a87d-31230a3fbfb7
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: e3d724fc-3130-470e-b197-4e4483649a9b
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 5e5fb2af-256d-4e95-af8b-386fb61c40a6
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: eaa0ddeb-a6a9-4fc0-be5b-f580319f8403
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 611583cc-3e33-42dc-a8ec-e240811feb6e
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-af0ac6ab-9f05-44ec-ae5d-25fffac8845d' = m
		mode: import
		source =
				let
				    // Source Oracle: mfg-oracle.corp.local:1521/MFGDB
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

