table dim_date
	lineageTag: b8ef0986-393e-4e96-bb0d-1fa282aedad4

	column date_key
		dataType: int64
		lineageTag: 2a5a78d7-a5ea-4710-a9ce-002c9f4e50ad
		summarizeBy: sum
		sourceColumn: date_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 365c30fc-b284-48ed-a2f9-065b59007118
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: 4b39562c-6fe0-4356-901f-382f7713386c
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: 268c3da4-1153-4416-918d-f86f70e496fe
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		lineageTag: 087f5dfe-51c7-4092-b18e-09f0358d2c16
		summarizeBy: sum
		sourceColumn: month_num

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: c6c35031-4825-4a6c-9a11-1e8cc312acb8
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column week_num
		dataType: int64
		lineageTag: c11420c1-ee09-4f04-9ae9-81d2e365ccc0
		summarizeBy: sum
		sourceColumn: week_num

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: c096a9e8-bc7a-4db6-ae97-e319c6abafd5
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: 79e804b5-4db5-4695-a3b6-0b38af3ba135
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		lineageTag: c0c22588-8077-4ded-b6b1-67515e05db3e
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: string
		lineageTag: 77c7f8ba-f23d-4c73-bda8-471c61bbff72
		summarizeBy: none
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: 716d389c-a0dc-4e5a-a282-b4f3d4e204a7
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	partition 'dim_date-2a636473-28e6-4e51-8ec8-e1c1e7fda275' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"date_key", "full_date", "year", "quarter", "month_num", "month_name", "week_num", "day_name", "is_weekend", "is_holiday", "fiscal_quarter", "fiscal_year"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_date Table" = #"SALES"{[Name="dim_date"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_date Table", {{"full_date", "Full Date"}, {"year", "Year"}, {"quarter", "Quarter"}, {"month_num", "Month"}, {"month_name", "Month Name"}, {"week_num", "Week"}, {"day_name", "Day Name"}, {"is_weekend", "Weekend?"}, {"is_holiday", "Holiday?"}, {"fiscal_quarter", "Fiscal Quarter"}, {"fiscal_year", "Fiscal Year"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: date_key, full_date, year, quarter, month_num, month_name, week_num, day_name, ... (12 columns total).

