table fact_sales
	lineageTag: 1c96f4c4-6296-4387-accc-a3f34f29db4b

	measure 'Gross Revenue' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e524b672-3398-4d71-926c-4eb0d60fdc63
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])

	measure 'Net Revenue' = SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 76d8b1af-a744-4a31-8c2c-ac0dc2470614
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [order_status] != "Cancelled" AND [is_returned] = FALSE THEN [quantity] * [unit_price] * (1 - [discount_pct]) ELSE 0 END) | DAX: SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))

	measure COGS = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 57285eb5-453c-4785-9a6d-f949991adfea
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_cost]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])

	measure 'Gross Profit' = [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 352418b3-5671-4652-b78b-1d3ca0b18144
		annotation Copilot_Description = Migrated from Tableau: [C_NetRev] - [C_COGS] - SUM([shipping_cost]) | DAX: [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])

	measure 'Gross Margin %' = IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0c279f4b-aeb1-48e0-85f8-aae86da4b3e6
		annotation Copilot_Description = Migrated from Tableau: ZN([C_GrossProfit] / [C_NetRev]) | DAX: IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])

	measure 'Tax Amount' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f67e5b8d-c113-49b2-9fc2-7b07ae46a0fb
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price] * (1 - [discount_pct]) * [tax_rate]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])

	measure 'Total Revenue incl Tax' = [Net Revenue] + [Tax Amount]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ba0141cb-2bfe-4554-bc4c-53b9b6be57e5
		annotation Copilot_Description = Migrated from Tableau: [C_NetRev] + [C_TaxAmt] | DAX: [Net Revenue] + [Tax Amount]

	measure 'Return Rate' = SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a52ad8d5-521a-4c0c-8202-0b40078aa388
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [is_returned] = TRUE THEN 1 ELSE 0 END) / COUNT([sale_id]) | DAX: SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])

	measure 'Revenue per Customer' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 724fd3db-9353-440b-8bbb-020eb20714f6
		annotation Copilot_Description = Migrated from Tableau: {FIXED [customer_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))

	measure 'Revenue per Product' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8e7951f4-f6d0-4ae8-be21-543ae4500db0
		annotation Copilot_Description = Migrated from Tableau: {FIXED [product_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))

	measure 'Revenue by Region-Channel' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 71739e69-0a41-4041-bfe4-eaae7f40b182
		annotation Copilot_Description = Migrated from Tableau: {FIXED [region], [channel] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))

	measure 'Revenue excl Territory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0f0e6556-690e-4484-b22b-5ed82b4ce5c3
		annotation Copilot_Description = Migrated from Tableau: {EXCLUDE [territory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))

	measure 'Revenue incl Subcategory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c4d1f5c5-a727-4f91-ac20-eff93cb2a8ee
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [subcategory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))

	measure 'Running Total Revenue' = /* TODO: DAX conversion validation failed for C_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 07735416-7886-4d49-b78d-d03b148db3d7
		annotation Copilot_Description = Migrated from Tableau: RUNNING_SUM(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for C_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Avg Revenue' = /* TODO: DAX conversion validation failed for C_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 12998d9c-aef2-4972-84b2-c7529bc772de
		annotation Copilot_Description = Migrated from Tableau: RUNNING_AVG(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for C_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Count' = /* TODO: DAX conversion validation failed for C_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: e3f2ae6c-8865-4d58-a7a8-ef55200b3499
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(SUM([quantity])) | DAX: /* TODO: DAX conversion validation failed for C_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Revenue Rank' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		displayFolder: Measures
		lineageTag: a7d3822b-23e9-41df-928a-3278785840fc
		annotation Copilot_Description = Migrated from Tableau: RANK(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))

	measure 'Revenue Rank Dense' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: e7595940-ee75-4927-a139-4d5d1c82004d
		annotation Copilot_Description = Migrated from Tableau: RANK_DENSE(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)

	measure 'Moving Avg 3-Period' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('fact_sales'[sale_id]), ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame SUM('fact_sales'[-2,0]) */
		formatString: #,0.00
		displayFolder: Measures
		isHidden
		lineageTag: 003a9c3e-fb1d-44fc-b69c-900f71398d97
		annotation Copilot_Description = Migrated from Tableau: WINDOW_AVG(SUM([quantity] * [unit_price]), -2, 0) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('fact_sales'[sale_id]), ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame SUM('fact_sa)...

	measure 'Window Max Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 11e57c64-bc95-408f-a650-50ce252dc1bb
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MAX(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))

	measure 'Revenue StdDev' = STDEVX.S('fact_sales', MAX('fact_sales'[quantity]) * MAX('fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9adc116c-4960-4882-9b3c-0b271b47f17a
		annotation Copilot_Description = Migrated from Tableau: STDEV(SUM([quantity] * [unit_price])) | DAX: STDEVX.S('fact_sales', MAX('fact_sales'[quantity]) * MAX('fact_sales'[unit_price]))

	measure 'Order Count' = DISTINCTCOUNT('fact_sales'[sale_id])
		displayFolder: Measures
		lineageTag: b85fc6d0-8e12-4fdf-843a-8dc5bb105a8c
		annotation Copilot_Description = Migrated from Tableau: COUNTD([sale_id]) | DAX: DISTINCTCOUNT('fact_sales'[sale_id])

	measure 'Unique Customers' = DISTINCTCOUNT('dim_customer'[customer_id])
		displayFolder: Measures
		lineageTag: 4dc783d6-277b-480e-ab8a-2f1621f6681c
		annotation Copilot_Description = Migrated from Tableau: COUNTD([customer_id]) | DAX: DISTINCTCOUNT('dim_customer'[customer_id])

	measure 'Unique Products Sold' = DISTINCTCOUNT('dim_product'[product_id])
		displayFolder: Measures
		lineageTag: ccaa7163-f615-4ce0-9987-78a2f5292bbf
		annotation Copilot_Description = Migrated from Tableau: COUNTD([product_id]) | DAX: DISTINCTCOUNT('dim_product'[product_id])

	measure 'Customer Tier' = IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))
		displayFolder: Dimensions
		lineageTag: 1cb00c61-0316-454f-ba6d-d1687548f18b
		annotation Copilot_Description = Migrated from Tableau: IF [C_RevPerCust] > 100000 THEN "Enterprise" ELSEIF [C_RevPerCust] > 50000 THEN "Mid-Market" ELSEIF [C_RevPerCust] > 10000 THEN "SMB" ELSE "Startup" END | DAX: IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))

	measure 'YTD Revenue' = CALCULATE(SUMX('dim_date', IF('dim_date'[year] = YEAR(TODAY()) && LOOKUPVALUE(fact_sales[is_returned], fact_sales[date_key], dim_date[date_key]) = FALSE, LOOKUPVALUE(fact_sales[quantity], fact_sales[date_key], dim_date[date_key]) * LOOKUPVALUE(fact_sales[unit_price], fact_sales[date_key], dim_date[date_key]), 0)), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9abb6f7a-c692-4c5f-ab6f-e3d49710ce41
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF [year] = YEAR(TODAY()) AND [is_returned] = FALSE THEN [quantity] * [unit_price] ELSE 0 END)} | DAX: CALCULATE(SUMX('dim_date', IF('dim_date'[year] = YEAR(TODAY()) && LOOKUPVALUE(fact_sales[is_returned], fact_sales[date_key], dim_date[date_key]) = FALSE, LOOKUPVALUE(fact_sales[quantity], fact_sales[d]))))...

	measure 'Is My Account' = SUM('dim_customer'[email]) = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: d9da18dc-3d3c-40f2-bc4d-590341b3fcdf
		annotation Copilot_Description = Migrated from Tableau: [email] = USERNAME() | DAX: SUM('dim_customer'[email]) = USERPRINCIPALNAME()

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 328fba2d-16d2-46c0-94b4-b6cb177f100b
		annotation Copilot_Description = Migrated from Tableau: ISMEMBEROF("Regional Managers") | DAX: TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */

	measure 'Analysis Start Date' = DATE(2024, 1, 1)
		lineageTag: 64f2836a-deda-4849-9313-a770a5a31447
		annotation Copilot_Description = DAX: DATE(2024, 1, 1)

	measure 'Metric Selector' = "Revenue"
		lineageTag: 25be56dd-ddc8-414d-9c8c-78504194eb4d
		annotation Copilot_Description = DAX: "Revenue"

	measure 'Display Currency' = "USD"
		lineageTag: f8331a8c-8ea9-47a7-a3aa-b2d1dc566959
		annotation Copilot_Description = DAX: "USD"

	column sale_id
		dataType: int64
		lineageTag: 4be1c159-9dfa-4420-b460-51b97d088938
		summarizeBy: sum
		sourceColumn: sale_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		lineageTag: f2a8363a-8588-473c-a1c8-92c49cf4f4a5
		summarizeBy: sum
		sourceColumn: date_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		lineageTag: 79a3e44c-7f24-4311-8873-4f74aa4f51af
		summarizeBy: sum
		sourceColumn: customer_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		lineageTag: 91ebfb87-f88f-4ae9-9c6a-ce6d372d472e
		summarizeBy: sum
		sourceColumn: product_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		lineageTag: 8f58b4a9-6f00-48a5-8de0-cbf59cd0da04
		summarizeBy: sum
		sourceColumn: store_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 38775e43-746d-41a8-a72c-0c4d926989df
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 2d4304be-8af5-48a7-bdad-d79910d4986a
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 38907b39-cb28-4578-b446-b926d2a3a1c1
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: fac38548-1d91-4a86-b012-70a285de49f7
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 58f8de6c-a086-4891-b230-09f4c418601f
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 9a12d26b-b20b-4a68-ac83-6220619b96b4
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: 9de96467-a990-4d89-a6d1-3c4bdc5dbbc7
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: eaa56d9f-207a-4a7b-9ab4-244882dcbffe
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: effa11e9-a70e-4e01-b1e9-f24a400abbe8
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 6de8e9a0-96be-40b5-8aad-0c2bcfc218e0
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: db25c3be-24ab-43a5-9e83-d7bd2879d6e1
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		lineageTag: c9eb14e2-98ea-489a-a8d5-4e0aab24eaa8
		summarizeBy: sum
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column discount_pct
		dataType: double
		formatString: #,0.00
		lineageTag: 20a0d6b2-98cc-4a16-a812-ff78afb1809c
		summarizeBy: sum
		sourceColumn: discount_pct

		annotation SummarizationSetBy = Automatic

	column tax_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 3612c19d-d5e1-4925-9c08-480960ef2418
		summarizeBy: sum
		sourceColumn: tax_rate

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: f2a3c3e9-9752-42f4-97b2-8bbc8c594f49
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column currency_code
		dataType: string
		lineageTag: f3300523-7cdc-48fa-8dda-bc81304abb62
		summarizeBy: none
		sourceColumn: currency_code

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: c1c9386c-9fd7-440e-9432-7350fa6e12ff
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 5d1d9691-2fd3-4d39-97bb-e9e318593b69
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: 7ec6716f-d452-46d0-a106-0a92a8c4a765
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column promotion_code
		dataType: string
		lineageTag: 611c5545-e6d3-43e2-adc7-cce7b530b490
		summarizeBy: none
		sourceColumn: promotion_code

		annotation SummarizationSetBy = Automatic

	column is_returned
		dataType: boolean
		lineageTag: 831e9c65-3583-4e3b-b49d-6cbc8898db99
		summarizeBy: none
		sourceColumn: is_returned

		annotation SummarizationSetBy = Automatic

	column 'Days Since First Order' = DATEDIFF(CALCULATE(SELECTEDVALUE(dim_customer[first_order_date])), TODAY(), DAY)
		dataType: int64
		lineageTag: d6c1c9c7-0e88-4283-9143-1a771dc6e75b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER('fact_sales'[city]) & ", " & 'fact_sales'[state] & " (" & 'fact_sales'[country] & ")"
		dataType: string
		lineageTag: f5bb5729-d4d7-4e97-9009-8f01795cee22
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: df8bb598-e30c-4da8-aa26-2831007402e7
		summarizeBy: none
		sourceColumn: 'Discount Category'

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount'
		dataType: double
		formatString: #,0.00
		lineageTag: 6f7a1f85-e6e0-4f30-99a2-18a47d6f1d51
		summarizeBy: none
		sourceColumn: 'Safe Discount'

		annotation SummarizationSetBy = Automatic

	partition 'fact_sales-43af1857-b887-4d0b-884a-a90ad1b47adc' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"sale_id", "date_key", "customer_key", "product_key", "store_key", "channel", "region", "territory", "country", "state", "city", "postal_code", "latitude", "longitude", "quantity", "unit_price", "unit_cost", "discount_pct", "tax_rate", "shipping_cost", "currency_code", "order_status", "payment_method", "sales_rep", "promotion_code", "is_returned"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"fact_sales Table" = #"SALES"{[Name="fact_sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"fact_sales Table", {{"sale_id", "Sale ID"}, {"channel", "Channel"}, {"region", "Region"}, {"territory", "Territory"}, {"country", "Country"}, {"state", "State"}, {"city", "City"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"unit_cost", "Unit Cost"}, {"discount_pct", "Discount %"}, {"tax_rate", "Tax Rate"}, {"shipping_cost", "Shipping Cost"}, {"currency_code", "Currency"}, {"order_status", "Order Status"}, {"payment_method", "Payment Method"}, {"sales_rep", "Sales Rep"}, {"promotion_code", "Promotion Code"}, {"is_returned", "Returned?"}}),
				    #"Added Discount Category" = Table.AddColumn(#"Renamed Columns", "Discount Category", each /* TODO: DAX conversion validation failed for C_DiscCat: invalid literal token detected in DAX output */ null, type text),
				    #"Added Safe Discount" = Table.AddColumn(#"Added Discount Category", "Safe Discount", each if ([discount_pct] = null) then 0 else [discount_pct], type number),
				    Result = #"Added Safe Discount"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 30 columns and 31 measures: sale_id, date_key, customer_key, product_key, store_key, channel, region, territory, ... (30 columns total).

