table 'Target Margin %'
	lineageTag: d881952c-4712-4494-91e3-195878b307e4

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: dba102f3-75b4-4a4f-98da-8253ee9b8c44
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)

	column Value
		dataType: double
		lineageTag: 89514f75-1719-4556-937e-0897428f5be5
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-9c0d59ea-6011-49cd-b9d3-c89de7497b86' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

