table 'Top N Items'
	lineageTag: f8423849-b6df-4a14-9bf8-8f410e04c951

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: bc3c5739-bff4-4276-922e-457a6bdeeb3c
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Items'[Value], 15)

	column Value
		dataType: int64
		lineageTag: 216e0a5d-ef96-48d0-b005-f3004094524f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-97652073-6094-489b-9b62-707e591dedb3' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

