table Calendar
	lineageTag: 322dfbf8-f147-4287-b3b4-6207052a7cb1

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f3ece13e-d734-4ad8-ba3e-7d398d028f3b
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 4c788897-7f85-468a-870c-3d0591aef1af
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 3d0c7f2a-89b6-4406-b031-f7bf6477d8dc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 63add92c-22be-458f-acc3-1b89a42cb59b
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c6c05813-94d4-4ded-ae5c-4ff3dfd3a1c4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e2f6d13e-df83-49ed-aee9-cfea756e7cdb
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2a1a582e-f5ca-4039-9acd-c0761b1b598e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fe94b9d6-2e19-4263-a7fe-3d3a3b164b68
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 08c9f5f5-b0e2-4346-badd-d16df2716fe6

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3f7cae54-8632-40a4-9dce-daa2d8ab118a

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 45eebabf-c79b-4a5f-9ac1-bdfb91b7cd58

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 4c7be440-28e5-41f2-b2fd-c05f0492c1e4

		level Day
			ordinal: 3
			column: Day
			lineageTag: 95521f0a-cd80-42a5-aa03-b73581002840


	partition 'Calendar-c4ba2956-7d81-4b86-bfb7-e2335344f90b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

