table Extract
	lineageTag: 8f7967f1-110e-4651-b17a-f1e7b54c0895

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 13f7c3c9-549d-44ef-97da-e041bfd6cd3b
		annotation Copilot_Description = Migrated from Tableau: AVG([F: GDP per capita (curr $)]) / TOTAL(AVG([F: GDP per capita (curr $)])) | DAX: AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8317b070-6f3e-4fb6-b7b1-7ccd5bc2c3b9
		annotation Copilot_Description = Migrated from Tableau: SUM([F: GDP (curr $)]) / SUM([P: Population (count)]) | DAX: SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0f588e56-c8ba-41e8-b1b5-249368e15ad0
		annotation Copilot_Description = Migrated from Tableau: AVG([F: Lending interest rate (%)])-AVG([F: Deposit interest rate (%)]) | DAX: AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: 4f50f2c8-2138-4a98-b25c-1ccf2179aeba
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	measure 'GDP per capita (weighted) Formatted' = VAR _val = [GDP per capita (weighted)] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 0d0b2e91-4d26-456d-990a-2848613bccbf
		annotation Copilot_Description = Dynamic numeric abbreviation for GDP per capita (weighted) (K/M/B)

	column 'Country / Region'
		dataType: string
		lineageTag: 0ec14881-2844-4fdd-9415-044c720f9c8b
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: d8e5b70a-064b-4702-a322-39161134dec5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 9286b9bf-3c52-4fdc-bb01-6bf96cf0e5cb
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 6ada5a63-8125-4fb1-9dd0-79e443b17184
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: eb140370-ade1-420c-960a-49f0d0a2111e
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 4c990598-be7c-4df7-aa6c-71025d10c94e
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: 19c726d1-ed5d-4d3c-8421-2413e7fa0f4b
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: 65277fea-dda8-4977-845b-83807b6125ee
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: 13b1f587-585f-498e-949c-747ecff42ef9
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 4291ff57-1c11-496f-b74c-fe71e1c54cda
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: a47ea39a-668a-4c6e-abe5-d1ad691dca5e
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3931a27f-8e5a-48f4-bd85-a93ecc8699eb
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: b60ad3c8-f127-478d-a258-fc14aeba181d
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)'
		dataType: string
		lineageTag: db354ff4-60fa-4d2f-8d57-f7b598f139f2
		summarizeBy: none
		sourceColumn: 'Action (Country Name)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))'
		dataType: string
		lineageTag: 55d3f7d1-2fa5-4ca3-801b-b87a31c8538d
		summarizeBy: none
		sourceColumn: 'Action (Date (year))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: fa9c6910-5c46-4c98-b857-3e6ccda6f53a
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))'
		dataType: string
		lineageTag: d6f8d9d5-ec59-4b08-a475-38162351a7b1
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))'
		dataType: string
		lineageTag: 5413de87-29ac-439b-b4de-4fdae8b62f85
		summarizeBy: none
		sourceColumn: 'Exclusions (Country Name,YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-590f5470-a6f7-4e12-9452-92a4bfc2a16b' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"},
				            {
				                {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"},
				                {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Sample 13", "Sample 14"}
				            }
				        )
				    otherwise
				        #table({"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    #"Added Action (Country Name)" = Table.AddColumn(#"Renamed Columns", "Action (Country Name)", each Text.From([#"Country / Region"]), type text),
				    #"Added Action (Date (year))" = Table.AddColumn(#"Added Action (Country Name)", "Action (Date (year))", each Text.From([#"Date"]), type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Action (Date (year))", "Action (Region)", each Text.From([#"Region"]), type text),
				    #"Added Action (YEAR(Date (year)))" = Table.AddColumn(#"Added Action (Region)", "Action (YEAR(Date (year)))", each Text.From(Date.Year([#"Date"])), type text),
				    #"Added Exclusions (Country Name,YEAR(Date (year)))" = Table.AddColumn(#"Added Action (YEAR(Date (year)))", "Exclusions (Country Name,YEAR(Date (year)))", each Text.From([#"Country / Region"]) & " | " & Text.From(Date.Year([#"Date"])), type text),
				    Result = #"Added Exclusions (Country Name,YEAR(Date (year)))"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 18 columns and 5 measures: Country / Region, Date, F: Deposit interest rate (%), F: GDP (curr $), F: GDP per capita (curr $), F: Lending interest rate (%), H: Health exp (% GDP), H: Health exp/cap (curr $), ... (18 columns total).

