table Calendar
	lineageTag: bb355475-a0c7-4734-8728-8f9c61116aef

	measure 'Year To Date' = TOTALYTD([Is My Account], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: d001944b-f683-49da-ac0a-dc27334f4e6b
		annotation Copilot_Description = DAX: TOTALYTD([Is My Account], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Is My Account], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 09a20a9d-848d-41ba-a2c8-1ec2f58b9093
		annotation Copilot_Description = DAX: CALCULATE([Is My Account], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 1670699c-e31d-41f1-8cd0-f5aaaf387006
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3641284d-08f7-40dd-9d07-cf9503f386ff
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: e3a356c5-930f-4926-870d-a057cadaa0cd
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 0bc74b5d-c3d7-4502-8070-aef8da83d10a
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 1d047ac2-f05b-4f01-8381-a561a57c1aef
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: eeb90df2-e460-4164-a452-8f2a497e7979
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 315e68b5-7376-4c79-a099-2ebacf2d3686
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: c46a22c7-6c1d-4942-85a7-39b33dea9263
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: fb974793-e76d-4dc7-a336-6361b0b8f4ff
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: c7ce3daf-e008-48c5-b09f-f033b29d08dc

		level Year
			ordinal: 0
			column: Year
			lineageTag: 44ec5793-71ca-46f6-b879-e648877e70b9

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 5e8bd87d-b444-43d1-9e7c-a2e491d7f7a9

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3629577b-3f62-4cde-944f-93b90b2b41ac

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5704c473-f9c1-4a67-a1f6-a5012e09163d


	partition 'Calendar-fdfa1a4b-ad2a-4e55-9b41-9e085d7d2afe' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

