table Customers
	lineageTag: 5c2cabf0-0dcf-4886-95bc-bb0baf984d58

	column customer_id
		dataType: int64
		lineageTag: 925c2a92-f9ab-40b1-91f0-95552f906e67
		summarizeBy: sum
		sourceColumn: customer_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 6df23ed8-7f89-4c58-8c55-1dfac8b96380
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: c761979d-6e97-4c53-8547-6155ab0def79
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 84d8c84f-a358-450d-aa90-c32ff82a0da7
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: bd17626b-ebf2-456a-a511-28c0eecbb5bd
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 02859717-bd07-4492-b1ec-9a2ca6d20f13
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: d135feb4-1371-4464-9af2-a920e54f5cb4
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: de5eedc0-caa2-4616-8f76-3bca02d4f16d
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 837eb8c3-0e0e-46db-9178-88a28f9c35f5
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: a81e372b-8f57-4039-a3fa-3f2f1cbc66d7
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: aabc145b-6292-4641-8e46-89298293b29e
		summarizeBy: none
		sourceColumn: first_purchase_date

		annotation SummarizationSetBy = Automatic

	partition 'Customers-e340d17f-7122-4e3c-b436-555b77548ea5' = m
		mode: import
		source =
				let
				    // Source Snowflake: acme.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH"),
				
				            _nav = _src{[Name="ANALYTICS"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_id", "customer_name", "segment", "city", "state", "country", "postal_code", "latitude", "longitude", "customer_email", "first_purchase_date"}, {}),
				    #"PUBLIC" = Source{[Name="PUBLIC"]}[Data],
				    #"Customers Table" = #"PUBLIC"{[Name="Customers"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Customers Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"segment", "Segment"}, {"city", "City"}, {"state", "State"}, {"country", "Country"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"customer_email", "Customer Email"}, {"first_purchase_date", "First Purchase Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 11 columns: customer_id, customer_name, segment, city, state, country, postal_code, latitude, ... (11 columns total).

