table 'Target Margin'
	lineageTag: 2f5ba74d-0f64-408e-a912-3c6a70ea9b74

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 91637c3f-220e-4d2d-a873-461cfd0df1a8
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin'[Value], 0.2)

	column Value
		dataType: double
		lineageTag: 6a3edbaa-2858-4b04-8d04-a55838919647
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-ccb7bd38-6898-47f1-926d-8b5d96a95cd8' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

