table 'Top N'
	lineageTag: c6e085fb-e128-41b7-b268-52aef36d2064

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 25ba22fe-7d47-4a97-86ec-9d3a029326fd
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N'[Value], 10)

	column Value
		dataType: int64
		lineageTag: 1bdcce2f-fff7-4889-9987-e086b7fe3b3b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N-dfd707e7-5c30-441e-ac5f-cad0ce324509' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

