table dim_product
	lineageTag: 9ee39aa3-ca92-45ba-8530-b01ffd6f48cf

	column product_key
		dataType: int64
		lineageTag: 113ec421-fed5-4975-ab26-9b20d1293a4b
		summarizeBy: sum
		sourceColumn: product_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 979afab3-0164-4fb5-9b48-42dc4b12211b
		summarizeBy: none
		sourceColumn: product_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 01c0ddd5-c9d8-47c3-bd49-4ee09b689391
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 999bff23-a7bd-46df-9410-a62bf64d2381
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: 06b1d47b-e15d-4d8c-9adb-a407b66b1ecf
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: a036b9b3-1fd4-4f23-b374-918ed6d6fd6c
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: f7c86839-83e6-4ce0-bcd6-a072d95acc4a
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: 2f53e2fc-4b4c-45cb-ad98-3fd213ec0921
		summarizeBy: sum
		sourceColumn: weight_kg

		annotation SummarizationSetBy = Automatic

	column is_perishable
		dataType: boolean
		lineageTag: f7a975d4-c59e-4cf0-bacc-87e2d57b6971
		summarizeBy: none
		sourceColumn: is_perishable

		annotation SummarizationSetBy = Automatic

	column launch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 55865b06-facf-4b46-a668-4a3272521fde
		summarizeBy: none
		sourceColumn: launch_date

		annotation SummarizationSetBy = Automatic

	partition 'dim_product-d92ea5c0-e1ff-4e57-9617-6e3bd2cf6c5e' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"product_key", "product_id", "product_name", "category", "subcategory", "brand", "supplier", "weight_kg", "is_perishable", "launch_date"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_product Table" = #"SALES"{[Name="dim_product"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_product Table", {{"product_id", "Product ID"}, {"product_name", "Product Name"}, {"category", "Category"}, {"subcategory", "Subcategory"}, {"brand", "Brand"}, {"supplier", "Supplier"}, {"weight_kg", "Weight (kg)"}, {"is_perishable", "Perishable?"}, {"launch_date", "Launch Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

