table dim_customer
	lineageTag: 0111698f-0618-4e6a-bb73-3c75a0a70966

	column customer_key
		dataType: int64
		lineageTag: 3116ccab-6379-4713-8b24-6bfcf4f063b9
		summarizeBy: sum
		sourceColumn: customer_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: db95446c-513b-4f00-b39c-6349e1eff473
		summarizeBy: none
		sourceColumn: customer_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 3df048c2-b5d7-4941-a6fe-b389f6bdd77f
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 2711bac2-ab66-473a-9bd4-6141cbdb3a93
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 2220bf13-40ad-49d7-90cf-06d109da954e
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 0e9218f7-dd38-4966-a147-9db61e552e48
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: c2e949fe-4574-4c25-82b1-857257c980b2
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column company_size
		dataType: string
		lineageTag: b5d32220-cef9-4400-b64b-9b69101a08af
		summarizeBy: none
		sourceColumn: company_size

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 348b6f3f-c0c1-4931-954d-25a72c5327b5
		summarizeBy: none
		sourceColumn: first_order_date

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		formatString: #,0.00
		lineageTag: fbe4aaed-bf56-4559-b037-e1f576fd9d74
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

	column account_manager
		dataType: string
		lineageTag: 0f3262f5-c760-432c-bf36-a3670674cea8
		summarizeBy: none
		sourceColumn: account_manager

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		lineageTag: 9bd4f2aa-a44b-4a22-942c-bc08c0838fc9
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	partition 'dim_customer-83f2df8b-cc3b-4412-a013-7d47c6626a4b' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"customer_key", "customer_id", "customer_name", "email", "phone", "segment", "industry", "company_size", "first_order_date", "credit_limit", "account_manager", "is_active"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_customer Table" = #"SALES"{[Name="dim_customer"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_customer Table", {{"customer_id", "Customer ID"}, {"customer_name", "Customer Name"}, {"email", "Email"}, {"phone", "Phone"}, {"segment", "Segment"}, {"industry", "Industry"}, {"company_size", "Company Size"}, {"first_order_date", "First Order"}, {"credit_limit", "Credit Limit"}, {"account_manager", "Account Manager"}, {"is_active", "Active?"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: customer_key, customer_id, customer_name, email, phone, segment, industry, company_size, ... (12 columns total).

