table dim_date
	lineageTag: 2716c6fa-9604-4a54-9caf-a1b7389b3194

	column date_key
		dataType: int64
		lineageTag: 9495a852-fec4-45ac-b06d-648947e262b5
		summarizeBy: sum
		sourceColumn: date_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 237a75c3-0a36-4178-aa29-3e93abf4f26e
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: 2b210965-1de7-4ea9-9abc-2eaac7cbe8dd
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: 3eac1460-4467-4cee-92ab-eee73a097380
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		lineageTag: ecedcf0b-2f6f-4d1f-ad12-0e63bd02f094
		summarizeBy: sum
		sourceColumn: month_num

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 59438244-ffb3-4b75-880e-b2a9e3238973
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column week_num
		dataType: int64
		lineageTag: 12b1fc93-ffa1-41eb-9d79-c6e39eba048d
		summarizeBy: sum
		sourceColumn: week_num

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 450f29f6-4e53-4e5f-8be1-3c0b54a67e67
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: 32dace67-2c21-4964-a9af-45f59bbb0a1e
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: boolean
		lineageTag: deb5d0f0-1b2d-4673-a627-3cf4732b5824
		summarizeBy: none
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: string
		lineageTag: 56fc80bf-22ad-4344-a655-dfbda0ee390d
		summarizeBy: none
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		lineageTag: e1b981d5-c3a9-4971-9d3e-b8a25b9b566b
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	partition 'dim_date-86f54d71-4094-4bf6-8c39-9117d6840acf' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"date_key", "full_date", "year", "quarter", "month_num", "month_name", "week_num", "day_name", "is_weekend", "is_holiday", "fiscal_quarter", "fiscal_year"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_date Table" = #"SALES"{[Name="dim_date"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_date Table", {{"full_date", "Full Date"}, {"year", "Year"}, {"quarter", "Quarter"}, {"month_num", "Month"}, {"month_name", "Month Name"}, {"week_num", "Week"}, {"day_name", "Day Name"}, {"is_weekend", "Weekend?"}, {"is_holiday", "Holiday?"}, {"fiscal_quarter", "Fiscal Quarter"}, {"fiscal_year", "Fiscal Year"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: date_key, full_date, year, quarter, month_num, month_name, week_num, day_name, ... (12 columns total).

