table fact_sales
	lineageTag: f95bd6fe-a97f-4ce4-aff1-08a3020dbf46

	measure 'Gross Revenue' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 31291d78-48ff-485e-befd-fc2bd87e9f9d
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])

	measure 'Net Revenue' = SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a0332019-1272-4321-b3b8-566c9c6cd491
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [order_status] != "Cancelled" AND [is_returned] = FALSE THEN [quantity] * [unit_price] * (1 - [discount_pct]) ELSE 0 END) | DAX: SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))

	measure COGS = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 49d4c70c-bba9-4947-9822-aca04b2f2bb4
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_cost]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])

	measure 'Gross Profit' = [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d1457ec9-91aa-4173-ab1a-e0a7c8ef7e5a
		annotation Copilot_Description = Migrated from Tableau: [C_NetRev] - [C_COGS] - SUM([shipping_cost]) | DAX: [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])

	measure 'Gross Margin %' = IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9c758a31-0784-472a-b7f5-7d7bced15cb5
		annotation Copilot_Description = Migrated from Tableau: ZN([C_GrossProfit] / [C_NetRev]) | DAX: IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])

	measure 'Tax Amount' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 46b8661f-555a-4922-8749-2035cece2966
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price] * (1 - [discount_pct]) * [tax_rate]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])

	measure 'Total Revenue incl Tax' = [Net Revenue] + [Tax Amount]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 99676e45-45d5-4778-8d99-c87ff1840c28
		annotation Copilot_Description = Migrated from Tableau: [C_NetRev] + [C_TaxAmt] | DAX: [Net Revenue] + [Tax Amount]

	measure 'Return Rate' = SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8b837e54-99eb-4a8f-b2cd-5d3ec7c89411
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [is_returned] = TRUE THEN 1 ELSE 0 END) / COUNT([sale_id]) | DAX: SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])

	measure 'Revenue per Customer' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3a264b17-df8e-44e9-b94a-2b2b11a37615
		annotation Copilot_Description = Migrated from Tableau: {FIXED [customer_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))

	measure 'Revenue per Product' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 47a2c9de-028f-48e5-a95b-2e3f03c0339a
		annotation Copilot_Description = Migrated from Tableau: {FIXED [product_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))

	measure 'Revenue by Region-Channel' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: eeed6852-0155-4a69-94db-cc00a36382bb
		annotation Copilot_Description = Migrated from Tableau: {FIXED [region], [channel] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))

	measure 'Revenue excl Territory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c8059e17-8236-4c4a-b5bf-91f2f0a49ca0
		annotation Copilot_Description = Migrated from Tableau: {EXCLUDE [territory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))

	measure 'Revenue incl Subcategory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a0ce482f-76f3-4775-b83d-4639c2de09ed
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [subcategory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))

	measure 'Running Total Revenue' = /* TODO: DAX conversion validation failed for C_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3fceb27b-b8df-4872-817e-a5de05a165a0
		annotation Copilot_Description = Migrated from Tableau: RUNNING_SUM(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for C_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Avg Revenue' = /* TODO: DAX conversion validation failed for C_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ae19cf71-0d60-4080-a72a-8a223461f927
		annotation Copilot_Description = Migrated from Tableau: RUNNING_AVG(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for C_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Count' = /* TODO: DAX conversion validation failed for C_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: 3f5cae8d-7b7e-4693-b504-b95a5f4deb5a
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(SUM([quantity])) | DAX: /* TODO: DAX conversion validation failed for C_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Revenue Rank' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		displayFolder: Measures
		lineageTag: 70de887d-3b6e-4dc0-b3d3-1962a8150fd8
		annotation Copilot_Description = Migrated from Tableau: RANK(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))

	measure 'Revenue Rank Dense' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: 2e6d7d94-d5e2-4778-8074-5414b41e4402
		annotation Copilot_Description = Migrated from Tableau: RANK_DENSE(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)

	measure 'Moving Avg 3-Period' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('fact_sales'[sale_id]), ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame SUM('fact_sales'[-2,0]) */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ee99db20-e531-4620-92bb-d9f43ee1cc87
		annotation Copilot_Description = Migrated from Tableau: WINDOW_AVG(SUM([quantity] * [unit_price]), -2, 0) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('fact_sales'[sale_id]), ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame SUM('fact_sa)...

	measure 'Window Max Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9dd3d5af-da25-4567-a9a1-6aa7af48acdb
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MAX(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))

	measure 'Revenue StdDev' = STDEVX.S('fact_sales', MAX('fact_sales'[quantity]) * MAX('fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9aebc254-a409-4844-b3f5-ac42f6ef8c34
		annotation Copilot_Description = Migrated from Tableau: STDEV(SUM([quantity] * [unit_price])) | DAX: STDEVX.S('fact_sales', MAX('fact_sales'[quantity]) * MAX('fact_sales'[unit_price]))

	measure 'Order Count' = DISTINCTCOUNT('fact_sales'[sale_id])
		displayFolder: Measures
		lineageTag: 815b0c8d-552e-4885-9a76-2e024bb14e44
		annotation Copilot_Description = Migrated from Tableau: COUNTD([sale_id]) | DAX: DISTINCTCOUNT('fact_sales'[sale_id])

	measure 'Unique Customers' = DISTINCTCOUNT('dim_customer'[customer_id])
		displayFolder: Measures
		lineageTag: 0b2bd676-e031-4005-a15e-41fa9330664a
		annotation Copilot_Description = Migrated from Tableau: COUNTD([customer_id]) | DAX: DISTINCTCOUNT('dim_customer'[customer_id])

	measure 'Unique Products Sold' = DISTINCTCOUNT('dim_product'[product_id])
		displayFolder: Measures
		lineageTag: ad6dd878-0c50-489b-a8a7-11bf6a0cb84a
		annotation Copilot_Description = Migrated from Tableau: COUNTD([product_id]) | DAX: DISTINCTCOUNT('dim_product'[product_id])

	measure 'Customer Tier' = IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))
		displayFolder: Dimensions
		lineageTag: 760a0861-8dae-49b7-8c22-7862b3da2742
		annotation Copilot_Description = Migrated from Tableau: IF [C_RevPerCust] > 100000 THEN "Enterprise" ELSEIF [C_RevPerCust] > 50000 THEN "Mid-Market" ELSEIF [C_RevPerCust] > 10000 THEN "SMB" ELSE "Startup" END | DAX: IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))

	measure 'YTD Revenue' = CALCULATE(SUMX('dim_date', IF('dim_date'[year] = YEAR(TODAY()) && LOOKUPVALUE(fact_sales[is_returned], fact_sales[date_key], dim_date[date_key]) = FALSE, LOOKUPVALUE(fact_sales[quantity], fact_sales[date_key], dim_date[date_key]) * LOOKUPVALUE(fact_sales[unit_price], fact_sales[date_key], dim_date[date_key]), 0)), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8f093c14-1c7c-4d07-836f-4356b7c2f8f8
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF [year] = YEAR(TODAY()) AND [is_returned] = FALSE THEN [quantity] * [unit_price] ELSE 0 END)} | DAX: CALCULATE(SUMX('dim_date', IF('dim_date'[year] = YEAR(TODAY()) && LOOKUPVALUE(fact_sales[is_returned], fact_sales[date_key], dim_date[date_key]) = FALSE, LOOKUPVALUE(fact_sales[quantity], fact_sales[d]))))...

	measure 'Is My Account' = SUM('dim_customer'[email]) = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 5f579111-d3f6-44d2-b72f-86c658c75659
		annotation Copilot_Description = Migrated from Tableau: [email] = USERNAME() | DAX: SUM('dim_customer'[email]) = USERPRINCIPALNAME()

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: be442e98-8077-4f6b-abde-385a2aedd39b
		annotation Copilot_Description = Migrated from Tableau: ISMEMBEROF("Regional Managers") | DAX: TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */

	measure 'Analysis Start Date' = DATE(2024, 1, 1)
		lineageTag: 5c5d7a45-4498-4fb1-895d-81687fc51ffe
		annotation Copilot_Description = DAX: DATE(2024, 1, 1)

	measure 'Metric Selector' = "Revenue"
		lineageTag: a4ad8d43-d6f6-48f8-a093-a6dd4d97d916
		annotation Copilot_Description = DAX: "Revenue"

	measure 'Display Currency' = "USD"
		lineageTag: 83d2b083-0caf-4f3b-98d0-9fab0820d6ba
		annotation Copilot_Description = DAX: "USD"

	measure 'Gross Revenue Formatted' = VAR _val = [Gross Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 93ffe819-3b30-4875-ae7e-55e39853caa3
		annotation Copilot_Description = Dynamic numeric abbreviation for Gross Revenue (K/M/B)

	measure 'Net Revenue Formatted' = VAR _val = [Net Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 06407e0c-6e4c-45c5-8cca-968bb2d012b1
		annotation Copilot_Description = Dynamic numeric abbreviation for Net Revenue (K/M/B)

	measure 'COGS Formatted' = VAR _val = [COGS] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: d9da9387-9db3-43d8-bce0-0369ca580ba5
		annotation Copilot_Description = Dynamic numeric abbreviation for COGS (K/M/B)

	measure 'Gross Profit Formatted' = VAR _val = [Gross Profit] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 476f91a5-c934-4843-8554-f9af4680929e
		annotation Copilot_Description = Dynamic numeric abbreviation for Gross Profit (K/M/B)

	measure 'Tax Amount Formatted' = VAR _val = [Tax Amount] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 3b46889c-a720-493c-8c90-0f63b82c251b
		annotation Copilot_Description = Dynamic numeric abbreviation for Tax Amount (K/M/B)

	measure 'Return Rate Formatted' = VAR _val = [Return Rate] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 88a28948-fff8-4c49-886d-9ef94b628729
		annotation Copilot_Description = Dynamic numeric abbreviation for Return Rate (K/M/B)

	measure 'Revenue per Customer Formatted' = VAR _val = [Revenue per Customer] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 4a8e5fe7-99da-452d-a554-8e6b4dffd94d
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue per Customer (K/M/B)

	measure 'Revenue per Product Formatted' = VAR _val = [Revenue per Product] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 23642bc8-b671-4f2f-90d2-3161f4d519c3
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue per Product (K/M/B)

	measure 'Revenue by Region-Channel Formatted' = VAR _val = [Revenue by Region-Channel] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 9069421e-f99d-46ec-8e03-0200e3ec0ea6
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue by Region-Channel (K/M/B)

	measure 'Revenue excl Territory Formatted' = VAR _val = [Revenue excl Territory] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: a217568b-afe4-49fc-b62b-cee9f1a1353b
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue excl Territory (K/M/B)

	measure 'Revenue incl Subcategory Formatted' = VAR _val = [Revenue incl Subcategory] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 5f42fd7e-90a2-4b95-9bee-7f33c03e4282
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue incl Subcategory (K/M/B)

	measure 'Revenue Rank Formatted' = VAR _val = [Revenue Rank] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: 2475bfdb-c566-49b5-bbff-196883806e31
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue Rank (K/M/B)

	measure 'Revenue Rank Dense Formatted' = VAR _val = [Revenue Rank Dense] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: b8211567-6ca4-4abb-a64f-6d0d925576b1
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue Rank Dense (K/M/B)

	measure 'Moving Avg 3-Period Formatted' = VAR _val = [Moving Avg 3-Period] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 50063991-35b8-482c-ad26-a355630eb500
		annotation Copilot_Description = Dynamic numeric abbreviation for Moving Avg 3-Period (K/M/B)

	measure 'Window Max Revenue Formatted' = VAR _val = [Window Max Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 48192474-14a2-4446-a7ca-ee7ac3bd9fea
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Max Revenue (K/M/B)

	measure 'YTD Revenue Formatted' = VAR _val = [YTD Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: e673eac1-a80e-4515-be4b-414d0414a266
		annotation Copilot_Description = Dynamic numeric abbreviation for YTD Revenue (K/M/B)

	column sale_id
		dataType: int64
		lineageTag: cdeb981f-b649-4639-aca9-df66766e586e
		summarizeBy: sum
		sourceColumn: sale_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		lineageTag: 0084f5bd-cc01-4939-a68b-7b4190809b04
		summarizeBy: sum
		sourceColumn: date_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		lineageTag: 7d77e03c-0cbd-405b-be8f-861668bff19f
		summarizeBy: sum
		sourceColumn: customer_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		lineageTag: 31c59f26-f017-45d9-b670-653a9057f729
		summarizeBy: sum
		sourceColumn: product_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		lineageTag: 359c5877-382b-441e-b885-c6954fd160ff
		summarizeBy: sum
		sourceColumn: store_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 77cd6f9e-9899-43b0-b49d-8c4d475079e8
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 52cb8303-070d-4310-96f0-61068be9eb2c
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: a44d91af-7d26-4e52-af82-350b855683a8
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 14e27566-e985-44b5-97d2-fbda139bd4eb
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 538e4ecb-bf6a-4cbd-9da5-f5282d7c80ca
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 2da17de5-54ca-4350-a070-f65db4ec77fb
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: c62033e8-7fd9-44e7-9f73-8d6c8523915a
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: db92f59d-001a-4176-91c8-c8c25903cbc9
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 43184753-1bb7-44e0-8abe-fabea857fa61
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: a4a01eef-80eb-4728-87be-aeb3bb54258d
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: d8c59cf7-1570-4280-aa34-0f3b023ce7e2
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 9dd369d2-8804-4170-bb69-c75b1d26699e
		summarizeBy: sum
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column discount_pct
		dataType: double
		formatString: #,0.00
		lineageTag: d687d4c7-7912-4aed-a59b-4542f5597e58
		summarizeBy: sum
		sourceColumn: discount_pct

		annotation SummarizationSetBy = Automatic

	column tax_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 1de304bf-5025-4526-82e0-84df2febd912
		summarizeBy: sum
		sourceColumn: tax_rate

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: fd1f186c-7b7b-457e-880b-19726fe12253
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column currency_code
		dataType: string
		lineageTag: 0ec6dd02-3420-4b32-9e47-0a66d8b4f740
		summarizeBy: none
		sourceColumn: currency_code

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: a0cc867d-ac2f-4cb7-8a8a-a934facb74dd
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 374eae1c-5b78-46a2-88d1-0a04367d74b8
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: 8a46244d-96b3-48a7-ac1f-de585b924412
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column promotion_code
		dataType: string
		lineageTag: ff04ba7b-cff5-4869-9300-31961d501f14
		summarizeBy: none
		sourceColumn: promotion_code

		annotation SummarizationSetBy = Automatic

	column is_returned
		dataType: boolean
		lineageTag: fe42a0c1-dc7f-42f5-920f-21faa01fe976
		summarizeBy: none
		sourceColumn: is_returned

		annotation SummarizationSetBy = Automatic

	column 'Days Since First Order' = DATEDIFF(CALCULATE(SELECTEDVALUE(dim_customer[first_order_date])), TODAY(), DAY)
		dataType: int64
		lineageTag: cae02eff-23ac-4b2a-8850-048e3d88d57f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER('fact_sales'[city]) & ", " & 'fact_sales'[state] & " (" & 'fact_sales'[country] & ")"
		dataType: string
		lineageTag: eedb9957-9785-481f-b0eb-4297a2b70aa7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: 5c57e066-bb9c-4f1b-b316-9dd0b3dfc39e
		summarizeBy: none
		sourceColumn: 'Discount Category'

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount'
		dataType: double
		formatString: #,0.00
		lineageTag: 72515010-8be3-4547-bf23-daea16baf8d0
		summarizeBy: none
		sourceColumn: 'Safe Discount'

		annotation SummarizationSetBy = Automatic

	column '-2,0'
		dataType: string
		lineageTag: db85e22d-aa8d-4744-88f8-25d994139c71
		summarizeBy: none
		sourceColumn: '-2,0'
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing qualified reference 'fact_sales'[-2,0].

		annotation SummarizationSetBy = Automatic

	partition 'fact_sales-f4bda6bb-486f-424b-aa4e-68fd920bc65d' = m
		mode: import
		source =
				let
				    // Source Snowflake: analytics.snowflakecomputing.com
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"sale_id", "date_key", "customer_key", "product_key", "store_key", "channel", "region", "territory", "country", "state", "city", "postal_code", "latitude", "longitude", "quantity", "unit_price", "unit_cost", "discount_pct", "tax_rate", "shipping_cost", "currency_code", "order_status", "payment_method", "sales_rep", "promotion_code", "is_returned"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"fact_sales Table" = #"SALES"{[Name="fact_sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"fact_sales Table", {{"sale_id", "Sale ID"}, {"channel", "Channel"}, {"region", "Region"}, {"territory", "Territory"}, {"country", "Country"}, {"state", "State"}, {"city", "City"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"unit_cost", "Unit Cost"}, {"discount_pct", "Discount %"}, {"tax_rate", "Tax Rate"}, {"shipping_cost", "Shipping Cost"}, {"currency_code", "Currency"}, {"order_status", "Order Status"}, {"payment_method", "Payment Method"}, {"sales_rep", "Sales Rep"}, {"promotion_code", "Promotion Code"}, {"is_returned", "Returned?"}}),
				    #"Added Discount Category" = Table.AddColumn(#"Renamed Columns", "Discount Category", each /* TODO: DAX conversion validation failed for C_DiscCat: invalid literal token detected in DAX output */ null, type text),
				    #"Added Safe Discount" = Table.AddColumn(#"Added Discount Category", "Safe Discount", each if ([discount_pct] = null) then 0 else [discount_pct], type number),
				    Result = #"Added Safe Discount"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 31 columns and 47 measures: sale_id, date_key, customer_key, product_key, store_key, channel, region, territory, ... (31 columns total).

