table 'Target Margin %'
	lineageTag: 84aa990f-3e9a-4a7f-8604-e4a819715c37

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: db4a0afa-ee90-4536-88ab-0b29e76c6573
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)

	column Value
		dataType: double
		lineageTag: 7ca832aa-3123-476d-a6f2-8f14e07a8c42
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-8d2dd6e7-76f6-4fcb-90b1-4024d0929db3' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

