table 'Top N Items'
	lineageTag: 020491c4-c606-418a-8fd2-f334dd3380ec

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 844b8714-f989-42e5-94c0-3b3441f7e5be
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Items'[Value], 15)

	column Value
		dataType: int64
		lineageTag: b0fab31d-7e40-44a8-9482-3a7720bf8bc3
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-634d9ebb-6194-4764-b0c3-06c43c22ea93' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

