expression DataFolder = "C:\\Users\\pidoudet\\OneDrive - Microsoft\\Boulot\\PBI SME\\OracleToPostgre\\TableauToPowerBI\\artifacts\\bug_bash\\HR_Analytics\\Data" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression ServerName = "localhost" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression DatabaseName = "HRDatabase" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]