table Calendar
	lineageTag: eeb8b99e-277d-4bc1-8fc5-23c65f75752a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 2987451f-0de0-44fa-843a-17c28db1592b
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0435c723-d696-419f-ac97-823cdbe693e9
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4a324439-3aaf-42b2-904b-d4f7c69b11c9
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 3a217f88-d182-43b5-b2b7-73d84d5c10ff
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5ccbac6d-d9ad-433c-8833-0c32ad636ea9
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: ffa44dd9-189e-4aa8-ae08-8258442f1143
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 2625c1bf-aa58-4341-ba25-330d958ff05a
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 8cada8bb-bfa9-445a-8ccf-6cd6d22f21fc
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 41e577ea-18ed-4989-a748-46b2a2db74e9

		level Year
			ordinal: 0
			column: Year
			lineageTag: 21c8c537-267f-4b7e-8e19-536731d61563

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: fad63758-7785-4e43-8b4a-a373c9e45cd5

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: ca2ebca1-7347-4c0a-bc95-64e1aff846fb

		level Day
			ordinal: 3
			column: Day
			lineageTag: ce42fcd7-2c38-4a57-a0a2-eeea5020c7c5


	partition 'Calendar-9c8c7e0e-7658-42ca-ad8c-1f709469a09c' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

