// DAX measures for table: Owned By
// Auto-generated by Tableau → Power BI migration

Avg Probability (Open Opp.) =
AVERAGEX('Owned By', IF('Owned By'[Is Open Opportunity?], 'Owned By'[_Avg Probability (Expression)], BLANK()))

Sales Cycle Won (Display) =
IF([Sales Cycle (won)] <= 30, FORMAT(ROUND([Sales Cycle (won)], 0), "0") & " d", IF([Sales Cycle (won)] <= 365, FORMAT(ROUND([Sales Cycle (won)]/30.25,1), "0") & " mo", FORMAT(ROUND([Sales Cycle (won)]/30.25,0), "0") & " mo"))

Days to Close (avg) =
AVERAGE('Owned By'[Days to Close])

One =
MAXX('Owned By', 1)

Pipeline Profile - Average Deal Size (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Average Deal Size (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Average Deal Size (num)])," ","☆")

First Time Closed Won by Account =
CALCULATE(MINX('Owned By', IF('Owned By'[Won Flag]="Y", 'Owned By'[Opportunity Close Date], BLANK())), ALLEXCEPT('Owned By', 'Owned By'[Account]))

Label DONE - Closed WON - Nb of Clients (Existing) =
[Label DONE - Closed WON - Nb of Clients] - [Label DONE - Closed WON - Nb of Clients (New)]

Probability (bucket) =
IF(SUM('Owned By'[_Avg Probability (Expression)]) < 0.25, "0-25%", IF(SUM('Owned By'[_Avg Probability (Expression)]) < 0.50, "25-50%", IF(SUM('Owned By'[_Avg Probability (Expression)]) < 0.75, "50-75%", "75-100%")))

Rank Sales Value (for selected Opp Owner) =
/* TODO: DAX conversion validation failed for Calculation_703968976541376514: unterminated double-quoted string literal */ BLANK()

Today =
DATE(2022,04,18)

Conversion Rate Average (for trends) =
/* TODO: DAX conversion validation failed for Calculation_928867483214106624: unconverted Tableau function token detected in DAX output */ BLANK()

Label FOCUS - Closing Overdue - Nb of Opp =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Overdue")) = "Closing Overdue")))

Total Sales for Existing Clients =
SUMX('Owned By', IF('Owned By'[Client/Prospect by Opportunity]="Existing Clients" && 'Owned By'[Is Last N months filter - Closed Date?], 'Owned By'[_Total Sales (Expression)], BLANK()))

Pipeline Profile - Pipeline Generation =
IF(MAX('Owned By'[_Per Customer: Pipeline Generation]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation]), ALL('Owned By'))/5, "1", IF(MAX('Owned By'[_Per Customer: Pipeline Generation]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation]), ALL('Owned By'))/5*2, "2", IF(MAX('Owned By'[_Per Customer: Pipeline Generation]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation]), ALL('Owned By'))/5*3, "3", IF(MAX('Owned By'[_Per Customer: Pipeline Generation]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation]), ALL('Owned By'))/5*4, "4", "5"))))

Label DONE - Closed WON - Nb of Opp =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag]="Y"))

Label DONE - Closed LOST - Nb of Accounts =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag] <> "Y"))

Label DONE - Closed LOST - Opp Amount =
SUMX('Owned By', IF((LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag] <> "Y", 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Label DONE - New - Nb of Opp =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("New")) = "New")))

Label DONE - Closed WON - Nb of Clients (New) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag]="Y" && 'Owned By'[Is First Time Client?]))

Label DONE - Closed WON - Nb of Clients =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag]="Y"))

Label DONE - Closed LOST - Nb of Opp =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag] <> "Y"))

Label DONE - Closed WON - Opp Amount =
SUMX('Owned By', IF((LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("Closed")) = "Closed") && 'Owned By'[Won Flag]="Y", 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Label DONE - New - Nb of Accounts (Prospect) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("New")) = "New") && 'Owned By'[Client/Prospect by Account]="Prospects"))

Label DONE - New - Nb of Accounts =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("New")) = "New")))

Label DONE - New - Opp Amount =
SUMX('Owned By', IF((LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("New")) = "New"), 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Label DONE - New - Nb of Accounts (Client) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - DONE - Cat 2], LEN("New")) = "New") && 'Owned By'[Client/Prospect by Account]="Existing Clients"))

Label FOCUS - Closing Next x days  - Nb of Accounts (Prospect) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Next")) = "Closing Next") && 'Owned By'[Client/Prospect by Account]="Prospects"))

Label FOCUS - Closing Next x days  - Nb of Accounts (Client) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Next")) = "Closing Next") && 'Owned By'[Client/Prospect by Account]="Existing Clients"))

Label FOCUS - Closing Next x days  - Nb of Accounts =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Next")) = "Closing Next")))

Label FOCUS - Closing Overdue - Nb of Accounts (Client) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Overdue")) = "Closing Overdue") && 'Owned By'[Client/Prospect by Account]="Existing Clients"))

Label FOCUS - Closing Overdue - Nb of Accounts (Prospect) =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Overdue")) = "Closing Overdue") && 'Owned By'[Client/Prospect by Account]="Prospects"))

Label FOCUS - Closing Overdue - Nb of Accounts =
CALCULATE(DISTINCTCOUNT('Owned By'[Account]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Overdue")) = "Closing Overdue")))

Label FOCUS - Closing Next x days  - Nb of Opp =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', (LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Next")) = "Closing Next")))

Label FOCUS - Closing Next x days - Opp Amount =
SUMX('Owned By', IF((LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Next")) = "Closing Next"), 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Label FOCUS - Closing Overdue - Opp Amount =
SUMX('Owned By', IF((LEFT('Owned By'[Pipeline Review - FOCUS - Cat 2], LEN("Closing Overdue")) = "Closing Overdue"), 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Pipeline Generated =
SUM('Owned By'[_Pipeline Generated (Expression)])

Nb of Owners =
DISTINCTCOUNT('Owned By'[Opportunity Owner])

Won/Lost Rate =
IF(ISBLANK([Nb of Won Opportunities]), 0, [Nb of Won Opportunities]) / IF(ISBLANK([Nb of Closed Opportunities]), 0, [Nb of Closed Opportunities])

Total Sales =
SUM('Owned By'[_Total Sales (Expression)])

Nb of Open Opportunities =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', 'Owned By'[Is Open Opportunity?]))

Nb of Won Opportunities =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', 'Owned By'[Is Won Opportunity?]))

Avg Deal Size (won) =
AVERAGE('Owned By'[_Avg Deal Size (won) (Expression)])

Sales Velocity =
(IF(ISBLANK([Nb of Open Opportunities]), 0, [Nb of Open Opportunities]) * IF(ISBLANK([Avg Deal Size (won)]), 0, [Avg Deal Size (won)]) * IF(ISBLANK('Owned By'[Won/Lost Rate]), 0, 'Owned By'[Won/Lost Rate])) / IF(ISBLANK([Sales Cycle]), 0, [Sales Cycle])

Sales Cycle =
AVERAGEX('Owned By', CONVERT(IF(NOT 'Owned By'[Is Open Opportunity?], DATEDIFF('Owned By'[CreatedDate (Owned By)], 'Owned By'[Opportunity Close Date], MINUTE) / (24*60), BLANK()), DOUBLE))

Avg Probability =
AVERAGE('Owned By'[_Avg Probability (Expression)])

Weighted Pipeline Value =
SUMX('Opportunities', CONVERT(IF(LOOKUPVALUE('Owned By'[Is Open Opportunity?], 'Owned By'[Id], Opportunities[OwnerId]), LOOKUPVALUE('Owned By'[Probability %], 'Owned By'[Id], Opportunities[OwnerId])*'Opportunities'[Amount], BLANK()), DOUBLE))

Nb of Opportunities =
DISTINCTCOUNT('Owned By'[Opportunity Id])

Total Closed Opportunities Amount =
SUM('Owned By'[_Total Closed Opportunities Amount (Expression)])

Conversion Rate =
IF(ISBLANK([Total Sales]), 0, [Total Sales]) / IF(ISBLANK([Total Closed Opportunities Amount]), 0, [Total Closed Opportunities Amount])

Pipeline Value =
SUMX('Opportunities', CONVERT(IF(LOOKUPVALUE('Owned By'[Is Open Opportunity?], 'Owned By'[Id], Opportunities[OwnerId]), 'Opportunities'[Amount], BLANK()), DOUBLE))

Sales Cycle (won) =
AVERAGEX('Owned By', CONVERT(IF('Owned By'[Is Won Opportunity?], DATEDIFF('Owned By'[CreatedDate (Owned By)], 'Owned By'[Opportunity Close Date], MINUTE) / (24*60), BLANK()), DOUBLE))

Nb of Closed Opportunities =
CALCULATE(DISTINCTCOUNT('Owned By'[Opportunity Id]), FILTER('Owned By', NOT 'Owned By'[Is Open Opportunity?]))

Opportunity Owner Class - Title =
IF([Opportunity Owner Class]=[pOpportunityOwner_Champions], "CHAMPIONS", IF([Opportunity Owner Class]=[pOpportunityOwner_GrowthPlanPipelineGeneration], "CLOSERS Growth Plan: Pipeline Generation", IF([Opportunity Owner Class]=[pOpportunityOwner_GrowthPlanClosing], "HUNTERS/FARMERS Growth Plan: Closing", "REQUIRED IMPROVEMENTS")))

Opportunity Owner Class (sort) =
IF([Opportunity Owner Class]=[pOpportunityOwner_Champions], 1, IF([Opportunity Owner Class]=[pOpportunityOwner_GrowthPlanPipelineGeneration], 2, IF([Opportunity Owner Class]=[pOpportunityOwner_GrowthPlanClosing], 3, 4)))

Opportunity Owner Class =
IF([Pipeline Profile - Conversion Rate (num)] > 3 && [Pipeline Profile - Pipeline Generation (num)] > 3, [pOpportunityOwner_Champions], IF([Pipeline Profile - Conversion Rate (num)] > 3 && [Pipeline Profile - Pipeline Generation (num)] <= 3, [pOpportunityOwner_GrowthPlanPipelineGeneration], IF([Pipeline Profile - Conversion Rate (num)] <= 3 && [Pipeline Profile - Pipeline Generation (num)] > 3, [pOpportunityOwner_GrowthPlanClosing], [pOpportunityOwner_RequiredImprovements])))

Opportunity Owner Class - Action =
SWITCH([Opportunity Owner Class], [pOpportunityOwner_Champions], "Reward these elements, they can be a model for the other owners. Leverage their best-practices.", [pOpportunityOwner_GrowthPlanPipelineGeneration], "Guide them on how to generate pipeline.", [pOpportunityOwner_GrowthPlanClosing], "Provide these elements additional trainings to improve their ability to convince clients.", [pOpportunityOwner_RequiredImprovements], "These opportunity owners need to improve their skills in both areas, to get more business && to win over clients. Train them quickly.")

Opportunity Owner Class - Description =
SWITCH([Opportunity Owner Class], [pOpportunityOwner_Champions], "Top performers in the team. They perform well in all areas && pull the team up.", [pOpportunityOwner_GrowthPlanPipelineGeneration], "Effective at closing && winning deals, they can develop in Pipeline Generation (farming || hunting).", [pOpportunityOwner_GrowthPlanClosing], "Good at developing pipeline, they will improve their performance by developing their ability to close && win the deals.", [pOpportunityOwner_RequiredImprovements], "Underperforming in pipeline generation && deal closing. ")

Conversion Rate (Last N Months - Closed Date) =
[Total Sales (Last N Months - Closed Date)]/[Total Closed Opportunities Amount (Last N Months - Closed Date)]

Total Sales (Last N Months - Closed Date) =
SUMX('Owned By', IF('Owned By'[Is Last N months filter - Closed Date?], 'Owned By'[_Total Sales (Expression)], BLANK()))

Pipeline Generation (Last N Months - Created Date) =
SUMX('Owned By', IF('Owned By'[Is Last N months filter - Created Date?], 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Pipeline Profile - Conversion Rate (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Conversion Rate (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Conversion Rate (num)])," ","☆")

Pipeline Profile - Conversion Rate =
IF(SUM('Owned By'[_Per Customer: Conversion Rate]) <= CALCULATE(MAX('Owned By'[_Per Customer: Conversion Rate]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Conversion Rate]) <= CALCULATE(MAX('Owned By'[_Per Customer: Conversion Rate]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Conversion Rate]) <= CALCULATE(MAX('Owned By'[_Per Customer: Conversion Rate]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Conversion Rate]) <= CALCULATE(MAX('Owned By'[_Per Customer: Conversion Rate]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Average Deal Size (description) =
SWITCH([Pipeline Profile - Average Deal Size], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Average Deal Size"

Pipeline Axis =
100

Pipeline Profile - Average Deal Size (num) =
INT([Pipeline Profile - Average Deal Size])

Pipeline Profile - Pipeline Generation (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Pipeline Generation (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Pipeline Generation (num)])," ","☆")

Pipeline Profile - Total Sales to Existing Clients =
IF(SUM('Owned By'[_Per Customer: Total Sales for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Existing Clients]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Total Sales for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Existing Clients]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Total Sales for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Existing Clients]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Total Sales for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Existing Clients]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Conversion Rate (description) =
SWITCH([Pipeline Profile - Conversion Rate], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Conversion Rate"

Pipeline Profile - Conversion Rate (num) =
INT([Pipeline Profile - Conversion Rate])

Pipeline Profile - Pipeline Generation to Existing Clients (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Pipeline Generation to Existing Clients (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Pipeline Generation to Existing Clients (num)])," ","☆")

Pipeline Profile - Average Deal Size =
IF(SUM('Owned By'[_Per Customer: Average Deal Size]) <= CALCULATE(MAX('Owned By'[_Per Customer: Average Deal Size]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Average Deal Size]) <= CALCULATE(MAX('Owned By'[_Per Customer: Average Deal Size]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Average Deal Size]) <= CALCULATE(MAX('Owned By'[_Per Customer: Average Deal Size]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Average Deal Size]) <= CALCULATE(MAX('Owned By'[_Per Customer: Average Deal Size]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Pipeline Generation (description) =
SWITCH([Pipeline Profile - Pipeline Generation], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Ability to generate pipeline"

Pipeline Profile - Pipeline Generation (num) =
INT([Pipeline Profile - Pipeline Generation])

Pipeline Profile - Pipeline Generation to Prospects (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Pipeline Generation to Prospects (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Pipeline Generation to Prospects (num)])," ","☆")

Pipeline Profile - Total Sales (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Total Sales (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Total Sales (num)])," ","☆")

Pipeline Profile - Total Sales to Existing Clients (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Total Sales to Existing Clients (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Total Sales to Existing Clients (num)])," ","☆")

Pipeline Profile - Total Sales to Prospects =
IF(SUM('Owned By'[_Per Customer: Total Sales for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Prospects]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Total Sales for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Prospects]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Total Sales for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Prospects]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Total Sales for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales for Prospects]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Total Sales to Existing Clients (description) =
SWITCH([Pipeline Profile - Total Sales to Existing Clients], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Ability to sell to existing clients"

Pipeline Profile - Total Sales to Existing Clients (num) =
INT([Pipeline Profile - Total Sales to Existing Clients])

Pipeline Profile - Total Sales to Prospects (description) =
SWITCH([Pipeline Profile - Total Sales to Prospects], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Ability to sell to prospects"

Pipeline Profile - Total Sales to Prospects (num) =
INT([Pipeline Profile - Total Sales to Prospects])

Pipeline Profile - Total Sales to Prospects (Star) =
SUBSTITUTE(REPT(" ", [Pipeline Profile - Total Sales to Prospects (num)])," ","★") & SUBSTITUTE(REPT(" ", 5-[Pipeline Profile - Total Sales to Prospects (num)])," ","☆")

Pipeline Profile - Pipeline Generation to Existing Clients =
IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Existing Clients]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Pipeline Generation to Existing Clients (description) =
SWITCH([Pipeline Profile - Pipeline Generation to Existing Clients], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Ability to generate pipeline with existing clients"

Pipeline Profile - Pipeline Generation to Existing Clients (num) =
INT([Pipeline Profile - Pipeline Generation to Existing Clients])

Pipeline Profile - Total Sales =
IF(SUM('Owned By'[_Per Customer: Total Sales]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Total Sales]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Total Sales]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Total Sales]) <= CALCULATE(MAX('Owned By'[_Per Customer: Total Sales]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Pipeline Generation to Prospects =
IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Prospects]), ALL('Owned By'))/5, "1", IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Prospects]), ALL('Owned By'))/5*2, "2", IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Prospects]), ALL('Owned By'))/5*3, "3", IF(SUM('Owned By'[_Per Customer: Pipeline Generation for Prospects]) <= CALCULATE(MAX('Owned By'[_Per Customer: Pipeline Generation for Prospects]), ALL('Owned By'))/5*4, "4", "5"))))

Pipeline Profile - Total Sales (description) =
SWITCH([Pipeline Profile - Total Sales], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Ability to sell"

Pipeline Profile - Pipeline Generation to Prospects (description) =
SWITCH([Pipeline Profile - Pipeline Generation to Prospects], "1", "VERY LOW", "2", "LOW", "3", "MEDIUM", "4", "HIGH", "5", "VERY HIGH") & " Ability to generate pipeline with prospects"

Pipeline Profile - Total Sales (num) =
INT([Pipeline Profile - Total Sales])

Pipeline Profile - Pipeline Generation to Prospects (num) =
INT([Pipeline Profile - Pipeline Generation to Prospects])

Probability (bucket) (sort) =
IF(MAX('Owned By'[_Avg Probability (Expression)]) < 0.25, 10, IF(MAX('Owned By'[_Avg Probability (Expression)]) < 0.50, 20, IF(MAX('Owned By'[_Avg Probability (Expression)]) < 0.75, 30, 40)))

Sales Value (for selected Opp Owner) =
MAXX('Owned By', IF('Owned By'[Is Selected Opportunity Owner Flag?], CALCULATE([Total Sales]), BLANK()))

Rank Conversion Rate (for selected Opp Owner) =
/* TODO: DAX conversion validation failed for Rank Sales Value (for selected Opp Owner) (copy)_1048775823272144897: unterminated double-quoted string literal */ BLANK()

Rank Total Opp Amount (for selected Opp Owner) =
/* TODO: DAX conversion validation failed for Rank Sales Value (for selected Opp Owner) (copy)_928867483237888003: unterminated double-quoted string literal */ BLANK()

Conversion Rate (for selected Opp Owner) =
MAXX('Owned By', IF('Owned By'[Is Selected Opportunity Owner Flag?], CALCULATE('Owned By'[Conversion Rate]), BLANK()))

Total Opp Amount (for selected Opp Owner) =
MAXX('Owned By', IF('Owned By'[Is Selected Opportunity Owner Flag?], CALCULATE([Pipeline Generated]), BLANK()))

Total Closed Opportunities Amount (Last N Months - Closed Date) =
SUMX('Owned By', IF('Owned By'[Is Last N months filter - Closed Date?], 'Owned By'[_Total Closed Opportunities Amount (Expression)], BLANK()))

Average Deal Size (Last N Months - Closed Date) =
SUMX('Owned By', IF('Owned By'[Is Last N months filter - Closed Date?], 'Owned By'[_Avg Deal Size (won) (Expression)], BLANK()))

Pipeline Generation for Existing Clients =
SUMX('Owned By', IF('Owned By'[Client/Prospect by Opportunity]="Existing Clients" && 'Owned By'[Is Last N months filter - Created Date?], 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Total Sales for Prospects =
SUMX('Owned By', IF('Owned By'[Client/Prospect by Opportunity]="Prospects" && 'Owned By'[Is Last N months filter - Closed Date?], 'Owned By'[_Total Sales (Expression)], BLANK()))

Pipeline Generation for Prospects =
SUMX('Owned By', IF('Owned By'[Client/Prospect by Opportunity]="Prospects" && 'Owned By'[Is Last N months filter - Created Date?], 'Owned By'[_Pipeline Generated (Expression)], BLANK()))

Days from Open to Close =
AVERAGEX('Owned By', CONVERT(DATEDIFF('Owned By'[CreatedDate (Owned By)], 'Owned By'[Opportunity Close Date], MINUTE) / (24*60), DOUBLE))

__MyToday =
DATE(2022,04,18)

Last N Months =
36

KPI_AvgOpportunitySize_Calculation =
"Average of [Opportunity Amount]"

KPI_AvgOpportunitySize_Description =
"Average amount of opportunities, whether they are open or closed (expressed in currency)"

KPI_SalesVelocity_Description =
"Determines how fast you are making money (you bring back about that much every day) (expressed in currency)"

KPI_AvgDealSizeWon_Description =
"Average amount of won opportunities (expressed in currency)"

KPI_TotalClosedOpportunitiesAmount_Description =
"Total amount of opportunities that are closed (expressed in currency)"

KPI_NbOpportunities_Calculation =
"Count Distinct of [Opportunity Id]"

KPI_NbClosedOpportunities_Description =
"Number of opportunities that are closed"

KPI_NbOpportunities_Description =
"Total number of opportunities (open or closed)"

KPI_PipelineValue_Description =
"Total amount of open opportunities (expressed in currency)"

KPI_NbWonOpportunities_Description =
"Number of opportunities that were won"

KPI_NbLostOpportunities_Description =
"Number of opportunities that were lost"

KPI_SalesCycle_Calculation =
"Average of TimeDifference([Opportunity Created Date], [Opportunity Closed Date])   (for closed opportunities only)"
isHidden

KPI_WeigthedPipelineValue_Description =
"Total amount of open opportunities, weighted by probability of closing (expressed in currency)"

KPI_WonLostRate_Description =
"Share of the number of opportunities won in relation to the number of all closed opportunities (expressed in \%)"

KPI_SalesCycle_Description =
"Average time it takes to close an opportunity (only considering won opportunities)"

KPI_SalesCycleLost_Calculation =
"Average of TimeDifference([Opportunity Created Date], [Opportunity Closed Date])   (for lost opportunities only)"
isHidden

KPI_SalesCycleLost_Description =
"Average time it takes to close an opportunity (only considering lost opportunities)"

KPI_SalesCycleWon_Calculation =
"Average of TimeDifference([Opportunity Created Date], [Opportunity Closed Date])   (for won opportunities only)"
isHidden

KPI_SalesCycleWon_Description =
"Average time it takes to win an opportunity"

KPI_TotalSales_Description =
"Total amount of opportunities won (expressed in amount)"

KPI_TotalPipelineGeneration_Calculation =
"Sum of [Opportunity Amount]"

KPI_TotalPipelineGeneration_Description =
"Total amount of opportunities created (expressed in amount)"

KPI_ConversionRate_Description =
"Share of the amount of opportunities won in relation to the amount of all closed opportunities (expressed in \%)"

KPI_NbOpenOpportunities_Description =
"Number of opportunities that are currently open"

Currency =
"$"

Organization Name =
"Salesforce"

Accelerator Title =
"Sales Pipeline"

Accelerator Log =
"LinPack messages (view comment for details)"

pSelectOpportunityOwner =
"Bellina Catmull"

pOpportunityOwner_Champions =
"CHAMPIONS"

pOpportunityOwner_GrowthPlanPipelineGeneration =
"GROWTH PLAN Pipeline Generation"

pOpportunityOwner_GrowthPlanClosing =
"GROWTH PLAN Closing"

pOpportunityOwner_RequiredImprovements =
"REQUIRED IMPROVEMENTS"

