table Rebounds
	lineageTag: e43ad619-f118-461e-a6e8-45d7e07b31ce

	measure Rebounds = SELECTEDVALUE('Rebounds'[Value], 1.0)
		lineageTag: 6994d16f-a3ca-4dac-bbec-6d14fbbf4c8e
		annotation Copilot_Description = DAX: SELECTEDVALUE('Rebounds'[Value], 1.0)

	column Value
		dataType: double
		lineageTag: b9c295a6-ff77-4871-ad95-67c8609870c2
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 8b458acd-0d1f-465b-b07e-a9404542e4fb
		summarizeBy: none
		sourceColumn: Name
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Rebounds-87f41ae6-dba7-49ee-a08f-338466472ab1' = calculated
		mode: import
		source = DATATABLE("Value", DOUBLE, "Name", STRING, {{1.0, "Average Deffensive Rebounds per Game"}, {2.0, "Average Offensive Rebounds per Game"}, {3.0, "Average Rebound per Game"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns and 1 measures: Value, Name.

