table Sheet1
	lineageTag: 1046158f-13cd-4f28-a7f4-a8e8f2f68b64

	measure 'p. Rebounds' = SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2c617af1-38ae-4012-a59d-66712fc7a488
		annotation Copilot_Description = Migrated from Tableau: CASE [Parameters].[Parameter 1] When 1 then avg([DEF]) When 2 then AVG([OFF]) When 3 then avg([REB]) END | DAX: SWITCH([Rebounds], 1, AVERAGE('Sheet1'[DEF]), 2, AVERAGE('Sheet1'[OFF]), 3, AVERAGE('Sheet1'[REB]))

	measure 'min(1)' = MINX('Sheet1', 1)
		displayFolder: Measures
		lineageTag: fd9f40a8-fea2-4225-9153-12daa96c6359
		annotation Copilot_Description = Migrated from Tableau: min(1) | DAX: MINX('Sheet1', 1)

	column Player
		dataType: string
		lineageTag: 68f63ed3-55a2-4925-831c-1959cc0a8f94
		summarizeBy: none
		sourceColumn: Player

		annotation SummarizationSetBy = Automatic

	column YR
		dataType: int64
		lineageTag: 3a1816b2-c6df-4b1f-b253-adb1fb6eeb4d
		summarizeBy: sum
		sourceColumn: YR

		annotation SummarizationSetBy = Automatic

	column TM
		dataType: string
		lineageTag: d8b2d41f-ffa3-4531-ab8a-bf9c51aeb26a
		summarizeBy: none
		sourceColumn: TM

		annotation SummarizationSetBy = Automatic

	column GP
		dataType: int64
		lineageTag: f5cfd20b-8c96-4c40-a183-7ec709d6ec3a
		summarizeBy: sum
		sourceColumn: GP

		annotation SummarizationSetBy = Automatic

	column MIN
		dataType: double
		formatString: #,0.00
		lineageTag: 9ea3c4fb-c576-40cc-aa0c-7e686dbc66e2
		summarizeBy: sum
		sourceColumn: MIN

		annotation SummarizationSetBy = Automatic

	column FGM
		dataType: double
		formatString: #,0.00
		lineageTag: 18a364da-bef0-4452-b357-8278ae59ba36
		summarizeBy: sum
		sourceColumn: FGM

		annotation SummarizationSetBy = Automatic

	column FGA
		dataType: double
		formatString: #,0.00
		lineageTag: 522c9423-ef70-4965-8c1a-fbae167bc760
		summarizeBy: sum
		sourceColumn: FGA

		annotation SummarizationSetBy = Automatic

	column 'FG%'
		dataType: double
		formatString: #,0.00
		lineageTag: 89712f9e-7759-415d-a12e-7151ded4fc23
		summarizeBy: sum
		sourceColumn: 'FG%'

		annotation SummarizationSetBy = Automatic

	column '3PT%'
		dataType: double
		formatString: #,0.00
		lineageTag: 711b015f-5296-4d05-85ab-1026f53a71cc
		summarizeBy: sum
		sourceColumn: '3PT%'

		annotation SummarizationSetBy = Automatic

	column 'FT%'
		dataType: double
		formatString: #,0.00
		lineageTag: dfe382ea-da7b-4257-b0b9-2d1672f2eaf8
		summarizeBy: sum
		sourceColumn: 'FT%'

		annotation SummarizationSetBy = Automatic

	column OFF
		dataType: double
		formatString: #,0.00
		lineageTag: 3dcc0f87-54d0-446e-b1f6-a636d0ff7667
		summarizeBy: sum
		sourceColumn: OFF

		annotation SummarizationSetBy = Automatic

	column DEF
		dataType: double
		formatString: #,0.00
		lineageTag: 105057bb-5943-4853-9ed8-8949f4a23de3
		summarizeBy: sum
		sourceColumn: DEF

		annotation SummarizationSetBy = Automatic

	column REB
		dataType: double
		formatString: #,0.00
		lineageTag: 7b31a023-7ce0-4a0f-8b61-a4a2f64154a5
		summarizeBy: sum
		sourceColumn: REB

		annotation SummarizationSetBy = Automatic

	column ASST
		dataType: double
		formatString: #,0.00
		lineageTag: 01aa96a4-e8c3-4aab-bdce-b24168ca0762
		summarizeBy: sum
		sourceColumn: ASST

		annotation SummarizationSetBy = Automatic

	column STL
		dataType: double
		formatString: #,0.00
		lineageTag: 005b7777-6db0-4f62-b7b0-80a66453192c
		summarizeBy: sum
		sourceColumn: STL

		annotation SummarizationSetBy = Automatic

	column BLK
		dataType: double
		formatString: #,0.00
		lineageTag: 737d32e8-4c90-498a-9c66-bec67f97043e
		summarizeBy: sum
		sourceColumn: BLK

		annotation SummarizationSetBy = Automatic

	column TO
		dataType: double
		formatString: #,0.00
		lineageTag: 4ef03b34-e51a-44cb-895e-bfac04b69353
		summarizeBy: sum
		sourceColumn: TO

		annotation SummarizationSetBy = Automatic

	column PF
		dataType: double
		formatString: #,0.00
		lineageTag: b7a7ad7d-67b4-450b-9272-cd813d8ee853
		summarizeBy: sum
		sourceColumn: PF

		annotation SummarizationSetBy = Automatic

	column PTS
		dataType: double
		formatString: #,0.00
		lineageTag: e96e6f7e-8265-47c1-bfd4-17051b7ba643
		summarizeBy: sum
		sourceColumn: PTS

		annotation SummarizationSetBy = Automatic

	column 'Action (Player)'
		dataType: string
		lineageTag: eea73c8e-aca9-4d34-b672-a1653f2f28c9
		summarizeBy: none
		sourceColumn: 'Action (Player)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Sheet1-6849552a-3363-4fae-8a7a-f72085d4c1a1' = m
		mode: import
		source =
				let
				    // Source Excel: nba_players.xlsx
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\nba_players.xlsx"), null, true),
				
				            _nav = _src{[Item="Sheet1",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Player", "YR", "TM", "GP", "MIN", "FGM", "FGA", "FG%", "3PT%", "FT%", "OFF", "DEF", "REB", "ASST", "STL", "BLK", "TO", "PF", "PTS"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Player", type text},
				        {"YR", Int64.Type},
				        {"TM", type text},
				        {"GP", Int64.Type},
				        {"MIN", type number},
				        {"FGM", type number},
				        {"FGA", type number},
				        {"FG%", type number},
				        {"3PT%", type number},
				        {"FT%", type number},
				        {"OFF", type number},
				        {"DEF", type number},
				        {"REB", type number},
				        {"ASST", type number},
				        {"STL", type number},
				        {"BLK", type number},
				        {"TO", type number},
				        {"PF", type number},
				        {"PTS", type number}
				    }),
				    #"Added Action (Player)" = Table.AddColumn(#"Changed Types", "Action (Player)", each Text.From([#"Player"]), type text),
				    Result = #"Added Action (Player)"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 20 columns and 2 measures: Player, YR, TM, GP, MIN, FGM, FGA, FG%, ... (20 columns total).

