expression DataFolder = "C:\\Users\\pidoudet\\OneDrive - Microsoft\\Boulot\\PBI SME\\OracleToPostgre\\TableauToPowerBI\\artifacts\\bug_bash\\Ventes_France\\Data" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression ServerName = "db.entreprise.fr:5432" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression DatabaseName = "ventes_db" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]