expression DataFolder = "C:\Users\pidoudet\OneDrive - Microsoft\Boulot\PBI SME\OracleToPostgre\TableauToPowerBI\artifacts\test_m_check\TABLEAU_10_TWBX\Data\Datasources" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression ServerName = "mssql2012.test.tsi.lan" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression DatabaseName = "TestV1" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]