table Calendar
	lineageTag: 975205eb-e3db-4e13-bd0c-36926b3279d9

	measure 'Year To Date' = TOTALYTD([Profit Ratio], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: a290411b-0dfe-4cb4-9880-10da22af698f
		annotation Copilot_Description = DAX: TOTALYTD([Profit Ratio], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 89212258-f0ee-4e81-9eda-eb0907b1354c
		annotation Copilot_Description = DAX: CALCULATE([Profit Ratio], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: de610a48-f17a-4d66-8d6c-8fd88dfdf5aa
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4aa4a28e-378c-4a2d-b426-d4d9158be17c
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 35214e34-27ff-4112-b23b-5128d4a465f4
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e6221b71-244e-45be-9f19-9e3ceeb6e303
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 3bb269ad-e947-4581-829b-ab0e2453d4be
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: fd472e42-0888-4d45-958e-246e183f954c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 8ae9f51a-0127-40a5-bc9c-a8237c90dc42
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 41add8e7-e8dd-4e14-98fb-3a0d67709cbe
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: f398d88c-fe98-4e2c-ac50-c03f8e19bbc6
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 405993cd-6894-4ce9-85c9-b33aa8b0f58d

		level Year
			ordinal: 0
			column: Year
			lineageTag: f4f0844a-ceac-4b05-a8ea-6f4749735de8

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 9746c193-b610-4a4e-bcf2-7c0cd189cb3c

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: bd716f93-3ae7-491c-9cea-d5b32afe915e

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9cb48084-50be-4a4b-a80b-4425f7bed3f2


	partition 'Calendar-21fb29fb-6bb0-46d5-864c-19d94b3eed7d' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

