table 'Profit Bin Size'
	lineageTag: e781ff7d-3df9-47d3-92b5-bed125d5c5b9

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 1b35a614-cebc-4834-a154-b4679e82ff18
		annotation Copilot_Description = DAX: SELECTEDVALUE('Profit Bin Size'[Value], 200)

	column Value
		dataType: int64
		lineageTag: 3975f1b9-0d4e-4243-a9b7-990c7e04a1bb
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-07be3895-dbc2-439a-affa-20060fc7945b' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

