table 'Top Customers'
	lineageTag: 3c7b44d3-d910-4208-b606-d876466489b3

	measure 'Top Customers' = SELECTEDVALUE('Top Customers'[Value], 5)
		lineageTag: d3edb915-df11-4a11-a202-545f9fb5e6ee
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top Customers'[Value], 5)

	column Value
		dataType: int64
		lineageTag: 019ad662-9442-48dc-8fb3-8e63742382fb
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top Customers-75b52825-e4e3-4c06-a54e-4bc5477d4d0b' = calculated
		mode: import
		source = GENERATESERIES(5, 20, 5)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

