table Extract
	lineageTag: 6b735503-d7c0-470f-8146-a5b050b1528c

	measure 'GDP % of Total' = AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 86acd3f4-82f2-4187-888d-869b5f5fc77e
		annotation Copilot_Description = Migrated from Tableau: AVG([F: GDP per capita (curr $)]) / TOTAL(AVG([F: GDP per capita (curr $)])) | DAX: AVERAGE('Extract'[F: GDP per capita (curr $)]) / CALCULATE(AVERAGE('Extract'[F: GDP per capita (curr $)]), ALL('Extract'))

	measure 'GDP per capita (weighted)' = SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 9e15412d-3e16-4c4c-816b-3ce7c267964d
		annotation Copilot_Description = Migrated from Tableau: SUM([F: GDP (curr $)]) / SUM([P: Population (count)]) | DAX: SUM('Extract'[F: GDP (curr $)]) / SUM('Extract'[P: Population (count)])

	measure 'Rate spread (difference)' = AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 82fa5e19-30e0-4d2b-8b4c-9874c4a44bb3
		annotation Copilot_Description = Migrated from Tableau: AVG([F: Lending interest rate (%)])-AVG([F: Deposit interest rate (%)]) | DAX: AVERAGE('Extract'[F: Lending interest rate (%)])-AVERAGE('Extract'[F: Deposit interest rate (%)])

	measure 'Number of Records' = 1
		displayFolder: Measures
		lineageTag: 1133a5c4-33ac-44ae-8f14-fd1d8622b144
		annotation Copilot_Description = Migrated from Tableau: 1 | DAX: 1

	measure 'GDP per capita (weighted) Formatted' = VAR _val = [GDP per capita (weighted)] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 227eb21e-726a-4e3d-8c04-8b21e317b997
		annotation Copilot_Description = Dynamic numeric abbreviation for GDP per capita (weighted) (K/M/B)

	column 'Country / Region'
		dataType: string
		lineageTag: 12149725-3bb4-4f23-8f4a-f046f9063c5f
		summarizeBy: none
		sourceColumn: 'Country / Region'
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3eb1a102-318e-4730-8a78-b1bc6c8def1a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'F: Deposit interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 97ac1a7b-e439-4a8d-863d-dbfba58aeda5
		summarizeBy: sum
		sourceColumn: 'F: Deposit interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.00B;("$"#,#0,,.00B)
		lineageTag: 7d08eaf5-a67b-4ef2-b7b3-a925a05d91d9
		summarizeBy: sum
		sourceColumn: 'F: GDP (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: GDP per capita (curr $)'
		dataType: double
		formatString: c"$"#,#0,.0K;("$"#,#0,.0K)
		lineageTag: b2001ecd-0393-40de-b9f9-a37836b29e99
		summarizeBy: sum
		sourceColumn: 'F: GDP per capita (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'F: Lending interest rate (%)'
		dataType: double
		formatString: #,0.00
		lineageTag: 64a89560-1611-4b7c-83f5-ac1478074114
		summarizeBy: sum
		sourceColumn: 'F: Lending interest rate (%)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp (% GDP)'
		dataType: double
		formatString: #,0.00
		lineageTag: 6ceb2ed6-75ee-43f5-b42f-669493a6d02c
		summarizeBy: sum
		sourceColumn: 'H: Health exp (% GDP)'

		annotation SummarizationSetBy = Automatic

	column 'H: Health exp/cap (curr $)'
		dataType: double
		formatString: c"$"#,#0,,.0B;("$"#,#0,,.0B)
		lineageTag: ebe3020f-c673-4cfa-9876-f8ef89418487
		summarizeBy: sum
		sourceColumn: 'H: Health exp/cap (curr $)'

		annotation SummarizationSetBy = Automatic

	column 'H: Life exp (years)'
		dataType: double
		formatString: n#,0;-#,0
		lineageTag: d1e216e8-ee60-440d-a7d6-448256b21ed5
		summarizeBy: sum
		sourceColumn: 'H: Life exp (years)'

		annotation SummarizationSetBy = Automatic

	column 'Number of Records'
		dataType: int64
		lineageTag: 5860ff05-fc7d-46f3-bb71-63b6cd55fcab
		summarizeBy: sum
		sourceColumn: 'Number of Records'

		annotation SummarizationSetBy = Automatic

	column 'P: Population (count)'
		dataType: double
		formatString: #,0.00
		lineageTag: c55bcc10-ea4b-4986-a6d4-cb4d8e6bf4d4
		summarizeBy: sum
		sourceColumn: 'P: Population (count)'

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 03627b6e-e0e0-4bde-837c-9cb63c39eb6a
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Subregion
		dataType: string
		lineageTag: ebebae6a-826e-48fd-982c-71b8773d0fc1
		summarizeBy: none
		sourceColumn: Subregion
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Action (Country Name)'
		dataType: string
		lineageTag: e71976f0-f403-453c-b483-ee1ab9ab3802
		summarizeBy: none
		sourceColumn: 'Action (Country Name)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Date (year))'
		dataType: string
		lineageTag: 043a0c8d-92c0-4c65-99d2-568d913127ec
		summarizeBy: none
		sourceColumn: 'Action (Date (year))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (Region)'
		dataType: string
		lineageTag: 4791b194-7deb-49ed-9b57-3b69a4169869
		summarizeBy: none
		sourceColumn: 'Action (Region)'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Action (YEAR(Date (year)))'
		dataType: string
		lineageTag: ec4151dd-92fc-45ec-89b9-cfaa5542b920
		summarizeBy: none
		sourceColumn: 'Action (YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	column 'Exclusions (Country Name,YEAR(Date (year)))'
		dataType: string
		lineageTag: b8d0f4f0-3d27-4aca-a42d-e4fefe0413db
		summarizeBy: none
		sourceColumn: 'Exclusions (Country Name,YEAR(Date (year)))'
		displayFolder: Groups

		annotation SummarizationSetBy = Automatic

	partition 'Extract-fdcbcc9f-2a23-4b25-baf4-e6819a987016' = m
		mode: import
		source =
				let
				    // TODO: Configure the data source for connector type: DATAENGINE
				    // Replace the sample table below with the actual source expression.
				    Source = try
				        #table(
				            {"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"},
				            {
				                {"Sample 1", 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, "Sample 12", "Sample 13"},
				                {"Sample 2", 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "Sample 13", "Sample 14"}
				            }
				        )
				    otherwise
				        #table({"Country / Region", "Date", "F: Deposit interest rate (%)", "F: GDP (curr $)", "F: GDP per capita (curr $)", "F: Lending interest rate (%)", "H: Health exp (% GDP)", "H: Health exp/cap (curr $)", "H: Life exp (years)", "Number of Records", "P: Population (count)", "Region", "Subregion"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date (year)"}, {"F: Deposit interest rate (%)", "Deposit interest rate (%)"}, {"F: GDP (curr $)", "GDP (curr $)"}, {"F: GDP per capita (curr $)", "GDP per capita (curr $)"}, {"F: Lending interest rate (%)", "Lending interest rate (%)"}, {"H: Health exp (% GDP)", "Health exp (% GDP)"}, {"H: Health exp/cap (curr $)", "Health exp/cap (curr $)"}, {"H: Life exp (years)", "Life exp (years)"}, {"P: Population (count)", "Population (count)"}}),
				    #"Added Action (Country Name)" = Table.AddColumn(#"Renamed Columns", "Action (Country Name)", each Text.From([#"Country / Region"]), type text),
				    #"Added Action (Date (year))" = Table.AddColumn(#"Added Action (Country Name)", "Action (Date (year))", each Text.From([#"Date"]), type text),
				    #"Added Action (Region)" = Table.AddColumn(#"Added Action (Date (year))", "Action (Region)", each Text.From([#"Region"]), type text),
				    #"Added Action (YEAR(Date (year)))" = Table.AddColumn(#"Added Action (Region)", "Action (YEAR(Date (year)))", each Text.From(Date.Year([#"Date"])), type text),
				    #"Added Exclusions (Country Name,YEAR(Date (year)))" = Table.AddColumn(#"Added Action (YEAR(Date (year)))", "Exclusions (Country Name,YEAR(Date (year)))", each Text.From([#"Country / Region"]) & " | " & Text.From(Date.Year([#"Date"])), type text),
				    Result = #"Added Exclusions (Country Name,YEAR(Date (year)))"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 18 columns and 5 measures: Country / Region, Date, F: Deposit interest rate (%), F: GDP (curr $), F: GDP per capita (curr $), F: Lending interest rate (%), H: Health exp (% GDP), H: Health exp/cap (curr $), ... (18 columns total).

