table 'Profit Bin Size'
	lineageTag: ac8e0d9b-ee13-457b-bdab-151bd05e0f99

	measure 'Profit Bin Size' = SELECTEDVALUE('Profit Bin Size'[Value], 200)
		lineageTag: 3c57c49e-d0ed-4c22-aad0-cf29918c89d6
		annotation Copilot_Description = DAX: SELECTEDVALUE('Profit Bin Size'[Value], 200)

	column Value
		dataType: int64
		lineageTag: 4246292f-b07a-44f6-a9c4-cd7d30fb9b1f
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Profit Bin Size-cec2f7c3-fc53-4eb9-a64b-fed1e5ec8dc8' = calculated
		mode: import
		source = GENERATESERIES(50, 200, 50)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

