// DAX measures for table: Commandes
// Auto-generated by Tableau → Power BI migration

Chiffre d''Affaires Brut =
SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire])

Chiffre d''Affaires Net =
SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise]), 0))

Marge Brute =
SUMX('Produits', IF(LOOKUPVALUE(Commandes[statut], Commandes[produit_id], Produits[produit_id]) <> "Annulée", (LOOKUPVALUE(Commandes[quantite], Commandes[produit_id], Produits[produit_id]) * LOOKUPVALUE(Commandes[prix_unitaire], Commandes[produit_id], Produits[produit_id]) * (1 - LOOKUPVALUE(Commandes[remise], Commandes[produit_id], Produits[produit_id]))) - (LOOKUPVALUE(Commandes[quantite], Commandes[produit_id], Produits[produit_id]) * 'Produits'[cout_achat]) - LOOKUPVALUE(Commandes[frais_port], Commandes[produit_id], Produits[produit_id]), 0))

Taux de Marge (%) =
IF(ISBLANK([Marge Brute] / [Chiffre d"Affaires Net]), 0, [Marge Brute] / [Chiffre d"Affaires Net])
isHidden

Montant Remises =
SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * 'Commandes'[remise])

Nombre de Commandes =
DISTINCTCOUNT('Commandes'[commande_id])

Clients Uniques =
DISTINCTCOUNT('Commandes'[client_id])

Panier Moyen =
/* TODO: DAX conversion validation failed for Calc_PanierMoyen: unterminated single-quoted identifier */ BLANK()

CA par Client =
CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), ALLEXCEPT('Commandes', 'Commandes'[client_id]))

CA Régional par Catégorie =
CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Commandes'[region]), REMOVEFILTERS('Produits'[categorie]))

CA hors Produit =
CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Produits'[nom_produit]))

Classification Client =
IF([CA par Client] > 50000, "Platine", IF([CA par Client] > 20000, "||", IF([CA par Client] > 5000, "Argent", "Bronze")))

Cumul Mobile CA =
/* TODO: DAX conversion validation failed for Calc_CumulCA: unconverted Tableau function token detected in DAX output */ BLANK()

Moyenne Mobile 3M =
CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('Commandes'[commande_id]), ASC)), ALL('Commandes')) /* WINDOW.AVG: frame SUM('Commandes'[-2,0]) */
isHidden

Classement CA =
RANKX(ALL('Commandes'), SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]))

CA Année en Cours =
CALCULATE(SUMX('Commandes', IF(YEAR('Commandes'[date_commande]) = YEAR(TODAY()), 'Commandes'[quantite] * 'Commandes'[prix_unitaire], 0)), ALL('Commandes'))

Période d''Analyse =
"Année"

