table 'Base Salary'
	lineageTag: 4947c249-fb96-43e0-b20a-a7b185066d0f

	measure 'Base Salary' = SELECTEDVALUE('Base Salary'[Value], 50000)
		lineageTag: ab92ebd8-b3c4-40d2-91ec-5b51be5d00ed
		annotation Copilot_Description = DAX: SELECTEDVALUE('Base Salary'[Value], 50000)

	column Value
		dataType: int64
		lineageTag: cb17761d-1e6c-414f-b621-fee531f8d7d2
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Base Salary-aa14b2cb-1a54-4540-b672-a41133137f4f' = calculated
		mode: import
		source = GENERATESERIES(0, 100, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

