table Calendar
	lineageTag: ae8b981d-13b8-49c7-acb9-15a434c869cc

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8ab94ec0-346a-4921-9ec9-27ccc373953d
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: fd993807-ccc0-4e1b-b881-92feeed61099
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: de7dcc0a-ef51-4089-8471-dad13addc4c7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 08d2e8e0-5477-4fa7-b06b-8815cb0fdb5f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 720eae5e-259a-4c44-91aa-9674566656a2
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 47abf53a-e62a-4438-bec0-4cdbe62b3d0b
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 0d8d96d2-71ec-4e6d-a255-087bf877c1fc
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 49d89126-9358-4cbf-b2ad-002f2071af8a
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b29d76e3-cb0f-41ed-a74d-61321099e5f5

		level Year
			ordinal: 0
			column: Year
			lineageTag: b5a401d1-812e-405f-b15a-6b4e4a9daf44

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 34877eb5-46ea-4f84-9a6d-4fe9b1b48a18

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: c62128c7-2cfe-4f05-aa51-55700a618d0c

		level Day
			ordinal: 3
			column: Day
			lineageTag: 8fdfc850-99d6-4af0-bc90-17b54cbb32f5


	partition 'Calendar-4caa2b7e-52dd-4690-956b-24a69710d1f0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

