table 'Churn Rate'
	lineageTag: 6bbe48ac-14b2-41bc-9626-856add49a205

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: b66a7d32-6a9c-415c-a4f7-0cd27dc35fe8
		annotation Copilot_Description = DAX: SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)

	column Value
		dataType: double
		lineageTag: d854a9e6-5016-4b45-b65c-407b5a75470e
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-ad4d3e6a-aacb-429e-b221-75db86dba052' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

