table 'Commission Rate'
	lineageTag: 71f6ec07-9405-4fbf-84a5-63038bb7d64f

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 22121328-36fa-4bd3-be1f-127b7bd71a31
		annotation Copilot_Description = DAX: SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)

	column Value
		dataType: double
		lineageTag: aca71c7a-6d7c-4c62-911b-06d3104f243d
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-b8fa96c4-bd9c-45ce-b23e-5e18904d56ea' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

