table 'New Business Growth'
	lineageTag: 178b48a3-fc55-4979-a7bb-0a03a71e8afe

	measure 'New Business Growth' = SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)
		lineageTag: a38558c5-b968-4973-95d6-6643d065df00
		annotation Copilot_Description = DAX: SELECTEDVALUE('New Business Growth'[Value], 0.59999999999999998)

	column Value
		dataType: double
		lineageTag: 341b9f33-104c-422c-9df3-7e50bab141bd
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'New Business Growth-a58ce37f-50c6-42d9-bf9a-156773814f7f' = calculated
		mode: import
		source = GENERATESERIES(0.0, 1.0, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

