table State
	lineageTag: 7d61bb9b-a4c1-4b3c-ba12-456c487ab968

	measure State = SELECTEDVALUE('State'[Value], "Alabama")
		lineageTag: 2079524b-205b-451b-8b51-7150517d8f7c
		annotation Copilot_Description = DAX: SELECTEDVALUE('State'[Value], "Alabama")

	column Value
		dataType: string
		lineageTag: 6db23a45-fd9e-4614-84ec-d028ea184bf8
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'State-533f8858-7668-4147-a806-2d91dea34c26' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"Alabama"}, {"Arizona"}, {"Arkansas"}, {"California"}, {"Colorado"}, {"Connecticut"}, {"Delaware"}, {"District of Columbia"}, {"Florida"}, {"Georgia"}, {"Idaho"}, {"Illinois"}, {"Indiana"}, {"Iowa"}, {"Kansas"}, {"Kentucky"}, {"Louisiana"}, {"Maine"}, {"Maryland"}, {"Massachusetts"}, {"Michigan"}, {"Minnesota"}, {"Mississippi"}, {"Missouri"}, {"Montana"}, {"Nebraska"}, {"Nevada"}, {"New Hampshire"}, {"New Jersey"}, {"New Mexico"}, {"New York"}, {"North Carolina"}, {"North Dakota"}, {"Ohio"}, {"Oklahoma"}, {"Oregon"}, {"Pennsylvania"}, {"Rhode Island"}, {"South Carolina"}, {"South Dakota"}, {"Tennessee"}, {"Texas"}, {"Utah"}, {"Vermont"}, {"Virginia"}, {"Washington"}, {"West Virginia"}, {"Wisconsin"}, {"Wyoming"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

