table Calendar
	lineageTag: 60c6a963-f779-42a5-a800-1cd987441fec

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c277e2d0-2999-44bb-bc32-0dbfebb52d95
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 31391820-6227-4e30-824b-07e4e715c304
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1cadf705-fa5c-40f2-8243-b5f96fa3f3d7
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d3065447-a671-40cf-9893-7583fa39082e
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: bdfd63f7-a723-4cf0-9b0c-b393deb93103
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e6ac3c6e-7b6d-4dea-b79e-1ccd86864ac5
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 9053a5fc-63d0-47bc-9500-bbe666b96332
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 875c894e-5256-4a3f-98c6-d0756e5f598e
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7855b4ab-d6e0-4bf5-9882-4b25223a79d5

		level Year
			ordinal: 0
			column: Year
			lineageTag: 29205e0c-7a52-4434-9534-51adad675f26

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: f3ee9a05-524c-4dc6-bfe7-568a901cd5f0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 7a22d865-3677-46f7-90db-1936bca974ca

		level Day
			ordinal: 3
			column: Day
			lineageTag: 260c61f0-0890-43de-8744-81b41c89e8f5


	partition 'Calendar-1517a415-0749-45e3-9fe2-5f5aad5091e0' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

