table 'Churn Rate'
	lineageTag: fcfe07c9-db23-41fe-b074-82ec36245b3e

	measure 'Churn Rate' = SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)
		lineageTag: 4eb1371d-acdd-44ac-9b9c-fe4de268dc11
		annotation Copilot_Description = DAX: SELECTEDVALUE('Churn Rate'[Value], 0.064000000000000001)

	column Value
		dataType: double
		lineageTag: bacb8d68-e32b-4f51-a1fc-6c6f80ab92fe
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Churn Rate-242aca52-bf98-4362-8509-230575db30a8' = calculated
		mode: import
		source = GENERATESERIES(0.0, 0.25, 0.001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

