table 'Commission Rate'
	lineageTag: 65cf4e26-118f-4d35-bfd6-07ab87d50ff2

	measure 'Commission Rate' = SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)
		lineageTag: 45dcbaa6-5d48-4a94-94c0-c86d7ee33712
		annotation Copilot_Description = DAX: SELECTEDVALUE('Commission Rate'[Value], 18.400000000000002)

	column Value
		dataType: double
		lineageTag: dd42a6e6-459b-4c60-8c0e-49d9f8a0de18
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Commission Rate-69f7d1c6-0b4e-4322-b531-583ed280c7f9' = calculated
		mode: import
		source = GENERATESERIES(1.0, 100.0, 0.10000000000000001)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

