table Employees
	lineageTag: 3bddcf69-23e2-410f-9a9a-74f128e7bbba

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e59bd12a-5edc-473d-b0f2-8b05646cde64
		annotation Copilot_Description = Migrated from Tableau: AVG([Salary]) | DAX: AVERAGE('Employees'[Salary])

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: 927591ab-c64a-4cb4-998d-e0f48e87b65d
		annotation Copilot_Description = Migrated from Tableau: COUNT([EmployeeID]) | DAX: COUNT('Employees'[EmployeeID])

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f2d04e84-7cb8-4929-8377-b9287914b398
		annotation Copilot_Description = Migrated from Tableau: SUM([Salary]) * 1.25 | DAX: SUM('Employees'[Salary]) * 1.25

	measure 'Total Compensation Formatted' = VAR _val = [Total Compensation] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: e5f3be29-0820-4572-9447-439de18188f9
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Compensation (K/M/B)

	column EmployeeID
		dataType: int64
		lineageTag: 7ea31bf7-8256-497e-8cda-d0c082a978cd
		summarizeBy: sum
		sourceColumn: EmployeeID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 01da214d-da68-4ec0-a497-fab2c322e95f
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 6f44fe70-8c30-4a3e-93f9-e685d20473b8
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 84f8a5b9-880f-4043-a16f-954dcc4056a5
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: b7067079-6ddd-4532-942b-93665f99de3d
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 95698503-c780-4995-af79-3a985d27e639
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: 8c6710a1-f5c0-47b4-8d6e-a0024fe3c0d9
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 06897a97-8972-43d7-9981-dbaa7083e91f
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: 7b0e923d-40a9-40f9-a98d-eee096ed7f03
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: b7479574-9c56-4af2-bd1f-099f2cc2bcce
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: 1e4616a1-86d9-4c7b-8168-972c909e3338
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: e6018add-0b88-4319-bf7d-1bd178f92a6b
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-ae810652-eb6b-481f-974a-bd5a3aacfe12' = m
		mode: import
		source =
				let
				    // Source SQL Server
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "HRDatabase"),
				
				            _nav = _src{[Schema="dbo", Item="Employees"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Added Tenure Category" = Table.AddColumn(_nav, "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns and 4 measures: EmployeeID, FirstName, LastName, HireDate, Department, JobTitle, Salary, Location, ... (12 columns total).

