expression DataFolder = "C:\\Users\\pidoudet\\OneDrive - Microsoft\\Boulot\\PBI SME\\OracleToPostgre\\TableauToPowerBI\\artifacts\\bug_bash\\Financial_Report\\Data" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression ServerName = "db.company.com:5432" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]

expression DatabaseName = "finance" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]